### ISSUE TITLE
Retrieve System Defined Scanning Intervals

### ISSUE THREAD

**Issue by ChrisPennell** [lordmilko/PrtgAPI#100]
**What's going on?**

Hi, I am currently using the PrtgAPI in Powershell and am very impressed. We have a need to automate adjustment of sensor scanning intervals that have 24hour Intervals and adjust them for Daylight Saving Time. The API provides everything to achieve this. One question :- Is there a way to extract\list the of Scanning Intervals listed on the PRTG GUI  System Admin Page?

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [x] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi Chris,

You can retrieve the "Scanning Intervals" setting from the System Administration -> Monitoring tab by retrieving the *Web Server Options* object from PRTG and then listing its raw object properties

```powershell
C:\> $intervals = (Get-Object -Id 810 | Get-ObjectProperty -Raw).sensorintervals -split "`n"
C:\> $intervals

5s
10s
30s
1m
5m
10m
15m
30m
1h
4h
6h
12h
1d

```

Regards,
lordmilko

**Comment by ChrisPennell** [comment]
Perfect thanks, that completes the configuration I need to automate DST
adjustment of sensors  with 24 hour Intervals.
Regards
Chris
