### ISSUE TITLE
Create multi Devices and groupe in PRTG

### ISSUE THREAD

**Issue by mbensaid23** [lordmilko/PrtgAPI#105]
Hello, 
I work in a company where we use Nagios as supervision tools, now we switch to PRTG, and as we have a loan plus 500 equipment it is difficult to do it manually, so I wanted to know how to add a CSV extraction of nagios equipment to PRTG (name, equipment type or group, ip address). Thank you in advance.

**Comment by lordmilko** [comment]
Hi @mbensaid23,

Please see the following [blog post](https://blog.paessler.com/how-to-add-hundreds-of-devices-to-prtg) from Paessler which describes exactly how to achieve this. You can find more information about how to use PrtgAPI by viewing the [wiki](https://github.com/lordmilko/PrtgAPI/wiki)

Regards,
lordmilko

**Comment by mbensaid23** [comment]
@lordmilko ,

Thanks for your help I'll look into it and keep you informed of the rest. 👍 🥇 

Best Regards

**Comment by mbensaid23** [comment]
Yes, I'm interested, I'd like you to share it with me the script. Thank you. 
Best Regards
