### ISSUE TITLE
PRTG monitoring tasks scheduled 

### ISSUE THREAD

**Issue by mbensaid23** [lordmilko/PrtgAPI#106]
hello

it is possible with PRTG to monitoring scheduled Windows tasks ?

regards

**Comment by lordmilko** [comment]
Hi @mbensaid23,

Please be advised that PrtgAPI is a third party product for interfacing with the PRTG API; for questions specific to PRTG itself you should post a question on the PRTG forums ([kb.paessler.com](https://kb.paessler.com)).

Paessler used to support monitoring scheduled tasks, however this functionality has now been removed. You can implement this functionality yourself however by creating your own [custom sensor](https://www.paessler.com/manuals/prtg/exe_script_advanced_sensor) using PowerShell. Using cmdlets like `Get-ScheduledTask` you can then retrieve the information you need and then display it in PRTG.

Regards,
lordmilko
