### ISSUE TITLE
Unable to add all targets to sensor that are actually detected. 

### ISSUE THREAD

**Issue by mattwiener1** [lordmilko/PrtgAPI#107]
**What's going on?**

Creating SSH Disk Sensors, it does not get all targets. 
If i run

client.Targets.GetSensorTargets(device.Id, "sshdiskfree");

it shows them all, but when adding the sensor it only gets the first one. 

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [x ] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x ] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @mattwiener1,

When creating sensors with Dynamic Sensor Parameters, by default only the first target is selected. As per [the example](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#targets) on the wiki, if you want to use additional targets you need to explicitly say so

```c#
//Create a new set of parameters for adding one or more VMware Datastore sensors
var parameters = client.GetDynamicSensorParameters(1001, "vmwaredatastoreextern");

//Select all datastores supported by the device
parameters["datafieldlist__check"] = parameters.Targets["datafieldlist__check"];

//Create a sensor for each VMware Datastore
var sensors = client.AddSensor(1001, parameters);
```

In the PowerShell section of this page, it explicitly states *By default, any fields that represent sensor targets will store the first sensor target compatible with that field*, however I can see this remark is actually missing from the C# section. As such, I have updated the C# section to include this detail as well.

Regards,
lordmilko
