### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by clemensmool** [lordmilko/PrtgAPI#108]
Is it possible to get a list of sensors or devices where the Maintenance Window has been set?
Is it possible to set a maintenance window with PrtgAPI?

**Comment by lordmilko** [comment]
Hi @clemensmool,

The Maintenance Window of an object can be retrieved with the [Get-ObjectProperty](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#get-1) cmdlet

```powershell
C:\> Get-Sensor ping -count 1 | Get-ObjectProperty | select *maint*

MaintenanceEnabled MaintenanceStart      MaintenanceEnd
------------------ ----------------      --------------
             False 23/10/2016 5:07:00 PM 23/10/2016 5:07:00 PM
```

When it comes to *setting* maintenance windows, this is not currently natively supported, however this can still be achieved by specifying a set of [raw parameters](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#raw-unsupported-1)

```powershell
Get-Sensor ping -count 1 | Set-ObjectProperty -rawparameters @{
    maintenable_=1
    maintstart_="2019,10,23,17,07,00"
    maintend_="2020,10,23,17,07,00"
} -force
```
Which results in the following
```powershell
C:\> Get-Sensor ping -count 1 | Get-ObjectProperty | select *maint*

MaintenanceEnabled MaintenanceStart      MaintenanceEnd
------------------ ----------------      --------------
              True 23/10/2019 5:07:00 PM 23/10/2020 5:07:00 PM
```

Regards,
lordmilko
