### ISSUE TITLE
Who is LordMilko?

### ISSUE THREAD

**Issue by ArneBrucker** [lordmilko/PrtgAPI#109]
Hi
We train a few PRTG users in Germany and are huge fans of PrtgAPI. We would like to show you the possibilities offered by the use of PrtgAPI, but would also like to pay tribute to the brilliant mind behind the project. Can you tell us something about you and the reasons for starting this project?

Thank you very much

**Comment by lordmilko** [comment]
Hi @ArneBrucker,

I like to maintain as much anonymity online as possible, so prefer not to disclose any personally identifying information about myself :P

As for how the history of the project: while procrastinating at work one day, perusing through the PRTG API, I was taken aback by two things:
1. How *unnecessary complicated it was*
2. How well the components of a PRTG API request could be *modeled using a programming language*

Within a couple of days I put together a simple library that abstracted the details of interfacing with a number of key PRTG functions. I then threw it up on the internet, where it proceeded to be...completely ignored by everyone, **including me**. It wasn't until 12 months later when I considered implementing an outer PowerShell layer that it actually become useful to *me and others* , sparking a passion that has helped transform this project into a framework unto itself!

Over time, this project has become a vehicle for exploring a vast array of software development and programming techniques; it's one thing to play around with Docker in your lab - it's another to have a real use for it in a project!

Of course, as a result of the sheer amount of time and effort I've put into this project, I'm now stuck in a vicious cycle; the best thing I've ever developed is terrible unless I implement some improvement; but now it's even *better* so now it's even ***more* important** that I implement the next improvement, etc :P

Thanks for your support!

Regards,
lordmilko

**Comment by ArneBrucker** [comment]
Hello lordmilko,

Since your work, which we value very much, has become a standard in our training courses, we would very much appreciate it if we could mention you in a nutshell. We also invite you to attend one of our advanced seminars in person, depending on your location.

We respect your desire for anonymity, but we hope that we are able to establish a personal dialogue with you. We would like to share our vision with our participants. Please write me also personally to technik@netmon24.eu.

Best regards

**Comment by lordmilko** [comment]
Thanks @ArneBrucker, however I'd rather let my product speak for itself rather than have any attention focused on me.

Regards,
lordmilko
