### ISSUE TITLE
Idea: Autodiscover with Template

### ISSUE THREAD

**Issue by varmox** [lordmilko/PrtgAPI#11]
Would be nice if you could assign a device template for autodiscover when adding a new device

e.g "add-device dc1 192.168.1.20 -autodiscover --template Windows_Server"

**Comment by lordmilko** [comment]
I've noticed that the templates supported by a device appear to be included in the [data returned](https://github.com/lordmilko/PrtgAPI/blob/master/PrtgAPI.Tests.UnitTests/ObjectTests/TestResponses/DeviceSettingsResponse.cs#L185) by running `Get-ObjectProperty` on a device. Based on this, we can potentially do several things

1. Include a property on `DeviceSettings` that lists all of the templates currently supported by that device
2. Implement a new `Get-DeviceTemplate` cmdlet that returns a strongly typed `DeviceTemplate` object that is suitable to be used with `Add-Device` (similar to how `Get-SensorTarget` works for sensors).
3. `Add-Device` could allow specifying a wildcard `string` for the template, which will cause PrtgAPI to automatically invoke the functionality provided by `Get-DeviceTemplate` for you

```powershell
$templates = $device | Get-DeviceTemplate *windows*
$group | Add-Device dc-1 192.168.0.1 -AutoDiscover -Template $templates
```
```powershell
$group | Add-Device dc-1 192.168.0.1 -AutoDiscover -Template *windows*
```

In the meantime, the `AutoDiscoveryMode` enum does currently support performing an auto-discovery using a template. As such, it is currently possible to achieve this functionality by creating a `NewDeviceParameters` object with the `New-DeviceParameters` cmdlet and then creating a set of `CustomParameter` objects that specify the required parameters

```powershell
$params = New-DeviceParameters dc-1
$params.AutoDiscoveryMode = "AutomaticTemplate"

$customParams = $params[[PrtgAPI.Parameter]::Custom]
$p1 = New-Object PrtgAPI.Parameters.CustomParameter -ArgumentList "devicetemplate_",1
$p2 = New-Object PrtgAPI.Parameters.CustomParameter -ArgumentList "devicetemplate__check","Dell+MDI.odt|Dell+MDI+Disk||"
$customParams.Add($p1)
$customParams.Add($p2)

$group | Add-Device $params
```

I have added this to the [Roadmap](https://github.com/lordmilko/PrtgAPI/projects/1) to be completed after tree manipulation / `IQueryable` support has been shipped (which won't be anytime soon).

Thanks for raising this idea!

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @varmox,

PrtgAPI 0.8.4 has now been released, containing several methods for performing auto-discoveries with device templates

A new cmdlet `Get-DeviceTemplate` has been introduced, allowing you to query PRTG for device templates that have been installed on your PRTG Core Server

```powershell
C:\> Get-DeviceTemplate *wmi*,*rdp*

Name                       Value
----                       -----
RDP Server                 Server RDP.odt
Windows (Detailed via WMI) Windows Advanced.odt
Windows (via WMI)          Windows Generic.odt
```

The `Add-Device` cmdlet now includes a new `-Template` parameter. When specified in conjunction with `-AutoDiscover`, it is possible to specify one or more device template wildcard expressions indicating the templates you would like to include in your request. `Add-Device` will then internally retrieve the required `DeviceTemplate` objects for you and include them in the internal request parameters

```powershell
Get-Probe | Add-Device dc-1 -AutoDiscover -Template *wmi*,*rdp*
```

When creating device parameters manually, `NewDeviceParameters` objects returned by the `New-DeviceParameters` now include a `DeviceTemplates` property which allows you to assign one or more `DeviceTemplate` objects returned by the `Get-DeviceTemplate` cmdlet. Assigning a template to the `DeviceTemplates` property will automatically set the `AutoDiscoveryMode` to `AutomaticTemplate`

In addition, it is now possible to specify device templates to the `Start-AutoDiscovery` cmdlet. Either `DeviceTemplate` objects or template name wildcards can be specified

For more information on these features please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation)

To update PrtgAPI, run `Update-Module PrtgAPI` and re-open your PowerShell prompt

Please refer to the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.8.4) to be aware of any breaking changes

Thanks for suggesting this idea!

Regards,
lordmilko
