### ISSUE TITLE
filtering by property on Get-System System

### ISSUE THREAD

**Issue by yudaprasetia** [lordmilko/PrtgAPI#110]
Hello lordmiko,

I'm very interesting api prtg, and love your scripts.
I wanna ask, if possible to filtering data with Get-SystemInfo? I want to filter data (all device) with spesific value/name like serial number?

Thanks 

```
Name                           DeviceId   Property             Id     Value
----                           --------   --------             --     -----
Serial Number (Linux 3.3.5 ... 2125       Serial Number (Li... 1      tilegx-ehci.0
```

**Comment by lordmilko** [comment]
Hi @yudaprasetia,

You can do this using the `Where-Object` cmdlet

```powershell
Get-Device | Get-SystemInfo System | where { $_.Property -like *system* -and $_.Value -eq "tilegx-ehci.0" }
```

Regards,
lordmilko
