### ISSUE TITLE
Loading latest build .ZIP results in error

### ISSUE THREAD

**Issue by SwissJay** [lordmilko/PrtgAPI#115]
Attempting to download the latest build .ZIP from the given URL (https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.PowerShell/bin/Release/PrtgAPI.zip) yields the following error:

<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:21676b6f-901e-004d-3e49-9609c9000000
Time:2019-11-08T15:31:45.8031115Z</Message></Error>

**Comment by lordmilko** [comment]
Thanks @SwissJay!

This has now been resolved

Regards,
lordmilko
