### ISSUE TITLE
Status of Sensor in historical Data

### ISSUE THREAD

**Issue by cyberoner1** [lordmilko/PrtgAPI#116]
Hi,

is there a chance to get the status of the sensor in historical data, too? In the log files you only see when a sensor status change. But this is quite complicated to combine this with the historical data. If the stauts of the senor would be part of historical data it helps to analyse

**Comment by lordmilko** [comment]
Hi @cyberoner1,

You can track whether the sensor was up or down by analyzing the `Downtime` column. PRTG requires you format your request in a special way to include downtime information, so PrtgAPI enables you to view by this by executing the `Get-SensorHistory` cmdlet with the `-Downtime` parameter.

Aside from this, the purpose of the `Get-SensorHistory` cmdlet is to view fluctuations in channel values. If you wish to inspect changes in sensor states you should utilize the `Get-ObjectLog` cmdlet.

Regards,
lordmilko
