### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by clemensmool** [lordmilko/PrtgAPI#117]
Is it also possible to set the comments on a specific sensor with prtgapi?

**Comment by lordmilko** [comment]
Yes, you can do this using the `Set-ObjectProperty cmdlet`

```powershell
Get-Sensor -Count 1 | Set-ObjectProperty Comments "new comment!"
```

For more information on modifying object properties please see [the wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation)
