### ISSUE TITLE
Missing states in TriggerParameters

### ISSUE THREAD

**Issue by Z3nto** [lordmilko/PrtgAPI#120]
Hi @lordmilko,

I'm not sure if want this as a bug report or as a feature request.
The new state types for Notificationtriggers are missing in your API.

```
Exception` setting "State": "Cannot convert value "Up" to type "PrtgAPI.TriggerSensorState". Error: "Unable to match the identifier name Up to a valid enumerator name. Specify one of the following enumerator names and try again:
Down, Warning, Unusual, DownPartial""
````

Since a few versions there are additional states "Up" and "Unknown". Could you please add this two in the set of allowed states?

![grafik](https://user-images.githubusercontent.com/22791287/69547424-dcf7ea00-0f95-11ea-8350-c92b5b8fffa7.png)

I would create a Pull request, but I'm not sure if I would find all dependent files :)
Thank you very much!

Best Regards
Z3nto

**Comment by lordmilko** [comment]
Hi @Z3nto,

This was [added](https://github.com/lordmilko/PrtgAPI/blob/master/src/PrtgAPI/Enums/Serialization/TriggerSensorState.cs) in PrtgAPI 0.9.9, although I see I didn't include it in the release notes

Regards,
lordmilko
