### ISSUE TITLE
Connect-PrtgServer : The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by martijngoorman** [lordmilko/PrtgAPI#128]
Hi,

Since the last PRTG Update (20.1.55.1775) we're getting the following error when running a connect-prtgserver command:

Connect-PrtgServer : The request was aborted: Could not create SSL/TLS secure channel.

Server is reachable by browser.
Also connecting internally on IP it does'nt work and gives same error.
Tested on 2 instances with same PRTG version, also same error on both.

Please advise/update.

**Comment by lordmilko** [comment]
PrtgAPI 20.1.55 enforces TLS 1.2 by default, which certain PowerShell/.NET Framework versions do not include by default.

To resolve this for now, please specify

```powershelll
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

before calling `Connect-PrtgServer`

I will look into automatically including TLS 1.2 in the list of valid security protocols for the current process if it is not already included

**Comment by martijngoorman** [comment]
That does the trick :)
Thanks!

**Comment by forever765** [comment]
@lordmilko Thank you for your proposal, now PrtgAPI work normal!

**Comment by lordmilko** [comment]
Please be advised that PrtgAPI 0.9.12 has now been released, which includes a proper fix for this issue

To update PrtgAPI, simply run

```powershell
Update-Module PrtgAPI
```

and reopen PowerShell

Regards,
lordmilko

**Comment by klyukanov** [comment]
> PrtgAPI 20.1.55 enforces TLS 1.2 by default, which certain PowerShell/.NET Framework versions do not include by default.
> 
> To resolve this for now, please specify
> 
> ```
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
> ```
> 
> before calling `Connect-PrtgServer`
> 
> I will look into automatically including TLS 1.2 in the list of valid security protocols for the current process if it is not already included

Hi lordmilko
not sure why, but this command didnt help me. still getting same error..
please advise

**Comment by lordmilko** [comment]
Hi @klyukanov,

Are you able to advise what version of PrtgAPI you are using? You can get this information by executing the following commands

```powershell
ipmo prtgapi
gmo prtgapi
```

Also if your PRTG server has an invalid SSL certificate you will need to specify `-IgnoreSSL` to `Connect-PrtgServer`

PrtgAPI now automatically enables TLS 1.2 for you, however note that going forward you may need to instruct the .NET Framework to use newer versions of TLS for you. For example, if for whatever reason your PRTG server has actually been locked down to allow TLS 1.3 only, you would need to do

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls13
```

Regards,
lordmilko

**Comment by klyukanov** [comment]
Works! -IgnoreSSL helped! thanks!
