### ISSUE TITLE
Need help to create a custom exexml sensor

### ISSUE THREAD

**Issue by terrassen** [lordmilko/PrtgAPI#129]
Hello Lord Milko

I wish to create an exexml sensor using powershell. The name(s) of the sensor(s) should be derived from the filename(s) in a specific folder.
Is there a way that PrtgAPI queries the folder content and brings me back a list of file names, which then can be used for the 'name_' property ? Something like

$params = Get-Device -id ID | new-sensorparameters -someoptions "C:\folder"

The goal is that $params holds the list of filenames of C:\folders
Is this possible?

Thanks  and regards
Guido Weber

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [x] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by terrassen** [comment]
Forgot the mention that "C:\folders" is a folder of the device, not a local folder.

**Comment by lordmilko** [comment]
I don't exactly understand what you're asking. Can you provide an example of what the name, script and script parameters would be if you created this sensor manually, and where the information regarding the name/parameters comes from

**Comment by terrassen** [comment]
Let's asume the device is a SQL server. The content of it's C:\folder is a list of xml Files:

SQL_Availability_Group_Status.xml
SQL_ENDUR_BackupFileAge.xml
SQL_ENDUR_FileStats.xml
SQL_ENDUR_GeneralStats.xml
SQL_MSSQLSERVER_BackupFileAge.xml
SQL_MSSQLSERVER_FileStats.xml
SQL_MSSQLSERVER_GeneralStats.xml

The goal is to create for each file name a exexml sensor. The sensor names should match the file names. I know how to create
such a sensor if I can provide the name, thats not a problem.

My problem is to get the file names (= sensor names). The number of files and their names is dynamic, it can be different from device to device.
Due to security restrictions I am unable to use powershell to remote login to the device and get the folder listing.
I was hoping that prtgapi has a mechanism to query the content of a folder and bring me back the file names.

Something similar to the snmpnetappdiskfree sensor, where it brings me back a complete listing of the file system names, which will be used to
create the sensors:
( $DiskFreeUnits = Get-Device -Id $DeviceId | New-SensorParameters -RawType snmpnetappdiskfree )


Thanks and regards
Guido




[cid:itp_oria_4bd656f6-d1dd-4962-93a0-bdf17e4690bc.jpg]
Guido Weber
Senior Systems Engineer

ITpoint Systems AG | Riedstrasse 1 | CH-6343 Rotkreuz
D: +41 41 798 80 34 | M: +41 79 208 64 53
guido.weber@itpoint.ch

www.itpoint.ch<http://www.itpoint.ch> | www.oria.ch<http://www.oria.ch> | LinkedIn<https://www.linkedin.com/company/itpoint-systems-ag/> | Xing<https://www.xing.com/companies/itpointsystemsag> | Twitter<https://twitter.com/ITpointAG> | Facebook<https://www.facebook.com/ITpointSystemsAG>

Trusted IT for Business


Von: lordmilko <notifications@github.com>
Gesendet: Mittwoch, 12. Februar 2020 10:43
An: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Guido Weber <guido.weber@itpoint.ch>; Author <author@noreply.github.com>
Betreff: Re: [lordmilko/PrtgAPI] Need help to create a custom exexml sensor (#129)


I don't exactly understand what you're asking. Can you provide an example of what the name, script and script parameters would be if you created this sensor manually, and where the information regarding the name/parameters comes from

**Comment by lordmilko** [comment]
PrtgAPI is simply a library that encapsulates the functionality of the PRTG API, neither of which provide "functions" that allow you to access arbitrary folders on your devices in PRTG

If you can access the C: drive via SMB, you can get the information you need; you don't need to "remote login" with SMB per se - any Domain Admin account/account with local admin rights on the target server will have the appropriate permissions

```powershell
$devices = Get-Device sql*

foreach($device in $devices)
{
    $files = gci "\\$($device.Host)\c$\folder"

    foreach($file in $files)
    {
        # Now create some sensor parameters and add them to the devices
    }
}
```

Even if PRTG were able to do this for you, it would need to have some level of access to remotely probe the target device. I'm not sure if you simply don't have full admin rights in your environment, but if you do you should be able to achieve this goal
