### ISSUE TITLE
Copy NotificationTrigger with New-NotificationTriggerParamters

### ISSUE THREAD

**Issue by astapelfeld** [lordmilko/PrtgAPI#132]
Copying a Notification Trigger with New-NotificationTriggerParamters doesn't seem to work as expected.

```
PS /home/astapelfeld> Get-NotificationTrigger -ObjectId 10004 -SubId 1 -Inherited $false

Type      ObjectId SubId Inherited ParentId Latency Condition Threshold Unit       OnNotificationAction
----      -------- ----- --------- -------- ------- --------- --------- ----       --------------------
State     10004    1     False     10004    300     Equals    Down                 Something

PS /home/astapelfeld> New-NotificationTriggerParameters -Source $(Get-NotificationTrigger -ObjectId 10004 -SubId 1 -Inherited $false)

OffNotificationAction        :
EscalationNotificationAction :
Latency                      :
EscalationLatency            :
RepeatInterval               :
State                        :
ObjectId                     : 10004
SubId                        : 1
Action                       : Edit
Type                         : State
OnNotificationAction         :
Cookie                       : False
```
Shouldn't New-NotificationTriggerParameters -Source copy the parameters from the source object?. It is not copying Latency or OnNotificationAction.

My goal is to create Notification Triggers from existing ones only changing the Notification Action (OnNotificationAction)

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [ X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [ X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @astapelfeld,

To create a set of `TriggerParameters` for cloning a trigger you need to specify both the source trigger *and* the ID of the object the trigger will be created on. If you simply specify a `NotificationTrigger` itself, PrtgAPI will create a set of `TriggerParameters` for *editing* that existing trigger.

You can find more information on working with Notification Triggers on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Notification-Triggers#modify-1)

> TriggerParameters can also be created from existing NotificationTrigger objects, for scenarios in which you either wish to directly clone an existing trigger to another object, or scenarios in which you wish to use an existing trigger as a "template" for a new trigger you are trying to create.
> ```powershell
> # Clone all state triggers from the sensor with ID 1001 to the object with ID 1234
> Get-Sensor -Id 1001 | Get-Trigger -Type State -Inherited $false | New-TriggerParameters 1234 | Add-Trigger
> ```

Regards,
lordmilko
