### ISSUE TITLE
Sensor will be created in PRTG but with error in PowerShell Module

### ISSUE THREAD

**Issue by schoenm1** [lordmilko/PrtgAPI#134]
I tried to create with snmp library a new Sensor to get from a Cisco Switch the Firmware Version.
The sensor is created perfectly by your module, but I get the message:

![image](https://user-images.githubusercontent.com/1053744/75885129-3fc71000-5e26-11ea-8e13-630c93b4e05a.png)

![image](https://user-images.githubusercontent.com/1053744/75885398-b9f79480-5e26-11ea-8ae5-10fb775dfc7f.png)

How can I handle this? Is there an option to wait longer for a PRTG API Response?
My code:
`$deviceID = 2081`
`$param = Get-Device -id $deviceID | New-SensorParameters -RawType snmplibrary -qt *cisco-stack.oid* -Target *`
`$newvalue =  $param.interfacenumber__check | Where-Object Properties -like "*module fw*"`
`$param.interfacenumber__check = $newvalue`
`$param.Tags = "snmplibrarysensor FW-Version"`
`$sensor = Get-Device -Id $deviceID | Add-Sensor $param`

- [x] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [ ] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @schoenm1,

If you have a large PRTG installation and it takes PRTG a long time to create new sensors, you can instruct PrtgAPI to [wait longer between each retry](https://github.com/lordmilko/PrtgAPI/wiki/Getting-Started#session-management-1). The following will make `Add-Sensor` wait an *insanely* long time before giving up

```powershell
Set-PrtgClient -RetryCount 10 -RetryDelay 10
```

Please let me know if this resolves your issue

Regards,
lordmilko

**Comment by schoenm1** [comment]
Hi lodmilko,
unfortunately this did not solve my problem.
With `Get-PrtgClient` I see: `RetryCount : 10` / `RetryDelay = 10`
What excaclty is PRTGApi Module waiting for PRTG? Is there an option for a Debug Log (more then `Set-PrtgClient -LogLevel All` ?
Regards Micha

**Comment by lordmilko** [comment]
Before attempting to add the sensor, try this

```powershell
$param.DynamicType = $true
```

From the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#advanced-creation):

> When resolving added sensors, for accuracy and performance purposes PrtgAPI limits its search to sensors that have the same Type specified in the NewSensorParameters object. If you are creating a sensor with a dynamic sensor type that changes based on exact parameters that are specified (**such as snmplibrary**) you should set the DynamicType property of the parameters object to true. This can be done at the time of parameter creation via the -DynamicType parameter
