### ISSUE TITLE
using HashTable for "New-SensorParameters"

### ISSUE THREAD

**Issue by schoenm1** [lordmilko/PrtgAPI#137]
I have multiple Sensor, which are created based on parameters set in an XML.
```$RawTypeParam = @{}
$param = Get-Device -id $deviceID | New-SensorParameters @RawTypeParam
}
```
For many sensor, this is working well. My `$RawTypeParam` contains one or more entries.

Example working: 
```$RawTypeParam
Name                       Value
----                           -----
RawType                  snmpciscosystemhealth
Target                      *
}
```
In this Case, the Powershell will execute this line:
`$param = Get-Device -id $deviceID | New-SensorParameters -RawType snmpciscosystemhealth -Target *`

Example not working:
```$RawTypeParam
Name                           Value
----                           -----
qt                             @{tableoid_=""1.3.6.1.4.1.1916.1.1.1.9""}
RawType                  snmpcustomtable
```

This will end in an error:
```
New-SensorParameters : Cannot specify query target @{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"} on sensor type "snmpcustomtable": type does not support query targets.
At C:\Visual_Studio\prtg\General.ps1:51 char:37
+ ... param = Get-Device -id $deviceID | New-SensorParameters @RawTypeParam
+ CategoryInfo          : NotSpecified: (:) [New-SensorParameters], InvalidOperationException
```

I suggest that the problem is either the "@" or the "{}". Can you help me how I can set the parameter Value "@{tableoid_=""1.3.6.1.4.1.1916.1.1.1.9""}" for the Parameter "qt"?
At the end, it should be:
```$param = Get-Device -id $deviceID | New-SensorParameters -RawType snmpcustomtable -qp @{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}```
If I enter this manually, this is working well, but not when using the `$RawTypeParam = @{}`

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [ ] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @schoenm1,

Can you please copy and paste the exact output you get when you run the command

```powershell
Get-Device -id $deviceID | New-SensorParameters -RawType snmpciscosystemhealth -Target *
```

Where `$deviceID` has the ID of some device

**Comment by schoenm1** [comment]
```
PS C:\Users\mischoe> $deviceID = 4014
PS C:\Users\mischoe> Get-Device -id $deviceID | New-SensorParameters -RawType snmpciscosystemhealth -Target *

measurement        : 1
measurement__check : {CPU, Memory, Fans, Power Supplies...}
Targets            : {[measurement__check, PrtgAPI.Targets.GenericSensorTarget[]]}
Source             : switch lab
SensorType         : snmpciscosystemhealth
Priority           : Three
InheritTriggers    : True
InheritInterval    : True
Interval           : 00:01:00
IntervalErrorMode  : OneWarningThenDown
DynamicType        : False
Name               : Base Sensor
Tags               : {snmpciscosystemhealthsensor, systemhealth}
Cookie             : False
```
FYI: this is working well, wenn "-RawType snmpciscosystemhealth -Target *" was set in $RawTypeParam and using:
`$param = Get-Device -id $deviceID | New-SensorParameters @RawTypeParam`

**Comment by schoenm1** [comment]
This is working:
```
$deviceID = 5467
$param = Get-Device -id $deviceID | New-SensorParameters -RawType snmpcustomtable -qp @{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}
```
This is not working:
```
$hashtable = @{}
$hashtable.add("RawType","snmpcustomtable")
$hashtable.add("qp","@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}")
$param = Get-Device -id $deviceID | New-SensorParameters @hashtable
```
But if I take the example from above with 2 Paramters: `-RawType snmpciscosystemhealth -Target *`, the command with `@hashtable` is working well.
```
$hashtable = @{}
$hashtable.add("RawType","snmpciscosystemhealth ")
$hashtable.add("Target ","*")
$param = Get-Device -id $deviceID | New-SensorParameters @hashtable
```

**Comment by lordmilko** [comment]
So to confirm, the issue is it's not working when you try to use [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7)?

In the code you've provided, this line is wrong

```powershell
$hashtable.add("qp","@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}")
```
This line creates a new record "qp" whose value is the **string** "@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}". However this is incorrect. What you actually want is for the `qp` parameter to have the `Hashtable` value `@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}` - note the lack of surrounding quotes

Are you able to advise whether it works if you try to do this?

```powershell
$hashtable = @{}
$hashtable.add("RawType","snmpcustomtable")
$hashtable.add("qp",@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"})
$param = Get-Device -id $deviceID | New-SensorParameters @hashtable
```

**Comment by schoenm1** [comment]
I see the problem:
what I do: $hashtable.add("qp",@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}), where "@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9" is a string in my case and not a Hashtable.
My question now is: how can I convert the string "@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9" to a hashtable. (I have no other option to read the string directly and add it to the hash.

**Comment by lordmilko** [comment]
Why do you have to read the entire value "@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9" as a string? Do you have some sort of config file you're reading properties from to create a whole bunch of different sensor types? Why can't you simply read the value of the tableoid_ property as a string and then assign it from a variable, i.e.

```powershell
@{tableoid_=$value}
```

What exactly is it you're trying to achieve here?

**Comment by schoenm1** [comment]
I read all the parameters from an XML. So I don't know if this should be a normal string or a Hashtable.
```
<RawType>
  <item>
    <Name>RawType</Name>
    <Value>snmpcustomtable</Value>
  </item>
  <item>
    <Name>qt</Name>
    <Value>@{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}</Value>
  </item>
</RawType>
```
I loop over all the ìtems` and create a hashTable `@RawTypeParam`

This HashTable I use for the line:
```$param = Get-Device -id $deviceID | New-SensorParameters @RawTypeParam```

Until now, I never had a <Value></Value> which is formatted as a HashTable.
As mentioned above, manually it works:
`$param = Get-Device -id $deviceID | New-SensorParameters -RawType snmpcustomtable -qp @{tableoid_="1.3.6.1.4.1.1916.1.1.1.9"}`

My problem is: How can I read the XML and format the Value as a HashTable, so that it would work as in the manually created line?

**Comment by lordmilko** [comment]
You can convert a string into a Hashtable by using the `Invoke-Expression` cmdlet, however this is arguably a security risk, as if someone modifies your XML file your script will execute any arbitrary code an attacker likes.

Do you have the ability to modify the format of the XML?

If so, you could store the value as `tableoid_="1.3.6.1.4.1.1916.1.1.1.9"` 

```powershell
if($parameterName -eq "qt")
{
    $properties = $value -split ";"

    $qt = @{}

    foreach($prop in $properties)
    {
        $keyValue = $prop -split "="
        $qt.$keyValue[0] = $keyValue[1]
    }

    $hashtable.qt = $properties
}
```

**Comment by schoenm1** [comment]
I finally found a solution.
I changed the XML. If the String beginns with "@@", my script will split this entry to a hash and add it as you shown above. Thank you very much!
My XML entry is now: `@@tableoid_=1.3.6.1.4.1.1916.1.1.1.9`. So I can define in the XML, if it is a 'normal' String or a Hash.

**Comment by schoenm1** [comment]
thanks a lot for your help and the solution :-)
