### ISSUE TITLE
[Feature Request] Specific Error Message for GetDynamicSensorParameters

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#140]
https://github.com/lordmilko/PrtgAPI/blob/b68087d0c87de63de9d03041c46a6d7a383544c5/src/PrtgAPI/Request/ResponseParser.cs#L551-L577

Add logic to parse out the div class "errormessage" and report it in the error so I can take action. In this example, I'll know the username/password for the sensor for VMware isn't correct and report that back appropriately or attempt a different credential.
```
<div id="main" data-title="Add Sensor Failed" data-contexthelpshow="false">
  <div id="failed" style="display:none">
    <p>Could not create the <a href='/help/vmware_host_hardware_status_soap_sensor.htm' target='_blank'><b>VMware Host Hardware Status (SOAP)</b></a> sensor on device <b><a  dependency="12187" deptype="select"  thisid="12002" class="devicemenu isnotpaused  isnotfavorite remoteprobe" style="background-image:url(/icons/devices/A_Server_1.png?svg)" id="12002" href="device.htm?id=12002">DIAUAIAESX02.field.ad.dncinc.com </a> (10.64.100.17)</b>.</p>
    <p><b style="color:red"><div class="errormessage">Cannot complete login due to an incorrect user name or password.</div></b></p>
```

**Comment by lordmilko** [comment]
Hi @JustinGrote,

I have released a pre-release build of PrtgAPI 0.9.13 that includes this enhancement. Can you please follow the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) and advise whether this works as expected?

For future enhancements please use the fancy *Feature request/Idea* template when creating an issue.

Unrelated, you may be interested to know that a previous commit for PrtgAPI 0.9.13 introduced a new `-rt` alias for `-RawType` on `Get-SensorTarget` / `New-SensorParameters`. I'm sure you will most agree this is a revolutionary feature :P

Regards,
lordmilko

**Comment by JustinGrote** [comment]
@lordmilko thanks for the fast turnaround! Apologies on the Feature Request, I did a "new issue from line" in the code and it didn't present me with a template, maybe a Github limitation or something else that needs to be resolved.

I will be able to test later today when I get back to this item. Thanks.

**Comment by JustinGrote** [comment]
@lordmilko works as expected! This is very helpful as I can now test if VMware credentials are correct without needing them saved outside of PRTG, since Paessler in their infinite wisdom didn't make them available to custom scripts while still letting windows and linux creds.

Here's some examples of messages I can now trap:

```powershell
🏠(get-prtgclient).GetDynamicSensorParameters(11975,'esxserverhealthsensorextern')
MethodInvocationException: Exception calling "GetDynamicSensorParameters" with "2" argument(s): "An exception occurred while trying to resolve sensor targets: Please enter
 the VMware user and password in the device."
🏠(get-prtgclient).GetDynamicSensorParameters(12003,'esxserverhealthsensorextern')
MethodInvocationException: Exception calling "GetDynamicSensorParameters" with "2" argument(s): "An exception occurred while trying to resolve sensor targets: Cannot compl
ete login due to an incorrect user name or password."
🏠(get-prtgclient).GetDynamicSensorParameters(11975,'esxserverhealthsensorextern')
MethodInvocationException: Exception calling "GetDynamicSensorParameters" with "2" argument(s): "An exception occurred while trying to resolve sensor targets: Unable to co
nnect to the remote server."
```
