### ISSUE TITLE
Sensors 24 hours data snapshot

### ISSUE THREAD

**Issue by JeanPierreDP** [lordmilko/PrtgAPI#141]
**What's going on?**

Hi,

So I work for a company that has a reporting requirement, but I myself do not have any working knowledge of PRTG, so was given a link that return a dataset. If you could just point me in the right direction. I am not employed as a developer, just very keen on trying to help. 
http://prtg.mycoolsite.com/api/table.xml?content=sensors&output=csvtable&columns=group,device,sensor,status,message,lastvalue,interval&count=10000&id=30882&sdate=2020-03-23-00-00-00&edate=2020-03-24-00-00-00&username=USERNAME&passhash=HASHVALUE

So I believe I should be able to get same result following the instruction found here:
https://github.com/lordmilko/PrtgAPI/wiki/Sensors

That i should query for this value "id=30882" and just define the column values as listed in the URL? 

Got some of the other commands working, so I know I am connecting and able to get data back from the system, for the above I am trying:

            var sensor = _.GetSensors(Property.Id, 30882);

            foreach (var item in sensor)
            {
                    Console.WriteLine($"Found sensor {sensor}!"); //returns nothing
            }

If i use, i can see that I am obviously doing something wrong, I just do not understand what ID that would be then,
            var sensor = _.GetSensors(Property.Id, 30882).Count;
            Console.WriteLine($"Found sensor {sensor}!");

Found sensor 0!

Should be looking at the option available under:
https://github.com/lordmilko/PrtgAPI/wiki/Historical-Information

When i open the link in the browser I get an xml formatted as an csv, but I do not actually know what I am looking at, 

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [ ] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @JeanPierreDP,

> http://prtg.mycoolsite.com/api/table.xml?content=sensors&output=csvtable&columns=group,device,sensor,status,message,lastvalue,interval&count=10000&id=30882&sdate=2020-03-23-00-00-00&edate=2020-03-24-00-00-00&username=USERNAME&passhash=HASHVALUE

This URL is completely illegal, and appears to conflate the parameters that should be specified when asking for sensors vs asking for sensor history. In PRTG and PrtgAPI, `Sensor` objects represent things that periodically execute some kind of monitoring action. To retrieve *historical* information about a sensor, as you've surmised you need to look at the [GetSensorHistory](https://github.com/lordmilko/PrtgAPI/wiki/Historical-Information#sensor-history) method.

If `30882` is indeed a sensor, your usage of the `GetSensor` method appears to be correct. Given you have access to execute API requests, I assume you also have access to log into the PRTG UI. You should be able to do a search up the top right hand corner for `30882` and then open the object it finds. You can then look in the address bar to see if it was a sensor, device or group, etc. You can also use the `GetObject` method and then inspect the `Type` of the returned object to find out what type of object it really is

To give you an example of what a valid API request looks like, the following request retrieves all sensors whose name equals "ping"


> http://prtg.example.com/api/table.xml?content=sensors&columns=objid,name,probe,group,favorite,lastvalue,device,downtime,downtimetime,downtimesince,uptime,uptimetime,uptimesince,knowntime,cumsince,lastcheck,lastup,lastdown,minigraph,schedule,basetype,baselink,notifiesx,intervalx,access,dependency,position,status,comments,priority,message,parenid,tags,type,active&count=*&filter_name=ping&username=prtgadmin&passhash=12345678

And then the following API request retrieves historical information for the last 24 hours for one of these ping sensors (with ID 2056)

> http://prtg.example.com/api/historicdata.xml?id=2056&edate=2020-03-26-00-32-23&sdate=2020-03-25-23-32-23&avg=0&sortby=-datetime&username=prtgadmin&passhash=12345678

Please let me know if you have any further questions

Regards,
lordmilko

**Comment by JeanPierreDP** [comment]
Thank you very much for your response, really appreciate your assistance. Will request the password to login and investigate. Will let you know if I have any other related questions.

**Comment by JeanPierreDP** [comment]
Hi,

Okay so I managed to identify the ID, it looks like they have built some report and the URL passes the filters required and the system then generated the report and present the XML with CSV formatting,

http://prtg.mycoolsite.com/report.htm?id=30882&tabid=1

Is possible to use the API to process the above? or would I need to custom build a solution using HTTPClient?

**Comment by lordmilko** [comment]
Hi @JeanPierreDP,

PrtgAPI does not currently support interfacing with report objects, so I suspect you will need to build a custom solution

Regards,
lordmilko

**Comment by JeanPierreDP** [comment]
Thank you
