### ISSUE TITLE
How to get sensor parameters?

### ISSUE THREAD

**Issue by ivoruetsche** [lordmilko/PrtgAPI#147]
Hi

When I create a new sensor, I use the New-SensorParameters command in PS, like  `$oPar = $oDev|New-SensorParameters -RawType restcustom` to assign them to the `Add-Sensor` command, for example the `restcustom` sensor:

```
requesttype       : 0
protocol          : 0
tlsignore         : 0
authmethod        : 0
restuser          :
restpassword      :
resttoken         :
usecustomheaders  : no
timeout           : 60
query             :
jsonfilelabel     :
httpproxy         : 1
proxy             :
proxyport         : 8080
proxyuser         :
proxypassword     :
jsonfile          : channelDiscovery
requestbody       :
customheaders     :
Targets           : {[jsonfile, PrtgAPI.Targets.GenericSensorTarget[]]}
Source            : Device ABC
SensorType        : restcustom
Priority          : Three
InheritTriggers   : True
InheritInterval   : True
Interval          : 00:01:00
IntervalErrorMode : OneWarningThenDown
DynamicType       : False
Name              : Master V1
Tags              : {restcustomsensor, restsensor}
Cookie            : False
```
But how can I get these parameters back from an existing sensor?

Something like a "Get-SensorParameters"?

gruss ivo

**Comment by lordmilko** [comment]
Hi @ivoruetsche,

To get the existing properties of a sensor (i.e. the values you'd see in the Settings page in PRTG) you can use the `Get-ObjectProperty` cmdlet. To see all properties of a sensor (including those not natively supported by PrtgAPI, which you'll probably want for properties highly specific to different sensor types) you will additionally need to specify the `-Raw` parameter

For more information please see the following articles on the wiki
* [Get-ObjectProperty](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#get-1)
* [Get-ObjectProperty -Raw](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#raw-unsupported-1)

Regards,
lordmilko

**Comment by ivoruetsche** [comment]
Super, Perfect

Thanks a lot!
