### ISSUE TITLE
PassThru option to Connect-PRTGServer

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#15]
Hey love your module, using it every day these days :).

Could you add a -passthru parameter that returns the prtgclient object, so it can be interacted with directly? I have some additional cmdlets I want to write, but I'm not really a C# guy, and I'd rather use your engine than the Invoke-Restmethod-based one I have since you've already gone to a lot of trouble to optimize and stabilize it :)

Thanks!

**Comment by lordmilko** [comment]
Hi Justin,

Good idea! In the meantime however, are you aware that you can use the `Get-PrtgClient` cmdlet to retrieve the `PrtgClient`? This should allow you to achieve the functionality you are after

Regards,
lordmilko

**Comment by JustinGrote** [comment]
Oops I totally missed that one, I think I just skimmed over it. Thanks!

**Comment by lordmilko** [comment]
What sort of custom cmdlets are you trying to write? Generally speaking you should be able to achieve any functionality in C# via the PowerShell API. The C# API does not support generating arbitrary requests against web pages unknown to PrtgAPI if that's what you're potentially trying to do, although this is technically possible with a bit of type reflection

**Comment by lordmilko** [comment]
This feature has now been implemented, and will be included whenever PrtgAPI 0.8.7 is released (no current ETA)

Please let me know if you have any queries regarding your custom cmdlets

Regards,
lordmilko
