### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#151]
Good afternoon,
this is mostly a query to a function of the PRTG API in powershell, if you own it and if possible:
From a csv file where there is a table with the IP and device names, can it be imported into the powershell, and use that information to create devices?

Is there a method of adding devices in a more automated way?

**Comment by lordmilko** [comment]
Hi @mafer0410,

Please see [this article](https://blog.paessler.com/how-to-add-hundreds-of-devices-to-prtg) I wrote for the PRTG blog; this includes a sample script that accomplishes exactly this and should hopefully be enough to get you started.

Regards,
lordmilko
