### ISSUE TITLE
PRTG Python

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#152]
Hello greetings,
It is only a small query, can you create a Python script to do the same functions that are performed with the powershell in the PRTG?

**Comment by lordmilko** [comment]
Hi @mafer0410,

I'm not sure how to respond to this one, but

* I have been developing PrtgAPI for the last five years
* I don't know Python
* PowerShell works on Windows, MacOS and Linux
* PowerShell is infinitely superior to Python
* I have absolutely zero use for Python

> It is only a small query

lol

Regards,
lordmilko

**Comment by mafer0410** [comment]
Thanks
