### ISSUE TITLE
HTTP Advanced

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#153]
Hello good afternoon,
How could I create a sensor type HTTP Advanced, using parameters.

For example, to add an HTTP sensor it has the following way and works correctly:

   # Enter values for parameters
      $ sensor = read-host "` r`nEnter sensor name "
      $ type = read-host "` r`nEnter sensor type "
      $ interval = read-host "` r`nEnter sensor interval "
   
      $ param = Get-Device -Id $ ID | New-SensorParameters -RawType $ type
        $ param.Name = $ sensor
        $ param.Interval = $ interval

        $ sensor = Get-Device -Id $ ID | Add-Sensor $ param

But if I change the value for the type variable to: HTTP Advanced, it shows an error.
![image](https://user-images.githubusercontent.com/51204835/82252332-10478000-990c-11ea-9366-e3c53d593283.png)

**Comment by lordmilko** [comment]
Hi @mafer0410,

As per the wiki

> To create a set of DynamicSensorParameters, you must specify a device to create the parameters from and the **raw type name** of the sensor parameters you wish to create
> 
> To identify the raw identifier of a sensor type, the Get-SensorType cmdlet can be used
> 
> C:\> Get-SensorType *vmware*

If you do `Get-SensorType *http*` you can see that the type identifier for HTTP Advanced sensors is `httpadvanced`, not `HTTP Advanced`. As such, you should validate the specified sensor type exists first by calling `Get-SensorType` and translating it into its raw identifier if only one result exists

```powershell
$type = Read-Host "Please enter a type"

$types = (Get-SensorType $type)

if($types.Count -ne 1)
{
    throw "$($types.Count) types matched the specified value '$type'"
}
else
{
    $type = $types.Id
}
```

However note that many sensor types require additional parameters be specified beyond a type name and interval, so your script will only work for the basic sensor types only

Regards,
lordmilko

**Comment by mafer0410** [comment]
thanks
