### ISSUE TITLE
Issue with editing notification Schedule

### ISSUE THREAD

**Issue by H377Y** [lordmilko/PrtgAPI#155]
Hi,

First of all: amazing apitool.

I am trying to write a piece of code that allows us to change the notification hours when we are in holiday periods.

When i try the following:

`$all_actions = 0
$Wachtdienst = "Alerting Hours 7am ~11pm"

$all_actions = Get-NotificationAction 

for($i = 0; $i -le $all_actions.Length;$i++){

    Write-Host $all_actions[$i].Name

    if($all_actions[$i].Name -eq "SMS : Wachtdienst notification"){

        (Get-PrtgClient).SetObjectProperty($all_actions[$i].Id, [PrtgAPI.ObjectProperty]::Schedule, $Wachtdienst )
    }
    
}

for($i = 0; $i -le $all_actions.Length;$i++){

    if($all_actions[$i].Name -eq "SMS : Wachtdienst notification"){
        Write-Host $all_actions[$i].Schedule
    }
    
}`

I get the following error:
Cannot find an overload for "SetObjectProperty" and the argument count: "3".

So i want to edit the Schedule of the NotificationAction of (SMS: wachtdienst notification)
Where Wachtdienst is allready another Schedule aswell.

I presume Schedule is a "Schedule object" but i can not seem to get it work with that aswell . When passing the ID

**Comment by lordmilko** [comment]
Hi @H377Y,

If you are using PowerShell I recommend using the PowerShell style APIs, as these are much easier to use than trying to use the C# ones from within PowerShell

It sounds like you simply want to modify the schedule of a number of objects; modifying schedules is not currently natively supported by PrtgAPI, however can still be achieved by using the [raw Set-ObjectProperty API](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#raw-unsupported-1)

The following demonstrates how you would modify the schedule on a single object: the probe with ID 17834. You should be able to modify this to your scenario and pipe all the desired objects in instead

```powershell
Get-Probe -Id 17834 | Set-ObjectProperty -RawParameters @{
    "scheduledependency" = 0
    "schedule_" = Get-PrtgSchedule "Alerting Hours 7am ~11pm"
} -Force
```

Regards,
lordmilko

**Comment by H377Y** [comment]
this works :)

Solved it. 
Thanks!!!!
