### ISSUE TITLE
Group Creation

### ISSUE THREAD

**Issue by igorgcampos** [lordmilko/PrtgAPI#158]
Hello,
How can i create a group a set them to active directory integration?
Can i set this properties in Ad-Group creation ?
![Capturar](https://user-images.githubusercontent.com/31486326/87991158-ee10e080-cabb-11ea-83e8-371187f84057.JPG)

Thank you

**Comment by lordmilko** [comment]
Hi @igorgcampos,

PrtgAPI does not natively support the creation of User Group objects in PRTG

You can potentially manually do this yourself however by creating the group in PRTG and observing the API request that is made using [Fiddler](Susan Mikula
). You can then construct this URL yourself in your own program

e.g.

```powershell
https://prtg.example.com/editsettings?name_=Group&isadmingroup_=0&etc=etc&username=myusername&password=mypassword
```

I'm not sure how many groups you need to automate but if it's not actually that many it would probably be easier to just do it manually

Regards,
lordmilko

**Comment by igorgcampos** [comment]
Hi there,
Is possible to remove device from a specific group?


Em seg., 20 de jul. de 2020 às 23:05, lordmilko <notifications@github.com>
escreveu:

**Comment by lordmilko** [comment]
Hi @igorgcampos,

Are you able to clarify what you mean exactly? Are you referring to groups as in organizational groups in the PRTG UI? (devices, groups, probes). You can delete objects in PrtgAPI using the `Remove-Object` cmdlet and move them using the `Move-Object` cmdlet

**Comment by noaboa97** [comment]
Hi guys,

@igorgcampos 

Today I wrote a PowerShell to add a PRTG usergroup. 
I tested it in my lab and it worked fine.

https://github.com/noaboa97/PrtgAPI-Scripts/blob/main/Functions/New-PrtgUsergroup.ps1
