### ISSUE TITLE
GET-GROUP / GET-SENSOR

### ISSUE THREAD

**Issue by EDBent** [lordmilko/PrtgAPI#159]
We have many problems with using the function get-sensor by group, hviws you have groups with the same name e.g. Network / switch, then it returns a list with all sensors in all groups with the same name, although that but ask for an ID on a group
                       GRP L1      GRP L2   DEVICE   SENSOR
CUSTOMS 1/NETWORK/**SWITCH"ID:2340"**/SERVER1-(CPU,DISK,MEMORY)
CUSTOMS 2/NETWORK/SWITCH"ID:4343"/SERVER2-(CPU,DISK,MEMORY)
CUSTOMS 3/NETWORK/SWITCH"ID:4341"/SERVER3-(CPU,DISK,MEMORY)

$SensorList = Get-Group -Probe $probe -Id 2340 | Get-Sensor -Probe $probe -Recurse:$false
$SensorList  = Sensor from Server1 and Server 2 and Server 3

expect only to see sensor which is in the group with Id 2340

CODE:
$SensorList = Get-Group -Probe $probe -Id $Grp_Id | Get-Sensor -Probe $probe -Recurse:$false

**Comment by lordmilko** [comment]
Hi @EDBent,

I see a few issues with your syntax here:

```powershell
$SensorList = Get-Group -Probe $probe -Id 2340 | Get-Sensor -Probe $probe -Recurse:$false
```
1. ```powershell
   Get-Group -Probe $probe -Id 2340
   ```
   If you want to get all groups from the probe `$probe` you would do `$probe | Get-Group`. If you wanted to get the probe with ID `2340` you would do `Get-Group -Id 2340`. Specifying both of these at once is redundant
2. ```powershell
   | Get-Sensor -Probe $probe
   ```
   To get all of the sensors from the group in step 1 you would simply pipe to `Get-Sensor`. Specifying `-Probe` is redundant; by piping a `Group` to `Get-Sensor` the results will implicitly be filtered to only the sensors under that `Group`

3. ```powershell
   -Recurse:$false
   ```
   Why are you specifying `-Recurse:$false`? In your server list above, the "Switch" group with ID 2340 just seems to contain the `Device` `SERVER1`. Does `Switch` group actually contain other groups as well?

As such, I believe if you rewrite this code as follows

```powershell
Get-Group -Id 2340 | Get-Sensor
```
or
```powershell
$probe | Get-Group | Get-Sensor
```
it should work as expected.

By default, PrtgAPI retrieves sensors from its parent group by name (since this is what the PRTG API actually supports, and is the fastest method of operation). You can see in the [special logic](https://github.com/lordmilko/PrtgAPI/blob/master/src/PrtgAPI.PowerShell/PowerShell/Cmdlets/ObjectData/GetSensor.cs#L142) for retrieving sensors from groups that the logic doesn't apply if `Recurse` isn't specified, so I think that is the key reason why you are having this issue. Reading my comments on in the code linked above, I'm not sure I understand why that is the case, so are you potentially able to advise why you are specifying `-Recurse:$false`?

**Comment by EDBent** [comment]
HI
We have 10 PROBS in our PRTG setup
and we need to be able to find the sensors that are on a PROB and on a SPEC group e.g. SWITCH ID: 2340, but it retrieves all groups named SWICTH under all PROBS, but if we adjust all groups so that they are named "SWITCH-C1" "SWITCH-C2", then it works OK.

Med venlig hilsen / Best regards / Inussiarnersumik inuulluaqqusilluta

Bent Thorning
Infrastructure consultant

Tel
:
+45 96 34 55 20<tel:+45%2096%2034%2055%2020>
E-mail
:
bth@inuit.dk<mailto:bth@inuit.dk>




[inuit_rgb]

www.inuit.dk<http://www.inuit.dk/>

____________________________________________________________
inu:it a/s · Tilstedvej 73 · 7700 Thisted · Danmark · CVR: 35 19 32 19

PRIVATLIVSPOLITIK - LÆS MERE<https://inuit.dk/om-inuit/privatlivs-og-cookiepolitik/>
SULIFFIUP AVATAANI INUUNERMUT POLITIKKI - ANNERTUNERUSUMIK ATUARIT<https://www.inuit.gl/inuit-pillugu/suliffiup-avataani-inuunermut-politikki/>

Fra: lordmilko <notifications@github.com>
Sendt: 21. juli 2020 13:36
Til: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Bent Thorning | inu:it a/s <BTH@inuit.dk>; Mention <mention@noreply.github.com>
Emne: Re: [lordmilko/PrtgAPI] GET-GROUP / GET-SENSOR (#159)


Hi @EDBent<https://github.com/EDBent>,

I see a few issues with your syntax here:

$SensorList = Get-Group -Probe $probe -Id 2340 | Get-Sensor -Probe $probe -Recurse:$false

1.  Get-Group -Probe $probe -Id 2340

If you want to get all groups from the probe $probe you would do $probe | Get-Group. If you wanted to get the probe with ID 2340 you would do Get-Group -Id 2340. Specifying both of these at once is redundant

2.  | Get-Sensor -Probe $probe

To get all of the sensors from the group in step 1 you would simply pipe to Get-Sensor. Specifying -Probe is redundant; by piping a Group to Get-Sensor the results will implicitly be filtered to only the sensors under that Group

3.  -Recurse:$false

Why are you specifying -Recurse:$false? In your server list above, the "Switch" group with ID 2340 just seems to contain the Device SERVER1. Does Switch group actually contain other groups as well?

As such, I believe if you rewrite this code as follows

Get-Group -Id 2340 | Get-Sensor

or

$probe | Get-Group | Get-Sensor

it should work as expected.

By default, PrtgAPI retrieves sensors from its parent group by name (since this is what the PRTG API actually supports, and is the fastest method of operation). You can see in the special logic<https://github.com/lordmilko/PrtgAPI/blob/master/src/PrtgAPI.PowerShell/PowerShell/Cmdlets/ObjectData/GetSensor.cs#L142> for retrieving sensors from groups that the logic doesn't apply if Recurse isn't specified, so I think that is the key reason why you are having this issue. Reading my comments on in the code linked above, I'm not sure I understand why that is the case, so are you potentially able to advise why you are specifying -Recurse:$false?

**Comment by EDBent** [comment]
We have 10 PROBS in our PRTG setup
and we need to be able to find the sensors that are on a PROB and on a SPEC group e.g. SWITCH ID: 2340, but it retrieves all groups named SWICTH under all PROBS, but if we adjust all groups so that they are named "SWITCH-C1" "SWITCH-C2", then it works OK.

**Comment by EDBent** [comment]
Opdate
CUSTOMS 1/NETWORK-SITE1/SWITCH"ID:2340"/SERVER1-(CPU,DISK,MEMORY)
CUSTOMS 1/NETWORK-SITE2/SWITCH"ID:2365"/SERVER1-(CPU,DISK,MEMORY)
CUSTOMS 1/NETWORK-SITE4/SWITCH"ID:2376"/SERVER1-(CPU,DISK,MEMORY)

CUSTOMS 2/NETWORK/SWITCH"ID:4343"/SERVER2-(CPU,DISK,MEMORY)
CUSTOMS 3/NETWORK/SWITCH"ID:4341"/SERVER3-(CPU,DISK,MEMORY)

Get-Group -Probe $CUSTOM1 -Id 2340 | Get-Sensor -Probe CUSTOMS1 -Recurse:$false
Return all Sensor data from all groups name "SWITCH" for alle PROBS and all groups named SWITCH

**Comment by lordmilko** [comment]
Please see my comment above; the issue is you are specifying redundant `-Probe` parameters and are specifying `-Recurse:$false`. if you remove these parameters it should work as expected

**Comment by EDBent** [comment]
Hi
 it almost works, but I only need to see the sensor as it is on one group with this ID: 2340, but it includes all groups as it is under the group: SWITCH ID: 2340


PS D:\Optælling POWERSHELL\PrtgAPI> 
PS D:\Optælling POWERSHELL\PrtgAPI> Get-Group -Id 32024 | Get-Sensor 

Name                         Id     Device               Group                     Probe                 Status        
----                         --     ------               -----                     -----                 ------        
        
(001) Nianet Uplink Prima... 34187  DKLY-CORE01          Switches                  CUSTOM1     Up            
(051) Uplink til DKLY-COR... 34220  DKLY-CORE01          Switches                  CUSTOM1     Up            
(052) Uplink til DKLY-NEW... 34221  DKLY-CORE01          Switches                  CUSTOM1     Up            
(054) Nianet uplink, Seco... 34222  DKLY-CORE01          Switches                  CUSTOM1     Up            
(104) Uplink til DKLY-COR... 34254  DKLY-CORE01          Switches                  CUSTOM1     Up            
(105) Uplink til DKLY-NEW... 34255  DKLY-CORE01          Switches                  CUSTOM1     Up            
**Ping-TEST                    38953  10.93.32.215         SWITCH2                   CUSTOM1     UP**

**Comment by lordmilko** [comment]
Hi @EDBent,

You can potentially work around this for now by doing

```powershell
Get-Group -Id 2340 | Get-Device -Recurse:$false | Get-Sensor
```

This should get all of the devices directly under the group with ID 2340, and then get the sensors from all of those devices, without processing any sub groups.

I'm thinking potentially I may need to adjust the behavior of the `-Recurse:$false` parameter so it also works around the issue of having multiple groups with the same name, as it does when specifying `-Recurse:$true`.

Please let me know how you go with the code above

**Comment by EDBent** [comment]
Yes Yes, 
 It just works great, and a really good solution to this, I thank you many times for the quick support, for this challenge
