### ISSUE TITLE
Is possible to add sensors with the number off OID?

### ISSUE THREAD

**Issue by marcelo-0511** [lordmilko/PrtgAPI#161]
Hello, how are you?

Is possible to add sensors with the OID number, for example:

I would like to add this sensor in other devices automaticaly

![image](https://user-images.githubusercontent.com/67024069/88311172-f13be480-cce6-11ea-86c4-9897e50a1643.png)

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

The `DynamicSensorParameters` returned when creating sensors via [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell) should contain an `oid` property for sensors that support this property. The OID of existing sensors can be modified later on via the [Set-ObjectProperty] cmdlet (https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#set-1)

```powershell
$params = New-SensorParameters -RawType blah
$params.oid = "etcetc"
```

Regards,
lordmilko

**Comment by marcelo-0511** [comment]
Can you  show me a exemple?

I have this OIDs.
![image](https://user-images.githubusercontent.com/67024069/88351358-64b41500-cd2c-11ea-88bf-a811a839dbdc.png)


I Would like add this sensor to 200 devices.

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

I don't have access to any SNMP devices so I can't give you a concrete example, if you read the documentation on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell) it should be pretty self explanatory. I imagine you will need to start with something like this

```powershell
$params = $device | New-SensorParameters -RawType snmplibrary -qt "*fortinet-fortigate*"
```

Have a go following the instructions on the wiki; if you have any issues please provide the code you've written so far, advise what the issue is and advise what the output of your `$params` variable is

**Comment by marcelo-0511** [comment]
![image](https://user-images.githubusercontent.com/67024069/88725347-5f771180-d102-11ea-8153-68654ebee3c2.png)

![image](https://user-images.githubusercontent.com/67024069/88725602-bf6db800-d102-11ea-9726-dfbf4faadec5.png)

![image](https://user-images.githubusercontent.com/67024069/88725680-dd3b1d00-d102-11ea-843e-87e598f7ac38.png)

Hello, good evening

Above there are the screenshoots of the errors were occur.


There is this a difference when i try to create a new-sensorParameters the parameters show me just one sensor bu when i check with command get-sensortarget can i see many sensors?

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

There are 2 issues here

1. As per the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#advanced-creation),

> When resolving added sensors, for accuracy and performance purposes PrtgAPI limits its search to sensors that have the same Type specified in the NewSensorParameters object. If you are creating a sensor with a dynamic sensor type that changes based on exact parameters that are specified (such as snmplibrary) you should set the DynamicType property of the parameters object to true. This can be done at the time of parameter creation via the -DynamicType parameter
> ```powershell
> $params = $device | New-SensorParameters -RawType snmplibrary -DynamicType
> ```

2. Again, as per the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#targets-1)

> By default, any fields that represent sensor targets will store the first sensor target compatible with that field. For scenarios in which a sensor type only has a single sensor target property, the -Target parameter can be specified to New-SensorParameters, specifying a wildcard expression used to identify the sensor targets to utilize.
>```powershell
> # Create a new set of VMware Datastore parameters targeting all available datastores
> C:\> Get-Device esxi-1 | New-SensorParameters -rt vmwaredatastoreextern -Target *
> ```

**Comment by marcelo-0511** [comment]
Sorry for my delay.

I understood it now.


## That is my example
[string]$regex = '1\.3\.6\.1\.4\.1\.12356\.101\.4\.9\.2\.1\.[954]\.[1-3]\b'

 #SDWAN OID
 $link_OID = Get-Device -Id $id1 | New-SensorParameters -RawType snmplibrary -qt Mod_sd-wan.oidlib -DynamicType -Target *

 $link_OID.interfacenumber__check =  $link_OID.Targets["interfacenumber__check"] | ? Value -Match "$regex"

It got just OIDs tha match de Regex OID.

Thanks for your reply.
