### ISSUE TITLE
Remove-NotificationTrigger Inherited from parent example.

### ISSUE THREAD

**Issue by marcelo-0511** [lordmilko/PrtgAPI#162]
Can you show a example for Remove-NotificationTrigger inherited from parent?

I Tried it:
![image](https://user-images.githubusercontent.com/67024069/89852510-658ada80-db65-11ea-961b-e8f36732bb3e.png)

I see your wiki but, i did not undestand how to remove it. 

![image](https://user-images.githubusercontent.com/67024069/89855301-8276dc00-db6c-11ea-80a1-b7ecc7f8d99a.png)
 
Thanks for your time.

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

In order to retrieve the trigger, you simply need to remove it from the parent object that the trigger inherits from. You can see the error message says the sensor belongs to the object with ID 93710.

Assuming the object with ID 93710 is a device, you would do

```powershell
Get-Device -Id 93710 | Get-Trigger -Type State | Remove-NotificationTrigger -Force
```

Regards,
lordmilko

**Comment by marcelo-0511** [comment]
In time, i tried it too(In another sensor):
![image](https://user-images.githubusercontent.com/67024069/89856423-9ff97500-db6f-11ea-9223-345c12d8d3c6.png)


![image](https://user-images.githubusercontent.com/67024069/89856621-1dbd8080-db70-11ea-94b3-25560ae157b8.png)

**Comment by marcelo-0511** [comment]
Hi @lordmilko, thanks for your reply.

OK I understood, to remove for a especific sensor is not possible.

Is possible to remove the notification trigger inheritance from a device, with PRTGAPI?


More one time, thanks!



inheritance |  
-- | --




inheritance |  
-- | --

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

You can disable notification trigger inheritance on a specific device by setting the `InheritTriggers` property to `$false`

`Get-Device -Id 1001 | Set-ObjectProperty InheritTriggers $false`

For more information on modifying object properties please see [Property Manipulation](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation)

**Comment by marcelo-0511** [comment]
Sorry for my delay.

It is great and works.

Thank you!
