### ISSUE TITLE
related to  article - blog.paessler.com/how-to-add-hundreds-of-devices-to-prtg

### ISSUE THREAD

**Issue by ASDThys** [lordmilko/PrtgAPI#163]
Hi There. 

I am trying to get this to work but when ever I run the script I get this error. 

Get-PrtgClient : The term 'Get-PrtgClient' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At C:\Users\Thys Uys\Downloads\AddServers_example\AddServers.ps1:1 char:6

I made 1 change to the original script by adding my PRTG server IP . script attached. 

Please point me in the right direction as i am old to PRTG but new to scripting and need to get this client sorted. 
[AddServers.zip](https://github.com/lordmilko/PrtgAPI/files/5074601/AddServers.zip)

**Comment by lordmilko** [comment]
Hi @ASDThys,

You need to install PrtgAPI first. Please see [Installation](https://github.com/lordmilko/PrtgAPI/wiki/Installation) for more info on how to do this.

After you've installed PrtgAPI, note that the script on the blog post can't just be run immediately - while you've updated the server IP, you'll probably need to modify the script a bit for your scenario (e.g. you might want to have fewer or a greater number of groups than the example has) as well as update the `Servers.csv` file accordingly.

For more information on using PrtgAPI please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki)

**Comment by ASDThys** [comment]
HI There.

I have just installed  the software . I am testing currently , thanks for you help

To Book a session with me , follow this link : https://calendly.com/thysu

Kind Regards
[Africa Solution Distributor]

Thys Uys
Pre Sale Technical Engineer
Africa Solution Distributor
Your Preferred Network and
Cloud Solution Distributor in Africa.
Office: +27 (0) 12 665 0888
Skype : matthysuys2
      [cid:image002.png@01D6724C.931890F0] <https://asdafrica.com/>   [cid:image003.png@01D6724C.931890F0] <https://asdafrica.com/contact-us/>   [cid:image004.png@01D6724C.931890F0] <https://asdafrica.com/solution/>                     [cid:image005.png@01D6724C.931890F0] <https://www.facebook.com/pg/Africa-Solution-Distributor-100124588373325/about/?ref=page_internal>     [cid:image006.png@01D6724C.931890F0] <https://www.linkedin.com/company/africa-solution-distributor/>      [cid:image007.png@01D6724C.931890F0] <https://www.instagram.com/africasolutiondistributor/>     [cid:image008.png@01D6724C.931890F0] <https://twitter.com/AfricaSolution2>
