### ISSUE TITLE
Get-Sensor retrieves incorrect interval

### ISSUE THREAD

**Issue by Torrenator** [lordmilko/PrtgAPI#166]
When I retrieve all sensors from a certain probe I see interval times of 1 day. When I check the PRTG webpage I see that the interval is set to 30 seconds.

**Steps to reproduce**

```powershell
Get-Sensor -Status Up -Filter $FilterProbe | Select Name,Id,Interval
```
This is the result I get from the command
```powershell
Name                       Id Interval
----                       -- --------
System Health            2426 00:01:00
Common SaaS Check        2428 1.00:00:00
Disk Free                2429 00:01:00
vmxnet3 Ethernet Adapter 2430 00:01:00
Ping                     9084 1.00:00:00
CPU                      9085 1.00:00:00
Memory                   9086 1.00:00:00
```
**What is the output of `Get-PrtgClient -Diagnostic`?**
This did not work for me. Maybe the command changed? This is from Get-PrtgClient -Debug
```powershell
Server     : xxx
UserName   : xxx
PassHash   : xxx
Version    : 20.3.61.1649
RetryCount : 1
RetryDelay : 3
LogLevel   : Trace, Request
```

**Additional context**
The new environment I am making my scripts on is not yet licensed correctly. Which in turn pauses some sensors. Thats why I have the -Status Up in my query. The sensors where I see the 1 day interval are running fine.

**Comment by lordmilko** [comment]
Hi @Torrenator,

If `Get-PrtgClient -Diagnostic` does not work for you, that immediately indicates you are running an older version of PrtgAPI that does not support this parameter. I doubt that that would make a difference here however.

Can you please run the following commands and provide the complete output of the following?

```
Set-PrtgClient -LogLevel Response

Get-Sensor -Id 9084 -Verbose | Select Name,Id,Interval
```

This will show us the raw XML response that was returned from PRTG along with the deserialized output that is normally shown by PrtgAPI. This will allow us to compare the value the server is providing with the value that PrtgAPI is interpreting. I am assuming that the Ping sensor with ID 9084 is indeed supposed to be 30 seconds and not 1 day. If not, please change this ID to the ID of another sensor that is reporting the wrong interval

**Comment by Torrenator** [comment]
Hi @lordmilko,

Thanks for the quick response. Your right about the older version. I am running 0.9.9 at the moment. 
The sensor ID 9084 is indeed one of the sensors giving this issue. Please see the response.

```powershell
VERBOSE: Get-Sensor: <?xml version="1.0" encoding="UTF-8"?>
  <sensors totalcount="1" listend="1">
   <prtg-version>20.3.61.1649</prtg-version>
   <item>
    <objid>9084</objid>
    <name>Ping</name>
    <probe>MONITOR10</probe>
    <group>Windows</group>
    <favorite>&lt;span class=&quot;objectisnotfavorite icon-gray ui-icon ui-icon-flag&quot; title=&quot;Flag/Unflag as Favorite&quot; id=&quot;fav-9084&quot; onclick=&quot;_Prtg.objectTools.faveObject.call(this,9084,&apos;toggle&apos;);return false;&quot;&gt;&lt;/span&gt;</favorite>
    <favorite_raw>0</favorite_raw>
    <lastvalue>0 msec</lastvalue>
    <lastvalue_raw>0.0000</lastvalue_raw>
    <device>S38TS02</device>
    <downtime>0,0000%</downtime>
    <downtime_raw>000000000000000</downtime_raw>
    <downtimetime>0 s</downtimetime>
    <downtimetime_raw>000000000000000</downtimetime_raw>
    <downtimesince/>
    <uptime>100,0000%</uptime>
    <uptime_raw>000000001000000</uptime_raw>
    <uptimetime>1 h 41 m</uptimetime>
    <uptimetime_raw>000000000006090</uptimetime_raw>
    <uptimesince>1 h 59 m</uptimesince>
    <uptimesince_raw>000000000007174</uptimesince_raw>
    <knowntime>63%</knowntime>
    <knowntime_raw>000000000000000</knowntime_raw>
    <cumsince>2-9-2020 12:08:24 &lt;span class=&quot;percent&quot;&gt;[3 h 13 m ago]&lt;/span&gt;</cumsince>
    <cumsince_raw>44076.4225017014</cumsince_raw>
    <lastcheck>2-9-2020 15:02:20 &lt;span class=&quot;percent&quot;&gt;[19 m 4 s ago]&lt;/span&gt;</lastcheck>
    <lastcheck_raw>44076.5432888657</lastcheck_raw>
    <lastup>2-9-2020 15:02:20 &lt;span class=&quot;percent&quot;&gt;[19 m 4 s ago]&lt;/span&gt;</lastup>
    <lastup_raw>44076.5432888657</lastup_raw>
    <lastdown>-</lastdown>
    <minigraph>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,9,28,2,1,3,2,1,3,0,2,11,2,2,2,7,8,10,3,5,11,2,2|0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</minigraph>
    <schedule/>
    <basetype>sensor</basetype>
    <baselink>/sensor.htm?id=9084</baselink>
    <baselink_raw>9084</baselink_raw>
    <notifiesx>Inherited</notifiesx>
    <intervalx_raw>0000086400</intervalx_raw>
    <access>Full access</access>
    <access_raw>0000000400</access_raw>
    <dependency>Parent</dependency>
    <dependency_raw>S38TS02</dependency_raw>
    <position>10</position>
    <position_raw>0000000010</position_raw>
    <status>Up </status>
    <status_raw>3</status_raw>
    <priority>3</priority>
    <message>&lt;div class=&quot;status&quot;&gt;OK&lt;div class=&quot;moreicon&quot;&gt;&lt;/div&gt;&lt;/div&gt;</message>
    <message_raw>OK</message_raw>
    <parentid>9083</parentid>
    <tags>pingsensor S38 vcenter03.aspect.local Windows AMS4</tags>
    <type>Ping</type>
    <type_raw>ping</type_raw>
    <active>True</active>
    <active_raw>-1</active_raw>
   </item>
  </sensors>

Name   Id Interval
----   -- --------
Ping 9084 1.00:00:00```

Looking at the raw data it looks like the PRTG server is supplying the wrong data. I am going to do a reboot of the server to see if that changes anything.

**Comment by lordmilko** [comment]
It might also be worth checking on the Settings page of the sensor whether the sensor is set to inherit its interval from its parent object. In theory PRTG is supposed to also return this information in the API request, however I can see in your response that you are missing the `intervalx` property (which is what would specify this). Based on the logic PrtgAPI uses for inspecting the `intervalx` property, if this value is missing this indicates the object does *not* inherit its interval, so I'm not sure what would be going on with your erroneous interval beyond asking *are we really sure it's not set to 1 day?*

**Comment by Torrenator** [comment]
After restarting only the PRTG Core Server service the data seems to be completely different. Right now I am seeing the interval as 60 seconds. And it reports it back correctly. Which I now remember it was also weird seeing 30 seconds in the first place.

I do set the interval everytime via the add-sensor request because I work with templates defined in another format which would indeed indicate the missing intervalx property.

**Comment by lordmilko** [comment]
Thanks @Torrenator,

As this now appears to be working properly I will close this issue. Please let me know if you have any further issues

Regards,
lordmilko
