### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#167]
**What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?**

a query,
Is there a way to pause a sensor automatically, that is, every day?

**Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?**

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [ ] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [ ] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
Hi @lordmilko,

PrtgAPI simply exposes the underlying PRTG HTTP API in an easy to use framework.

In regards to your query, you have two options
1. If the schedule is going to be same every day, you can [modify the *Schedule* property](https://github.com/lordmilko/PrtgAPI/issues/101#issuecomment-520066779) normally found on the object's Settings page
2. If you'd like to have greater control over which objects are paused and when, you can setup a Scheduled Task on one of your servers that periodically runs (e.g. once every hour) and dynamically calculates which objects should be paused and then pauses them with the [Pause-Object](https://github.com/lordmilko/PrtgAPI/wiki/State-Manipulation#pause-1) cmdlet

Regards,
lordmilko

**Comment by mafer0410** [comment]
if it were the second option, would it be through a powershell script?

**Comment by lordmilko** [comment]
Hi @mafer0410,

Yes, you would write a PowerShell script that determines the sensors to be paused and then pauses them with the `Pause-Object` cmdlet

**Comment by mafer0410** [comment]
ok, it would be to call the sensors of a device and pass it with the
command, the time of the pause can be added as parameters,
for example, pause it at 8:00 am every day

**Comment by lordmilko** [comment]
Hi @mafer0410,

Yes. Please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) for more information on how to use PrtgAPI

* [Retrieving sensors](https://github.com/lordmilko/PrtgAPI/wiki/Sensors)
* [Retrieving devices](https://github.com/lordmilko/PrtgAPI/wiki/Devices)
* [Pausing objects](https://github.com/lordmilko/PrtgAPI/wiki/State-Manipulation#pause-1)

**Comment by mafer0410** [comment]
OK understood.
Thanks for the attention.
I was a few days off, so I did not answer him.
The attention is also appreciated.
