### ISSUE TITLE
Generate reports.

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#168]
Hello,
sorry for the inconvenience,
I have a question, rather it is to obtain a little more knowledge.

Is there a way to generate reports about the PRTG information or would it just be to choose the object information and extract it?

**Comment by lordmilko** [comment]
Hi @mafer0410,

PrtgAPI does not support generating Reports (i.e. the things you would find under https://prtg.example.com/reports.htm)

Depending on your use case, you can however generate your own reports using the interfaces PrtgAPI provides you. Most the information you'd want to extract would be retrieved using the interfaces described in [Historical Information](https://github.com/lordmilko/PrtgAPI/wiki/Historical-Information) on the wiki

Regards,
lordmilko

**Comment by mafer0410** [comment]
but is it possible to export the information of a command to a csv?

**Comment by lordmilko** [comment]
PowerShell data can be exported to a CSV using [standard PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-7)

**Comment by mafer0410** [comment]
Thank you
