### ISSUE TITLE
No Data from get-devicetemplate

### ISSUE THREAD

**Issue by dekinew** [lordmilko/PrtgAPI#169]
Hi lordmilko..
i am currently learning to work with your API. unfortunately, i cannot read out templates with get-devicetemplate in order to use them on newly created devices. i have looked at the get-help infos including examples. am i doing something wrong? when run: get-devicetemplate, i get no error and no information about the standard or custom templates.
regards, dennis

**Comment by lordmilko** [comment]
Hi @dekinew,

Can you please provide the output of `Get-PrtgClient -Diagnostic`

In addition, what happens if you do `Get-Device -count 1 | Get-DeviceTemplate`?

**Comment by dekinew** [comment]
hi @lordmilko...
i found my mistake.. know it works :)

**Comment by lordmilko** [comment]
Hi @dekinew,

Are you able to advise what the issue was?
