### ISSUE TITLE
Get-Device -Recurse irrelevant

### ISSUE THREAD

**Issue by jones-g** [lordmilko/PrtgAPI#17]
It seems that the -Recurse option on "Get-Device" is irrelevant as get-device by default is recursive thus enabling more recursion is not relevant. It might be that the default should be non recursive and -Recurse enables recursion.

Example that has been somewhat anonymized:
get-device -Group (get-group -id 111781) | select Id, @{N='GroupId';E={$_.ParentId}}
    Id GroupId
    -- -------
111816  112487
111782  112488
112102  112486
111803  112435
112020  112484
111973  112483
111849  112482
111813  112487
112023  112486
111804  112435
112017  112484
111971  112483
111966  112482
111796  112487
112108  112486
111832  112435
112014  112484
112109  112486
111842  112435
111982  112484
112119  112486
112154  111781
112144  112486
112159  111781
112149  112486
112164  111781
112178  111781
112183  111781
112188  111781

As can be seen. Not only devices in the group with id 111781 are included but also sub groups and sub sub groups are included.

If I include the -Recurse switch I get the exact same result
get-device -Group (get-group -id 111781) -Recurse | select Id, @{N='GroupId';E={$_.ParentId}}
    Id GroupId
    -- -------
111816  112487
111782  112488
112102  112486
111803  112435
112020  112484
111973  112483
111849  112482
111813  112487
112023  112486
111804  112435
112017  112484
111971  112483
111966  112482
111796  112487
112108  112486
111832  112435
112014  112484
112109  112486
111842  112435
111982  112484
112119  112486
112154  111781
112144  112486
112159  111781
112149  112486
112164  111781
112178  111781
112183  111781
112188  111781

I updated my PRTGApi version to 0.8.6 from 0.8.5 to see if that helped but no luck - same problem. My suggestion would be to either make the default "Get-Device" not recursive as to allow the -Recurse switch a prupose or replace the -Recurse switch with a -NoRecurse switch that disables recursion instead.

**Comment by lordmilko** [comment]
Hi @jones-g,

You are correct - the default behavior of the `-Recurse` switch is `-Recurse:$true`. To *disable* recursion, you can specify `-Recurse:$false`

The reason `-Recurse` defaults to true is that it seems very logical to have a *container* group that serves no purpose but to contain *sub-container* groups. The impetus for implementing this feature in the first place was that at my job we divide each state into a number of sub-regions, and it was very annoying doing `Get-Group <state> | Get-Device` and getting no results. When I say give me every device in the state, *I mean give me every device in the state!*

For reference, there is a note about this on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Groups#group-recursion-1). You can also see information about each parameter supported by a cmdlet within PowerShell by running `Get-Help <cmdlet> -Full`

Please let me know if you have any further issues

**Comment by jones-g** [comment]
@lordmilko You know what - I hadn't seen that :) Great! Just what I was looking for. I can understand the rationale, I had just gotten used to VMware's approach which is the same - default recursion on but with a -NoRecursion switch. 

No further issues from my side :)
