### ISSUE TITLE
Multiple Channel creation during Sensor creation

### ISSUE THREAD

**Issue by asacic** [lordmilko/PrtgAPI#175]
**What's going on?**

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [x] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

Hi,

I was looking through the Wiki and was not able to find an option where i could create multiple channels during sensor creation. 
At the moment I am creating the Sensor like this 
``` C#
var parameters = _prtgClient.GetDynamicSensorParameters(device, "httpiotpushdataadvanced");
parameters.Name = sensorName;
parameters["httppushtoken"] = $"{nodeId}_{sensorName}".ToSha256();
return _prtgClient.AddSensor(device, parameters);
```

Ideally, i would want to create the Channels here as well and assign them proper Value Lookups with 
```C#
_prtgClient.SetChannelProperty(channel,ChannelProperty.ValueLookup,valueLookupName);
```

Is there any way to do this during Sensor creation, or do I really have to 
1) Create the Sensor
2) Send HTTP POST for Channel Creation
3) Fetch the Sensor + Channels
4) Set the Value Lookup on the Channel

Thank you very much for your help!

**Comment by lordmilko** [comment]
Hi @asacic,

Looking at *Add Sensors* page of this sensor type in the PRTG UI, I don't see an option to specify anything to do with channels at the time of sensor creation.

As such, you would need to create this sensor first, then modify the channels later. Some sensors don't have *any* channels when they're created (which appears to be the case for this sensor type), so you would need to poll the sensor once a second or something until the channels have been created, and then you can go ahead and use `SetChannelProperty`

```c#
var sensor = client.AddSensor(device, parameters).First();

List<Channels> channels;

do
{
    channels = client.GetChannels(sensor);

    if (channels.Count == 0)
    {
        Console.WriteLine("Waiting for channel creation");
        client.RefreshObject(sensor.Id);
        Thread.Sleep(1000);
    }
} while (channels.Count == 0);

var channel = channels.First(/* Which channel */);

client.SetChannelProperty(channel, ChannelProperty.ValueLookup, valueLookupName);
```
