### ISSUE TITLE
Change local user passwords via script?

### ISSUE THREAD

**Issue by dekinew** [lordmilko/PrtgAPI#178]
Hi @lordmilko
Today we got a new customer request, wheter he could change user (local) passwords via script.
I think it works only via specifying the relevant raw parameters, correct?
Regards, Dennis

**Comment by lordmilko** [comment]
Hi @dekinew,

You should be able to reset local PRTG user accounts as follows

```powershell
$password = "Password1"

Get-Object "John Smith" | Set-ObjectProperty -RawParameters @{
    passwordradio=1
    password1=$password
    password2=$password
    password_=""
} -Force
```

Regards,
lordmilko

**Comment by dekinew** [comment]
ok, thanks, @lordmilko
