### ISSUE TITLE
Automate Business Process Sensor creation

### ISSUE THREAD

**Issue by dekinew** [lordmilko/PrtgAPI#179]
Hello lordmilko, it's me again ;)
Can I create a Business Process Sensor per server via script and fill it with certain sensors attached to this device including the percentage values for warnings/errors? Why: A customer wants to measure the availability of his 400 servers, per server and he don't want to create manual these 400 Sensors.

Regards, Dennis

**Comment by lordmilko** [comment]
Hi @dekinew,

Yes, you can create any type of sensor with PrtgAPI. In the case of Business Process sensors however, these are particularly complicated as most of the configuration is actually done in JSON

To create a Business Process sensor I suggest you use [Fidder](https://www.telerik.com/fiddler) to capture the HTTP request executed on your computer for creating the sensor when you configure it the way you want in the PRTG UI, then follow the process described on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell) for creating dynamic sensor parameters.

```powershell
# Get the parameters from one of the devices
$params = Get-Device -Id 1001 | New-SensorParameters -RawType businessprocess

# Fill in the sensor definition based on the information you see in Fiddler.
# Depending on your requirements you can modify the Fiddler JSON as required
$params.businessprocessdefinitions = $definition

# Add the sensor
Get-Device -Tags NY | Add-Sensor $params
```

The following shows the example JSON of specifying two Business Process sensor channels

```json
[{"objects":[2081],"warningthreshhold":75,"errorthreshhold":50,"channelname":"test"},{"objects":[2079],"warningthreshhold":80,"errorthreshhold":70,"channelname":"test1"}]
```

Regards,
lordmilko
