### ISSUE TITLE
Question: Setting dependencies when creating devices? 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#18]
Hi there, i was wondering if it was possible to set pause parent dependencies when creating devices through script? i looked at the wiki but couldnt see an option

**Comment by lordmilko** [comment]
Hi @SamuelmAsh,

Are you asking whether you can set the *Dependency* from under the *Schedules, Dependencies, and Maintenance Window* settings when creating a device?

**Comment by SamuelmAsh** [comment]
Yeah thats the one, is it possible?

**Comment by lordmilko** [comment]
Arbitrary object properties can be modified after an object has been created via the `Set-ObjectProperty` cmdlet

PrtgAPI does not currently natively support setting *Schedules, Dependencies and Maintenance Window* settings, however this can still be easily achieved via the raw API

```powershell
# Create a device named "dc-1" and set its dependency to the object with ID 40
Get-Probe | Add-Device dc-1 | Set-ObjectProperty -RawParameters @{
    scheduledependency=0
    dependencytype_=1
    dependency_=40
} -Force
```
If you wish to store a reference to your newly created device to further utilize in your script, you can either store it in a variable before passing it to `Set-ObjectProperty` or specify the `-PassThru` parameter to `Set-ObjectProperty` to cause it to output the input device

Are you able to advise whether this is what you are looking for?

Regards,
lordmilko

**Comment by SamuelmAsh** [comment]
Absolutely perfect! thanks again LordMilko!
