### ISSUE TITLE
PowerShell State Manipulation - Pause

### ISSUE THREAD

**Issue by ChrisPennell** [lordmilko/PrtgAPI#184]
Sensor does not Pause:

When I execute the following, the Sensor doe not go into Pause and Scans as per it's schedule.

`  #connection successful
  Connect-PrtgServer http://127.0.0.1 (New-Credential prtgadmin '****') -Force -IgnoreSSL 

  Get-Device -Verbose "LAPTOP82" | Get-Object -id 2344

  Get-Device -Id 2344 -Verbose | Pause-Object -Forever -Message "etretwetewgeyrywe"

  Get-Sensor -Verbose -Id 2344 | Refresh-Object`

I have attached the PowerShell logging
[Log.txt](https://github.com/lordmilko/PrtgAPI/files/5599524/Log.txt)
[Log.txt](https://github.com/lordmilko/PrtgAPI/files/5599525/Log.txt)

- [ ] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [ x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @ChrisPennell,

Each cmdlet requires `-Verbose` to be specified to pause the object. Are you able to add `-Verbose` to the end of `Pause-Object` and provide its output?

**Comment by lordmilko** [comment]
Hi @ChrisPennell,

Are you able to provide an update on this or whether you managed to get this working?
