### ISSUE TITLE
Problem with Setting tags in Pipline

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#186]
**Describe the bug**
*Clearly and concisely describe what you were trying to do, what happened and what you were expecting to happen*

I'm trying to add a tag to a set of sensors

When I execute it directly it works.
In pipline, it does not.

**Steps to reproduce**
*Put the relevant code from your application that caused the issue to happen in the code block below*

```powershell
# Code goes here!
$todo = get-sensor  -Tag "snmptrafficsensor"  -Name "*RED*"
$todo | forEach-Object {	$props = $_ | Get-ObjectProperty 
$tags = $props.Tags
$tags += "bandwidthw_wan"
$_ | Set-ObjectProperty -Tags $tags -Force -WhatIf} 
```
```text
# Output goes here!
Set-ObjectProperty : Parameter 'Tags' cannot be specified in parameter set ''.
At line:3 char:24
+ ... nsor -Id $_.Id | Set-ObjectProperty -Tags $props.Tags -Force -WhatIf}
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ObjectProperty], ParameterBindingException
    + FullyQualifiedErrorId : ParameterNotInParameterSet,PrtgAPI.PowerShell.Cmdlets.SetObjectProperty
```

**What is the output of `Get-PrtgClient -Diagnostic`?**

```powershell
Get-PrtgClient -Diagnostic
Get-PrtgClient : A parameter cannot be found that matches parameter name 'Diagnostic'.
At line:1 char:16
+ Get-PrtgClient -Diagnostic
+                ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PrtgClient], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,PrtgAPI.PowerShell.Cmdlets.GetPrtgClient
```

**Additional context**
*Anything else I should know to help solve the issue?*
Just need the correct syntax to add a tag

Thanks
  JR

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

As `-Tags` is a supported parameter you don't need to specify `-Force`, which is part of the various "Raw*" parameter sets only

Are you able to advise whether this works if you don't specify `-Force`?

**Comment by PRTGC** [comment]
Sun-ov-a....
That works... 
Hmmm a bit cryptic that error, but it is working now...

Thanks
  JR

**Comment by lordmilko** [comment]
Normally you would expect to get an error that specifies the exact parameter set whose parameters were invalid; in this case, because `Set-ObjectProperty` has a very complex array of parameter sets it appears the PowerShell engine is getting confused and doesn't know what set to refer to, leading to an empty parameter set in the error message
