### ISSUE TITLE
 Is it possible to create a new SNMP sensor?

### ISSUE THREAD

**Issue by malvarado611** [lordmilko/PrtgAPI#190]
I would like to create a new SNMP sensor via API using PowerShell commands, it is possible to do this.

If so, could you guide me?

Greeting,
Miguel Alvarado

**Comment by lordmilko** [comment]
Hi @malvarado611,

Please read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki). Specifically, the following articles

* [Object Creation (Sensors)](https://github.com/lordmilko/PrtgAPI/wiki)
* [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell)

If you have a specific question about something you believe is not covered by the wiki, please open an issue.
