### ISSUE TITLE
Question Sensor Factory

### ISSUE THREAD

**Issue by malvarado611** [lordmilko/PrtgAPI#192]
I am testing the following command:
Get-Sensor -Tags wmicpu* | New-Sensor -Factory "CPU Overview" { $_.Device } -sn "Average CPU" -se Average -DestinationId 2116 -WhatIf

But I get the following error:
New-Sensor : Property 'ChannelDefinition' requires a value, however a collection consisting of null, empty or
whitespace values was specified.
En línea: 1 Carácter: 28
+ ... s wmicpu* | New-Sensor -Factory "CPU Overview" { $_.Device } -sn "Ave ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Sensor], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PrtgAPI.PowerShell.Cmdlets.NewSensor

Any idea why I get this error.

Regards,
Miguel Alvarado

**Comment by malvarado611** [comment]
Additionally, I am trying to create a new facotory sensor that allows adding the values ​​of two sensors created previously. I am trying to use the examples, but I have problems creating it. Could someone help me with this.

Regardas,
Miguel Alvarado

**Comment by lordmilko** [comment]
Hi @malvarado611,

When I copy and paste this command it works fine for me. Are you able to provide the output of `Get-PrtgClient -Diagnostic`?

In addition, what happens if you specify the parameter names manually

```powershell
Get-Sensor -Tags wmicpu* | New-Sensor -Factory -Name "CPU Overview" -ChannelName { $_.Device } -sn "Average CPU" -se Average -DestinationId 2116 -WhatIf
```

**Comment by malvarado611** [comment]
Hi lordmiko,

For the command Get-PrtgClient -Diagnostic I get the following:

PSVersion      : 5.1.18362.1171
PSEdition      : Desktop
OS             : Microsoft Windows 10 Pro
PrtgAPIVersion : 0.9.14
Culture        : es-PE
CLRVersion     : .NET Framework 4.8 (528040)
PrtgVersion    : 20.4.64.1402
PrtgLanguage   : spanish.lng


When I specify the parameter manually I get the following:
Get-Sensor -Tags wmicpu* | New-Sensor -Factory -Name "CPU Overview" -ChannelName { $_.Device } -sn "Average CPU" -se Average -DestinationId 2116 -WhatIf

New-Sensor : Property 'ChannelDefinition' requires a value, however a collection consisting of null, empty or
whitespace values was specified.

Get-Sensor -Tags wmicpu* | New-Sensor -Factory -Name "CPU Overview" -ChannelName { $_.Device } -sn "Average CPU" -se Average -DestinationId 2116 -WhatIf
En línea: 1 Carácter: 28
+ ... s wmicpu* | New-Sensor -Factory -Name "CPU Overview" -ChannelName { $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Sensor], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PrtgAPI.PowerShell.Cmdlets.NewSensor

Regards,
Miguel Alvarado
________________________________
De: lordmilko <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 18:51
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


Hi @malvarado611<https://github.com/malvarado611>,

When I copy and paste this command it works fine for me. Are you able to provide the output of Get-PrtgClient -Diagnostic?

In addition, what happens if you specify the parameter names manually

Get-Sensor -Tags wmicpu* | New-Sensor -Factory -Name "CPU Overview" -ChannelName { $_.Device } -sn "Average CPU" -se Average -DestinationId 2116 -WhatIf

**Comment by lordmilko** [comment]
Hi @malvarado611,

Are you able to advise what the output of

```powershell
Get-Sensor -Tags wmicpu*
```

is?

I found that if you try and pipe *no sensors* into `New-Sensor -Factory` it will throw this error

**Comment by malvarado611** [comment]
I have no result when I put this command.

Regards,
Miguel Alvarado

[cid:ad84b878-2a11-4d6b-8ef7-0a3f37da7cb8]
________________________________
De: lordmilko <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 19:03
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


Hi @malvarado611<https://github.com/malvarado611>,

Are you able to advise what the output of

Get-Sensor -Tags wmicpu*

is?

I found that if you try and pipe no sensors into New-Sensor -Factory it will throw this error

**Comment by lordmilko** [comment]
Hi @malvarado611,

This means that you either don't have any WMI CPU sensors in your PRTG installation, or your WMI CPU sensors don't have the default `wmicpuloadsensor` tag on them. As such you will need to modify your invocation of `Get-Sensor` to properly target the sensors you'd like to create sensor parameters for

**Comment by malvarado611** [comment]
Thank you.

Regarding this query.

Additionally, I am trying to create a new facotory sensor that allows adding the values ​​of two sensors created previously. I am trying to use the examples, but I have problems creating it.


Could you give me a help please.

Regards,
Miguel Alvarado
________________________________
De: lordmilko <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 19:08
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


Hi @malvarado611<https://github.com/malvarado611>,

This means that you either don't have any WMI CPU sensors in your PRTG installation, or your WMI CPU sensors don't have the default wmicpuloadsensor tag on them. As such you will need to modify your invocation of Get-Sensor to properly target the sensors you'd like to create sensor parameters for

**Comment by lordmilko** [comment]
Hi @malvarado611,

What is the probem you are having exactly?

Can you provide the code you have written so far?

**Comment by malvarado611** [comment]
Hi Lordmiko,

I have created two sensors which I want to add both values ​​and then multiply by 0.5. At the moment I am testing with the following command.

Get-Sensor -name * TOTAL * | New-Sensor -Factory "TEST FACTORY" {$ _. Device} -sn "TOTAL CALLS SBC" -se Average -DestinationId 2078 -WhatIf


I think I should change the value from Average to Factory ErrorMode CustomFormula, but I have had trouble entering the correct expression.

Regards,
Miguel Alvarado.
________________________________
De: lordmilko <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 19:36
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


Hi @malvarado611<https://github.com/malvarado611>,

What is the problem you are having exactly?

Can you provide the code you have written so far?

**Comment by lordmilko** [comment]
Hi @malvarado611,

So you are saying you want to have a sensor factory with three channels

1. The value of sensor 1's channel with index 0
2. The value of sensor 2's channel with index 0
3. The value of sensor 1's channel with index 0 with + the value of sensor 2's channel with index 0 all multiplied by 0.5

Information on how sensor factories can be created using PrtgAPI can be found on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Sensor-Factories)

In order to add the values of the two sensor channels together and multiply by 0.5 we will need to use the `-SummaryExpression` and `-SummaryFinalizer` parameters.

For the `-SummaryExpression` we wish to accumulate the total of all sensor channels; as such this parameter will simply be `-SummaryExpression { "$acc + $expr" }`

In order to multiply this value by 0.5 at the end, we would then specify `-SummaryFinalizer { "($acc) * 0.5" }`

The full result of this would be:

```powershell
C:\ Get-Sensor *total* | New-Sensor -Factory "TEST FACTORY" {$_.Device} -sn "TOTAL CALLS SBC" -se { "$acc + $expr" } -sf { "($acc) * 0.5" } -DestinationId 2078 -WhatIf

#1:TOTAL CALLS SBC
(channel(2061,0) + channel(2092,0)) * 0.5
#2:dc-1
channel(2061,0)
#3:exch-1
channel(2092,0)
```

**Comment by malvarado611** [comment]
Hi Lormiko,

Thanks for you help.

Regards,
Miguel Alvarado
________________________________
De: lordmilko <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 21:30
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


Hi @malvarado611<https://github.com/malvarado611>,

So you are saying you want to have a sensor factory with three channels

  1.  The value of sensor 1's channel with index 0
  2.  The value of sensor 2's channel with index 0
  3.  The value of sensor 1's channel with index 0 with + the value of sensor 2's channel with index 0 all multiplied by 0.5

Information on how sensor factories can be created using PrtgAPI can be found on the wiki<https://github.com/lordmilko/PrtgAPI/wiki/Sensor-Factories>

In order to add the values of the two sensor channels together and multiply by 0.5 we will need to use the -SummaryExpression and -SummaryFinalizer parameters.

For the -SummaryExpression we wish to accumulate the total of all sensor channels; as such this parameter will simply be -SummaryExpression { "$acc + $expr" }

In order to multiply this value by 0.5 at the end, we would then specify -SummaryFinalizer { "($acc) * 0.5" }

The full result of this would be:

C:\ Get-Sensor *total* | New-Sensor -Factory "TEST FACTORY" {$_.Device} -sn "TOTAL CALLS SBC" -se { "$acc + $expr" } -sf { "($acc) * 0.5" } -DestinationId 2078 -WhatIf

#1:TOTAL CALLS SBC
(channel(2061,0) + channel(2092,0)) * 0.5
#2:dc-1
channel(2061,0)
#3:exch-1
channel(2092,0)

**Comment by malvarado611** [comment]
Hi Lorkmico,

I have created a threshold type notification for a sensor with ID 2153 through the API, but when it is created it inherits another sensor in which I would like to modify the value of -OnNotificationAction.

Get-Sensor -Id 2153 | Get-Trigger | where SubId -eq 1 | Set-TriggerProperty -OnNotificationAction "Plantilla de prueba"

I get the following message:

Set-TriggerProperty : Cannot modify NotificationTrigger 'Plantilla de prueba' applied to object ID 2153 as this
trigger is inherited from object ID 0. To modify this trigger, retrieve it from its parent object.
En línea: 1 Carácter: 57
+ ... bId -eq 1 | Set-TriggerProperty -OnNotificationAction "Plantilla de p ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-NotificationTriggerProperty], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PrtgAPI.PowerShell.Cmdlets.SetNotificationTriggerProper
   ty


In the wiki I have read that this is for security reasons, but it is possible to modify this value. I created the notification with the following command.

Get-Sensor -Id 2153 | New-Trigger -Type Threshold -OnNotificationAction "Plantilla de prueba" -Latency 15 -Channel 0 -Condition Equals

Regardars,
Miguel Alvarado
________________________________
De: Miguel Alvarado <malvarado@unifica2.pe>
Enviado: martes, 15 de diciembre de 2020 09:52
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>; lordmilko/PrtgAPI <reply@reply.github.com>
Cc: Mention <mention@noreply.github.com>
Asunto: RE: [lordmilko/PrtgAPI] Question Sensor Factory (#192)

Hi Lormiko,

Thanks for you help.

Regards,
Miguel Alvarado
________________________________
De: lordmilko <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 21:30
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


Hi @malvarado611<https://github.com/malvarado611>,

So you are saying you want to have a sensor factory with three channels

  1.  The value of sensor 1's channel with index 0
  2.  The value of sensor 2's channel with index 0
  3.  The value of sensor 1's channel with index 0 with + the value of sensor 2's channel with index 0 all multiplied by 0.5

Information on how sensor factories can be created using PrtgAPI can be found on the wiki<https://github.com/lordmilko/PrtgAPI/wiki/Sensor-Factories>

In order to add the values of the two sensor channels together and multiply by 0.5 we will need to use the -SummaryExpression and -SummaryFinalizer parameters.

For the -SummaryExpression we wish to accumulate the total of all sensor channels; as such this parameter will simply be -SummaryExpression { "$acc + $expr" }

In order to multiply this value by 0.5 at the end, we would then specify -SummaryFinalizer { "($acc) * 0.5" }

The full result of this would be:

C:\ Get-Sensor *total* | New-Sensor -Factory "TEST FACTORY" {$_.Device} -sn "TOTAL CALLS SBC" -se { "$acc + $expr" } -sf { "($acc) * 0.5" } -DestinationId 2078 -WhatIf

#1:TOTAL CALLS SBC
(channel(2061,0) + channel(2092,0)) * 0.5
#2:dc-1
channel(2061,0)
#3:exch-1
channel(2092,0)

**Comment by lordmilko** [comment]
If you do

```powershell
Get-Sensor -Id 2153 | Get-Trigger
```

you will likely find that there are multiple sensors with `SubId` 1. One of which has a `ParentId` of 0 and is therefore an *inherited* trigger, the other has a `ParentId` of 2153. This is why PrtgAPI does not support modifying inherited triggers - within the context of a child object, "SubId 1" is ambiguous

**Comment by malvarado611** [comment]
Hi Lormiko,

Thanks for you help.

Regards,
Miguel Alvarado

________________________________
De: lordmilko <notifications@github.com>
Enviado: martes, 15 de diciembre de 2020 15:57
Para: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [lordmilko/PrtgAPI] Question Sensor Factory (#192)


If you do

Get-Sensor -Id 2153 | Get-Trigger

you will likely find that there are multiple sensors with SubId 1. One of which has a ParentId of 0 and is therefore an inherited trigger, the other has a ParentId of 2153. This is why PrtgAPI does not support modifying inherited triggers - within the context of a child object, "SubId 1" is ambiguous
