### ISSUE TITLE
Missing hidden Channels with Get-Channel

### ISSUE THREAD

**Issue by s3ri0us** [lordmilko/PrtgAPI#194]
Unfortunately, the hidden channels cannot be retrieved using the Get-Channel command. By adding showhide=1 in the query URL this would be possible.

**Comment by lordmilko** [comment]
Hi @s3ri0us,

This is currently a known limitation of PrtgAPI. I was not aware of the showhide=1 option however, and can see that this does appear to resolve the issue. As such I will look into incorporating this into a future release.

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @s3ri0us,

Please be advised PrtgAPI 0.9.15 has now been released which includes a fix for this issue

To update PrtgAPI, please run `Update-Module PrtgAPI` and reopen PowerShell

Regards,
lordmilko
