### ISSUE TITLE
Get-Device: Comments property on object replaces newlines with double-spaces

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#20]
**Expected**
```
> get-objectproperty -Object (get-device xxx) -Property Comments
System Analysis: Cisco Device ASA Cisco IOS
Other names: xxx
System Info: Cisco Adaptive Security Appliance Version 9.0(3)
Cisco Adaptive Security Appliance Version 9.0(3)
```

**Actual**
```
> (device xxx).comments
System Analysis: Cisco Device ASA Cisco IOS  Other names: xxx System Info: Cisco Adaptive Security Appliance Version 9.0(3) Cisco Adaptive Security Appliance Version 9.0(3)
```

**Need**
I want to be able to parse the comments field based on newline (and other regex criteria) into name-value pairs. While I can try parsing on double-space, it seems flimsier to me, and the output should be consistent across all forms of query.

**Comment by lordmilko** [comment]
Hi @JustinGrote,

On my system when I do

```powershell
get-probe new*|get-objectproperty comments
```

I get

```powershell
first
second
```

When I do

```powershell
get-probe new*|get-objectproperty comments -verbose
```

Copy the URL, and then do

```powershell
(invoke-webrequest "http://prtg.example.com/api/getobjectstatus.htm?id=1&name=comments&username=prtgadmin&passhash=12345678").content
```

I get

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<prtg>
<version>18.2.40.1683</version>
<result>first
second</result>
</prtg>
```

As such, this indicates to me your object's comments do not in fact include a newline, perhaps only including `\r` or `\n`?

Can you call `Invoke-WebRequest` as per above and advise what the resulting XML looks like?

Regards,
lordmilko

**Comment by JustinGrote** [comment]
The best example to use is a system that's been autodiscovered. PRTG drops a bunch of comment notes in there. I haven't manually entered them, just using what PRTG automatically entered.

Again, it's the difference between IWR/Get-ObjectProperty (which returns the info correctly), and the properties returned by (get-device xxx).comments. Get-Device is swapping out the newlines for spaces. I think the PRTGDevice object might be stripping or otherwise misformatting it.

Here's an example replacing any \r or \n with '***' so they are clearly called out. Notice that in the comments property, the newlines aren't returned at all, vs. get-objectproperty and iwr

**Correct**
```
> (Get-objectproperty -Object (get-device xxx) -prop Comments) -replace '\n|\r','***'
***System Analysis: Cisco Device ASA Cisco IOS ***Other names: xxx  ***System Info: Cisco Adaptive Security Appliance Version 9.0(3)***Cisco Adaptive Security Appliance Version 9.0(3)
```

**Correct**
```
> ([xml](iwr 'https://rims.allieddigital.net/api/getobjectstatus.htm?id=11033&name=comments&username=xxx&passhash=xxx')).prtg.result -replace '\r|\n','***'
***System Analysis: Cisco Device ASA Cisco IOS ***Other names: xxx  ***System Info: Cisco Adaptive Security Appliance Version 9.0(3)***Cisco Adaptive Security Appliance Version 9.0(3)
```

**NOT CORRECT**
```
> (get-device adsluslvfw*).comments -replace '\n|\r','****'
System Analysis: Cisco Device ASA Cisco IOS  Other names: xxx  System Info: Cisco Adaptive Security Appliance Version 9.0(3) Cisco Adaptive Security Appliance Version 9.0(3)
```

**Comment by lordmilko** [comment]
`(get-device adsluslvfw*).comments` uses the public API, which completely strips out newline characters. You will *never* get newlines using that API. You can confirm this manually by executing the URL returned by `get-device adsluslvfw* -Verbose` and inspecting the value of the comments field.

As such, the only way to get comments with newlines is to use `Get-ObjectProperty comments`

From your initial issue, my understanding was that `Get-ObjectProperty comments` was *not* returning the newlines. Are you able to confirm then that `Get-ObjectProperty comments` is working properly?

**Comment by JustinGrote** [comment]
OK so the issue is in the downstream api, I of course didn't think to check
that, just assumed the return values were the same :). I will review.

**Comment by JustinGrote** [comment]
Confirmed the issue is downstream, the table.xml (as well as table.json) is the culprit vs. get-objectproperty. Guess I'll work around it :). Thanks for your time! 👍

**Comment by JustinGrote** [comment]
Closing as unfixable
