### ISSUE TITLE
PRTG using lots of RAM when making use of powershell API and crashes

### ISSUE THREAD

**Issue by BMNETWORK23** [lordmilko/PrtgAPI#202]
Dear Developer,

I have a problem when using the PRTG API with Powershell. For certain actions is is going to eat RAM and I cannot get it down in any way I have tried. Finally the machine will eat all the RAM en become unusable. I could be due to my poor programming/scripting skills, but I wanted to reach out to you for ideas on how this happens or what I can do about it. 

For example (not made up) the script below will eat up the RAM.

foreach($sensor in $allsnmptrafficsensors)
{
    Write-Host $sensor.device
     Get-Sensor -id $sensor.id | Set-ObjectProperty -RawParameters @{monitorstate_ = 1} -Force
}

The array $allsnmptrafficsensors contains a couple of hundred (500/600) when I ran the script. After this script is going all the way up to 12GB of RAM. When the script is finished it will not reduce the consumed RAM. Finally the machine becomes unusable.

What I have tried and seen:
- Rebooting the PRTG Core service -> RAM returns to normal (4GB use)
- Clearing Powershell (Vars / Scripts / Stopping the IDE) -> RAM stays high

Do I need to clear or explicitly kill the "API Call"? 

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @BMNETWORK23,

Please see #198 for my analysis of this issue. In short, this is an issue with PRTG and is not something PrtgAPI can control. If the memory does not go down *eventually*, this indicates that the behavior you are seeing is in fact a *memory leak*, and so is even more definitely a bug in PRTG

Regards,
lordmilko
