### ISSUE TITLE
"Would-be-nice" Feature request: more flexible with URL string in Connect-PRTGServer

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#206]
The 'Connect-PRTGServer' call takes the URL for PRTG, but it does not like the trailing '/'.

It would be nice if you would strip the trailing '/'...
I know it's a small thing, but I bump into it all the time.
P.S. A cut/copy and paste from the browser will always append the '/'
whether it is highlighted or not.

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

This feature has been implemented and will be present in PrtgAPI 0.10 (no ETA at this stage)

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

Please be advised PrtgAPI 0.9.15 has now been released which includes a fix for this issue

To update PrtgAPI, please run `Update-Module PrtgAPI` and reopen PowerShell

Regards,
lordmilko
