### ISSUE TITLE
Enable Channels in Sensor Custom Advanced

### ISSUE THREAD

**Issue by jtfachini** [lordmilko/PrtgAPI#207]
Hello,

I'm creating a sensor using the "Advanced Custom" type, I need to use more than one channel for that sensor and add OIDs.

So far, I managed to create the sensor and add the OIDs to the channels, but I can't enable them.

This sensor demands that when creating, the channels are enabled, and cannot be performed after creation.

Which parameter can I use to enable the channels?

I am using the following parameters to create the sensor:

```
$table = @{ 
	"name_" ="teste snmp"
     "tags_" ="snmpcustomsensor"
     “Sensortype” = "snmpcustomadvanced”
	“channel1name_” = “Test1”
	“channel1oid_” = “1.3.6.1.1.2”
	“channel2name_”	 = “Test2”
	“channel2oid_” = “1.3.6.1.1.2”	
} 

$params = New-SensorParameters $table

Get-Device “local probe” | Add-Sensor $params
```

Names and OIDs used for testing purposes

Thanks!!!

**Comment by lordmilko** [comment]
Looking at the HTML of the page for adding this sensor type, I see this

```html
<input type="radio" class="hidden radio  GroupShowHide" name="usechannel2_" value="1" id="usechannel21">
```

From my testing the first channel will work automatically, while the second will only be enabled if you also specify `"usechannel2_" = 1`

Are you able to advise if the following works?

```powershell
$table = @{
    "name_" ="teste snmp"
    "tags_" ="snmpcustomsensor"
    “Sensortype" = "snmpcustomadvanced"
    “channel1name_" = “Test1"
    “channel1oid_" = “1.3.6.1.1.2"
    “channel2name_" = “Test2"
    "channel2oid_" = “1.3.6.1.1.2"	
    "usechannel2_" = 1
} 

$params = New-SensorParameters $table

Get-Device “local probe" | Add-Sensor $params
```

**Comment by jtfachini** [comment]
Hello,

Yes, it worked, thank you very much!
