### ISSUE TITLE
Question: Help with new sensor creation

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#21]
Hi LordMilko, I've been getting to grips with your API for a few months now and its reallly improved my day to day life at work 👍 

I am trying to create a new ping sensor to apply across many groups however am unable to quite understand how to set parameters for this. I understand that the native creation only supports service/http and exe. Is there a way of configuring more basic sensor sets to apply in bulk?

**Comment by lordmilko** [comment]
Hi @SamuelmAsh,

As noted under [Sensor Creation](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#sensor-creation), sensor types not natively supported by PrtgAPI can be created via [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters)

Sensor creation of arbitrary sensor types is a three step process

1. Identify the raw sensor type ID
2. Create a set of sensor parameters from a compatible device
3. Batch create the sensor on all desired devices

```powershell
C:\> Get-SensorType *ping*

Id             Name             Description
--             ----             -----------
cloudping      Cloud Ping       Monitors the Ping time to the target device from diffe
ping           Ping             Monitors connectivity using Ping
ptfpingjitter  Ping Jitter      Monitors the Statistical Jitter value for Pings to the
...
```
```powershell
# Create the parameters from the device with ID 1234,
# then create the sensor on every device
C:\> $params = Get-Device -Id 1234 | New-SensorParameters -RawType ping
C:\> Get-Device | Add-Sensor $params
```

Regards,
lordmilko
