### ISSUE TITLE
WMI Volume

### ISSUE THREAD

**Issue by nfrederickx** [lordmilko/PrtgAPI#211]
Hi,
I'm trying to figure out how I can add the wmi volume sensor and select which drives I'd like it to check.

This is as far as I got:
$params = $device | New-SensorParameters -rawtype wmivolume                                 
$device | Add-Sensor $params

But it just adds one drive. 
I'd like to select the drives that need to be added.

Like I would do manually:
![2021-03-30_13h32_37](https://user-images.githubusercontent.com/28628271/112982189-7c198c80-915c-11eb-91b0-457ad3a55f74.png)

**Comment by nfrederickx** [comment]
I actually figured it out.

In case anyone else wonders in the future:

$add = $device | Get-SensorTarget -RawType wmivolume | Out-GridView -OutputMode Multiple
$params.deviceidlist__check = $add
$device | Add-Sensor $params

**Comment by lordmilko** [comment]
Hi @nfrederickx,

The correct way to do this is to programmatically filter the targets found on the `Targets` property of the parameters object

For more information please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#targets-1)

Regards,
lordmilko
