### ISSUE TITLE
Get Device with Tag1, but exclude Tag2

### ISSUE THREAD

**Issue by schoenm1** [lordmilko/PrtgAPI#212]
I can get all Device with a specific Tag with PowerShell Integration.

```
PS C:\Users\micha.schoenenberger> $device = Get-Probe -id 13876 | Get-Device -Tag "Firewall-Service"
PS C:\Users\micha.schoenenberger> $device

Name                        Id     Status      Host            Sensors    Group          Probe
----                        --     ------      ----            -------    -----           -----
device1           20264  Up          10.63.240.17    15         Firewall Cluster Member   LAB
device2           20282  Up          10.63.240.18    15         Firewall Cluster Member   LAB
device3-test      20300  Up          192.168.254.10  17         Firewall Cluster          LAB
```

But i was not able to Get all Device with Tag "Firewall-Service", but not with Tag "Test".
I tried with your Integration and with Powershell integrated function as "-notmatch", "-notlike", "notcontains".

Is it possible to use like the direct PRTG API the "+" and "-" Operation for searching for a Tag that must be inclulded or is excluded.
In direct API I used for example: "+Firewall-Service" "-TEST". This request returns all Devices with Tag "Firewall-Service", but only if "Test" is not included.
("Firewall-Service" and "Test" would return any Device with Tag "Firewall-Service" OR "Test")

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @schoenm1,

The PRTG API will not allow you to filter for search criteria like "not contains" server side; as such, in order to achieve this you will need to
1. Retrieve all sensors that contain *at least* the "Firewall-Service" tag server side
2. Exclude all sensors from those results that *also* contain the "Test" tag client side

```powershell
Get-Probe -Id 103876 | Get-Device -Tag "Firewall-Service" | where Tags -notcontains Test
```

Regards,
lordmilko
