### ISSUE TITLE
When acknowledging a sensor, messages with a space will be omitted

### ISSUE THREAD

**Issue by stefanpetter** [lordmilko/PrtgAPI#213]
**Describe the bug**
We want to acknowledge sensors through an Azure function. The acknowledge message contains a TopDesk ticket/incident number, which has a space in it. I think the space does not get properly encoded (into %20). 

**Steps to reproduce**
*Put the relevant code from your application that caused the issue to happen in the code block below*

```powershell
#Does work:
$sensor | Acknowledge-Sensor -Message 'I2101-1337' -Forever

#Doesn't work:
$sensor | Acknowledge-Sensor -Message 'I2101 1337' -Forever
```

**Comment by lordmilko** [comment]
Hi @stefanpetter,

PrtgAPI typically encodes spaces as `+` except in contexts where PRTG requires they be encoded as `%20` instead. This is based on the behavior I've observed PRTG exhibit as I've reverse engineered it. You can see the exact API request that is executed by specifying the `-Verbose` parameter to `Acknowledge-Sensor`

I tried executing your command that doesn't work against my test API server (PRTG 21.1.66.1664+) and it appeared to work

![image](https://user-images.githubusercontent.com/6138789/115376051-b3d29c00-a211-11eb-8da0-450dabb2b298.png)

Are you able to advise
1. what the output of `$sensor | Acknowledge-Sensor -Message 'I2101 1337' -Forever -Verbose` is (minus your server name and authentication credentials)
2. What is the output of `Get-PrtgClient -Diagnostic`?

**Comment by stefanpetter** [comment]
Hi @lordmilko, thank you so much for the fast response!

Appearantly I was being too impatient. The first refresh in the browser did not show the message. The second refresh, it did.... 
<img width="218" alt="prtg" src="https://user-images.githubusercontent.com/57794508/115379956-5703c100-a1d2-11eb-9552-8888a1e3c1fa.png">

Apoligies for wasting your time.

**Comment by lordmilko** [comment]
Thanks @stefanpetter,

I can definitely appreciate this! PRTG is so slow at handling acknowledgements it takes 10 minutes to run my 4 integration tests for the `Acknowledge-Sensor` cmdlet to run! Even with a smattering of `Refresh-Object` calls it still takes forever. The same is also true for `Pause-Object`
