### ISSUE TITLE
Trying to clone sensors between PRTG servers

### ISSUE THREAD

**Issue by der-thodi** [lordmilko/PrtgAPI#224]
**What's going on?**
Hi, I am currently trying to copy/clone sensors (actually entire sensor trees) between  different PRTG servers (as part of a migration). I know this feature is planned and in progress (https://github.com/lordmilko/PrtgAPI/projects/1#card-8254572), but is there a workaround that works right now? I tried something along the lines of 

```
[... Connect old server ...]

$production_devices = new-object system.collections.arraylist
foreach ($device in Get-Group -Id 17988 | Get-Device) {
   $name = $device.Name
   $production_devices.Add(@{
        Name = $device.Name;
        Host = $device.Host;
        Sensors = ($device | Get-Sensor);
    })
}

[... Disconnect old server / Connect new server ...]

$group = Get-Group -Id 20663
foreach ($device in $production_devices) {
    $new_device = $group | Add-Device -Name $device["Name"] -Host ($device["Host"].ToLower() + ".<domain>")
    foreach ($sensor in $device["Sensors"]) {
        $new_sensor = $sensor | Clone-Object -DestinationId $new_device.Id
    }
}
```

This does not work, as the sensors being cloned seem to be taken from the new server (looked up by the ID on the new server?), not the old server. Sensors are created on the new server, but the types and parameters have nothing to do with the sensors on the old server.

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @der-thodi,

There is no current built in system in PRTG or PrtgAPI for achieving this; as such, I would say your best bet right now would be to [extend this sample script](https://blog.paessler.com/how-to-add-hundreds-of-devices-to-prtg) to process a CSV that not only contains groups and devices, but also the sensor types to add to those devices, which you can then generate and add via `New-SensorParameters` / `Add-Sensor`

Regards,
lordmilko
