### ISSUE TITLE
Import parameters by file

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#226]
Hello, I hope you are well.
A query, is it possible to load parameters by means of a txt or csv file for the consultations with the PRTG?

**Comment by lordmilko** [comment]
Hi @mafer0410,

When you say "load parameters", do you mean load the parameters that will be passed to a cmdlet?

**Comment by mafer0410** [comment]
Yes, by means of a csv or txt load the parameters that are needed to create
an object, for example, create 10 devices with the parameters of a file.

**Comment by lordmilko** [comment]
Hi @mafer0410,

There are several ways you can going about doing this. The most straight forward method is simply to write a CSV containing the information you wish to use, and then write a script that processes that information

An example of how you can do this can be found in [this blog article](https://blog.paessler.com/how-to-add-hundreds-of-devices-to-prtg)

**Comment by mafer0410** [comment]
okay,
I'm going to read the article, thank you very much for the information.
