### ISSUE TITLE
Migration of PRTG-environment

### ISSUE THREAD

**Issue by Kipjr** [lordmilko/PrtgAPI#229]
**What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?**
- We have a **core-server with a local probe** (source) and a cloud-based VM with PRTG core  (target) with multiple remote probes (on-premise) and we want to migrate all components (group, device, sensor and channel with the corresponding settings/parameters) from the source (local core, local probe) to the target environment (cloud core, remote probe on-premise)
- Currently this is done by connecting to the source environment and execute the following commands
  - ` Connect-PrtgServer -Server $sourcePRTG -Credential $credSource`
  - `$source = get-probe |where {$_.name -like "name of the source probe"} | get-prtgtree -options all`
  - `Disconnect-PrtgServer`
  - `Connect-PrtgServer -Server $targetPRTG -Credential $credTarget`
  -  The we loop over the `$source` object and create groups, devices and then we are stuck. 
     - We want to migrate specific group settings (credentials per specific group, schedules etc.)
     -  Creation of sensors is still cumbersome. It looks like it is required to create a `SensorFactoryDefinition `or `SensorParameters`. 

**Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?**
- It is not possible to do this in the GUI except for manually mirroring every group, device, sensor and channel with the corresponding settings/parameters

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [ x ] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [ x ] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
Hi @Kipjr,

PRTG nor PrtgAPI currently provide a mechanism for migrating objects between servers. You'll see from the [roadmap](https://github.com/lordmilko/PrtgAPI/projects/1) that implementing this functionality is something I'm working on (literally as I received notification of your message! :P) however there's still quite a large number of outstanding items that need to be resolved before this ships as a usable product.

If your new PRTG server doesn't actually have any config on it yet your best bet might be to simply copy the entire PRTG configuration over to the new server (simply copying `PRTG Configuration.dat` is fine, but I would recommend to copy the entire `C:\ProgramData\Paessler\PRTG Network Monitor` folder)

Regards,
lordmilko

**Comment by Kipjr** [comment]
The issue is that I dont have access to the target core-server machine, however I'm able to perform administrative tasks using prtgAPI. Is there any workaround using prtgAPI?

**Comment by lordmilko** [comment]
Unfortunately not at this time

**Comment by lordmilko** [comment]
If you're really *really* desperate you can roll your own migration system using PrtgAPI's tree model

By creating a [PrtgNodeWalker](https://github.com/lordmilko/PrtgAPI/wiki/Tree-Manipulation) like so

```powershell
using namespace PrtgAPI.Tree

$tree = Get-PrtgTree -Options All

class Applier : PrtgNodeWalker
{
    [void]VisitGroup([GroupNode]$node)
    {
        # Create the group from the $node.Value if it doesn't already exist

        foreach($child in $node.Children)
        {
            $this.Visit($child)
        }
    }

    [void]VisitDevice([DeviceNode]$node)
    {
        # Create the device from the $node.Value if it doesn't already exist
        Write-Host "Pretend we're creating a device here"

        foreach($child in $node.Children)
        {
            $this.Visit($child)
        }
    }

    [void]VisitSensor([SensorNode]$node)
    {
        Write-Host "Pretend we're checking this is a type of sensor we want to recreate here"

        $parameters = $node.Parent.Value | New-SensorParameters -rt $node.Value.Type.StringValue

        $parameters.Unlock()

        $properties = $node.Properties.Children.Value

        foreach($prop in $properties)
        {
            $parameters.($prop.Name) = $prop.Value
        }

        Write-Host "Pretend we're creating a sensor here"
    }
}

$applier = [Applier]::new()
$applier.Visit($tree)
```

you can augment this to add each node using `Add-Group` / `Add-Device` / `Add-Sensor` if the node hasn't been added already.

In order to run this script you'll want to first have imported PrtgAPI in your PowerShell session (otherwise PowerShell will complain that the types referenced within aren't loaded). While we don't know what parameters are *truly* required to recreate the sensor, we are assuming that the raw properties found on the sensor should be everything we need. PrtgAPI will provide the tree traversal framework for you, but at this time the rest will be all up to you
