### ISSUE TITLE
Geting Error for large Threshold (int32)

### ISSUE THREAD

**Issue by MrEuds** [lordmilko/PrtgAPI#230]
**Describe the bug**
I was trying to get the Trigger information from all Sensors that are not inherited. Then Get-Trigger threw an Error: 
```powershell
Get-Trigger : There was an error deserializing the object of type PrtgAPI.NotificationTriggerData. The value '5000000000' cannot be parsed as the type 'Int32'.
At line:2 char:14
+ Get-Sensor | Get-Trigger
+              ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-NotificationTrigger], SerializationException
    + FullyQualifiedErrorId : System.Runtime.Serialization.SerializationException,PrtgAPI.PowerShell.Cmdlets.GetNotificationTrigger
```
The problem is caused by a Notification Trigger of the Threshold Trigger type that is set to trigger when working set (Byte) channel is above 5000000000 for at least 300 seconds.

I think the problem will get solved when you change the NotificationTriggerDataTrigger class in \src\PrtgAPI\Objects\Models\NotificationTriggerData.cs because it is set to int:
```cs
[DataMember(Name = "threshold")]
[PropertyParameter(TriggerProperty.Threshold)]
int? Threshold { get; set; }
```

I think there was already a commit for that: "Change NotificationTrigger.Threshold from int? to double?"
Maybe this spot in the code above was just not changed and that's why the Error happens.

**Steps to reproduce**

You need to configure a Sensor with the Threshold Trigger type and give it a large Byte Threshold.
```powershell
$triggerSensors = Get-Sensor | Get-Trigger -Inherited $false

```

**What is the output of `Get-PrtgClient -Diagnostic`?**

```powershell
PSVersion      : 5.1.18362.1593
PSEdition      : Desktop
OS             : Microsoft Windows 10 Enterprise
PrtgAPIVersion : 0.9.16
Culture        : de-DE
CLRVersion     : .NET Framework 4.8 (528040)
PrtgVersion    : 21.3.69.1333
PrtgLanguage   : Unknown

```

**Comment by lordmilko** [comment]
Hi @MrEuds,

Great find! Thanks for the detailed analysis that made this super easy to fix :P You're exactly right, looks like I missed updating `NotificationTriggerData` in that specified commit.

I have pushed a new pre-release version of PrtgAPI which should include a fix for this issue; can you follow the [manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions and advise if this resolves the issue?

Regards,
lordmilko

**Comment by MrEuds** [comment]
Hi @lordmilko,

works like a charm now. Thanks for the quick response :D
