### ISSUE TITLE
Impossible to install PrtgApi

### ISSUE THREAD

**Issue by WilLabisoumaniac** [lordmilko/PrtgAPI#232]
Hi,

I tried to install the PrtgApi on Windows Server 2016 but i have this message :

PS E:\Apps\Custom Sensors\Api\PrtgAPI> Import-Module PrtgApi
Import-Module : The specified module 'PrtgApi' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module PrtgApi
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (PrtgApi:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 ****

I unzip all PrtgApi on this directory :  E:\Apps\Custom Sensors\Api\PrtgAPI and launch the command Import-Module witj PowerShell as Administrator.

Thanks.

Wilfrid

**Comment by lordmilko** [comment]
Hi @WilLabisoumaniac,

The issue is that you are *inside* the PrtgAPI folder

Instead of having
```
PS E:\Apps\Custom Sensors\Api\PrtgAPI> Import-Module PrtgAPI
```
you should have
```
PS E:\Apps\Custom Sensors\Api> Import-Module PrtgAPI
```

Regards,
lordmilko

**Comment by WilLabisoumaniac** [comment]
Hi LordMilko,

I tried on \Api : same result : i have only the directory PrtgApi on Api 's directory, that's right ?

Wilfrid

**Comment by WilLabisoumaniac** [comment]
With the absolute path, it's done !!! 
Thanks.

**Comment by lordmilko** [comment]
Are you able to advise what happens if you specify the absolute path?

```powershell
Import-Module "E:\Apps\Custom Sensors\Api\PrtgAPI"
```
If that does not work, can you please advise what the contents of the *PrtgAPI* folder is

**Comment by WilLabisoumaniac** [comment]
All works Many thanks :)
