### ISSUE TITLE
Get-SystemInformation: Deserializing the object of type `PrtgAPI.SysInfoData1[[PrtgAPI.DeviceProcessInfo`

### ISSUE THREAD

**Issue by Ash258** [lordmilko/PrtgAPI#237]
**Describe the bug**

For one of my ubuntu host PRTG cannot get proper system information. Instead of datetime it returns `Unavailable`

![image](https://user-images.githubusercontent.com/13260377/132813143-dd3eba47-1a18-41bc-9d27-1cd42f828d0d.png)

**Steps to reproduce**

There is no direct steps to reproduce, unless you know how to simulate the process to get unavailable data.
To reproduce it should be possible to use the json data at the bottom on some test device or just mock them.

```powershell
pwsh@7.2.0-preview.9> Get-SystemInfo -Id 2167
Get-SystemInfo: There was an error deserializing the object of type PrtgAPI.SysInfoData`1[[PrtgAPI.DeviceProcessInfo, PrtgAPI, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null]]. String 'Unavailable' was not recognized as a valid DateTime.
```

**What is the output of `Get-PrtgClient -Diagnostic`?**

```powershell
pwsh@7.2.0-preview.9> Get-PrtgClient -Diagnostic

PSVersion      : 7.2.0-preview.9
PSEdition      : Core
OS             : Microsoft Windows 10.0.19043
PrtgAPIVersion : 0.9.16
Culture        : en-GB
CLRVersion     : .NETCoreApp,Version=v6.0
PrtgVersion    : 21.3.69.1333
PrtgLanguage   : english.lng
```

**Additional context**

Clear json data:

```json
{
	"kind": "processes",
	"receivetime": "10-09-2021 06:56:18.128",
	"error": 0,
	"message": "OK",
	"data": [
		{
			"displayname": "systemd",
			"properties": {
				"processid": "1",
				"runstatus": "Runnable",
				"caption": "systemd",
				"creationdate": "Unavailable"
			}
		},
		{
			"displayname": "kthreadd",
			"properties": {
				"processid": "2",
				"runstatus": "Runnable",
				"caption": "kthreadd",
				"creationdate": "Unavailable"
			}
		}
	]
}

```

**Comment by lordmilko** [comment]
Hi @Ash258,

Please be advised I have pushed a new pre-release version of PrtgAPI which should have a fix for this issue. Please see the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) for information on running this version

Regards,
lordmilko
