### ISSUE TITLE
Difference value Interval between GUI and PRTGAPI.

### ISSUE THREAD

**Issue by marcelo-0511** [lordmilko/PrtgAPI#238]
Hello Lordmilko, once again I would like congratulate you about your work.

I just would like to know, why there is a difference in interval value between GUI and PRTG API:

In PRTG API:
![image](https://user-images.githubusercontent.com/67024069/132857197-6ea7883e-90af-49f8-971b-4383f2c9c820.png)

In GUI:
![image](https://user-images.githubusercontent.com/67024069/132857607-5e90d7ce-c5ca-47b2-b0fb-c566f894ccbb.png)

The logs shows foreach 5 minutes:
![image](https://user-images.githubusercontent.com/67024069/132858314-88d03d7b-1cc1-4851-b63a-c93ca4bf4544.png)

Obs. That is a log from a device/sensor inherited from this group.

If you can help me I will be happy. Thanks.

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

`Get-ObjectProperty` retrieves values that are defined on the *Settings* page of the object. The fact the settings page says the interval is only 60 seconds despite the fact in the UI the interval is shown as 5 minutes tells me that the value of 5 minutes is being *inherited* from the parent object, and that the value "60 seconds" is what you would see if went on the settings page and disabled interval inheritance for this object. `Get-ObjectProperty -Raw` gives you the raw properties contained in the HTML on the page, so in this sense you got what you asked for!

If you want to get the actual effective interval of an object, you should look at the `Interval` property of the `Group` object itself

```powershell
Get-Group -Id 153078 | select Interval
```

Regards,
lordmilko

**Comment by marcelo-0511** [comment]
@lordmilko 

You are right, a got the real interval.

Thanks for you help.
