### ISSUE TITLE
Assistance creating device params for wmi service 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#24]
Hi there, i am trying to create the parameters for a wmiservice sensor. Could you by any chance assist me with the formatting of this?

**Comment by lordmilko** [comment]
Hi @SamuelmAsh,

Did you have any troubles with the examples on the wiki?

* [Sensor Creation](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#sensor-creation-1)
* [Sensor Targets](https://github.com/lordmilko/PrtgAPI/wiki/Sensor-Targets#supported-types-1)

**Comment by SamuelmAsh** [comment]
Not trouble per se i just didnt quite understand how to extrapolate the info for new EXE sensors to other sensor type. I am creating the params at the moment and cant work out where the service name would be declared or what sensortype to use. Get-sensortarget doesnt seem to run against wmi service sensors. Or i am overlooking something very simple. I am being obliterated by hay fever today. It may well be that :)

**Comment by SamuelmAsh** [comment]
Oh i cracked it! sorry i was not explaining WMIService *sophos* only WMIService so i think get get-targets was not working. However when defining params as such 
```

$params = @{
Sensor             : Sensor 
Services           : swi_service
StartStopped       : False
NotifyStarted      : True
MonitorPerformance : False
SensorType         : WmiService
Priority           : 
InheritTriggers    : 
InheritInterval    : 
Interval           : 
IntervalErrorMode  : 
Name               : Service
Tags               : {wmiservicesensor, servicesensor}
}
```

It returns 

`add-sensor : Property 'Services' requires a value, however the value was null or empty.`

**Comment by lordmilko** [comment]
```powershell
PS C:\> New-SensorParameters WmiService

Services           :
StartStopped       : False
NotifyStarted      : True
MonitorPerformance : False
Source             :
SensorType         : WmiService
Priority           :
InheritTriggers    :
InheritInterval    :
Interval           :
IntervalErrorMode  :
Name               : Service
Tags               : {wmiservicesensor, servicesensor}
```

We can see from this output that the `WmiServiceSensorParameters` object returned by the `New-SensorParameters` object contains a `Services` property. We can populate this value by retrieving a `WmiServiceTarget` object via the `Get-SensorTarget` cmdlet

```powershell
C:\> $params = New-SensorParameters WmiService
C:\> $params.Services = Get-Device dc-1 | Get-SensorTarget WmiService *netlogon*
C:\> $params

Services           : {Netlogon}
StartStopped       : False
NotifyStarted      : True
MonitorPerformance : False
Source             :
SensorType         : WmiService
Priority           :
InheritTriggers    :
InheritInterval    :
Interval           :
IntervalErrorMode  :
Name               : Service
Tags               : {wmiservicesensor, servicesensor}
```

You can then apply these parameters to all desired devices

```powershell
Get-Device dc-1 | Add-Sensor $params
```

Alternatively, you can follow the approach documented on the [Sensor Targets](https://github.com/lordmilko/PrtgAPI/wiki/Sensor-Targets#supported-types-1) page (which *is* for WMI Service parameters) and do it all in one line

```powershell
C:\> Get-Device dc-1 | Get-SensorTarget wmiservice *netlogon* -Params | Add-Sensor
```

**Comment by SamuelmAsh** [comment]
Hi LordMilko,

Thank you for this additional guidance it was very helpful! 

Thanks for making my job oh so much easier :) 
Sam
