### ISSUE TITLE
Trying add sensors are getting following error

### ISSUE THREAD

**Issue by marcelo-0511** [lordmilko/PrtgAPI#244]
### Describe the bug

When I am trying add sensors i am getting following errors:
```
WARNING: 'Add-Sensor' timed out: The underlying connection was closed: The connection was closed unexpectedly. Retries remaining: 1
Add-Sensor : The underlying connection was closed: The connection was closed unexpectedly.
At C:\Users\adm.msantos\Desktop\01-Adicionar_SDWAN_FortiOS6.4.ps1:102 char:22
+ Get-Device -Id $ID | Add-Sensor $sdwan_state ; Start-Sleep -Seconds 1 ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Sensor], WebException
    + FullyQualifiedErrorId : System.Net.WebException,PrtgAPI.PowerShell.Cmdlets.AddSensor
```
![image](https://user-images.githubusercontent.com/67024069/137409271-bbb97004-365c-4992-9c41-3aeb22bc73ad.png)

![image](https://user-images.githubusercontent.com/67024069/137409306-80c63581-fbc1-400d-ab9f-27578a00f113.png)

### Steps to reproduce

```powershell
When I tried to add sensor.
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
Version    : 18.1.38.11958
RetryCount : 1
RetryDelay : 3
LogLevel   : Trace, Request

PSVersion      : 5.1.17763.1971
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Standard
PrtgAPIVersion : 0.9.16
Culture        : en-US
CLRVersion     : .NET Framework 4.7.2 (461814)
PrtgVersion    : 18.1.38.11958
PrtgLanguage   : brazilian.lng
```

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

The implication here is there's something wrong with your sensor parameters.

Can you do

```powershell
$sdwan_state
```

and provide the output?

Furthermore, if you add the `-Verbose` parameter to your invocation of `Add-Sensor`, are you able to provide the output? Please be sure to redact any sensitive information

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

Can you also provide the `-Verbose` log output as mentioned above?

In additon, what happens if you simply target a single specific interface? (change `-Target *` to something more specific)

Are you able to add snmplibrary sensors for other OIDLIBs?

**Comment by marcelo-0511** [comment]
Yes, there are print screens below:
![sdwan_01](https://user-images.githubusercontent.com/67024069/137416883-761e7f76-6731-4b33-9182-7d0e6dd157f8.png)
![sdwan_02](https://user-images.githubusercontent.com/67024069/137416886-534bd391-ba63-4248-84dd-582b6ea250c7.png)
![sdwan_03](https://user-images.githubusercontent.com/67024069/137416895-b964e7a2-6392-49fc-a6fc-4ff894c8ef95.png)

Yes, I am able to add sensors.

I will try to do with a especific interface.
