### ISSUE TITLE
I Would Like to execute a command reading a file, is it possible?

### ISSUE THREAD

**Issue by marcelo-0511** [lordmilko/PrtgAPI#247]
### What's going on?

I have a fortigate and i would like to read a configuration file and execute it with invoke-sshcommand, let show it for you:

I am reading the file string.txt
![image](https://user-images.githubusercontent.com/67024069/140005401-7640bbf5-547d-45a1-81e8-88d84f15e906.png)

And that is my script:
![image](https://user-images.githubusercontent.com/67024069/140004746-086f37d7-6ec8-4a11-aace-a3579d45840b.png)

When I try like this it doesn't work (I guess that is not respecting the lines in string)

When I try Like this it works:

![image](https://user-images.githubusercontent.com/67024069/140005422-a2f51145-68a7-445d-a500-f735f40d1908.png)

The diference is one way I read a file ando another way I create the string in the code.

Please, may you help me?

I Like so much your contribution with POSH-SSH, Thanks! ;)

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @marcelo-0511,

This repo is regarding PrtgAPI, which is a PowerShell library for interfacing with PRTG Network Monitor. Can you please advise what your request has to do with PrtgAPI?

**Comment by marcelo-0511** [comment]
Lordmilko, good morning

Sorry, I opened this case in the wrong Repo.

Please, forgive me.
