### ISSUE TITLE
Sensor Primarychannel  Property can not be used

### ISSUE THREAD

**Issue by JGlumanda** [lordmilko/PrtgAPI#249]
### What's going on?

Im not able to set a Primarychannel at a Sensor. It does not appear in Set-ChannelPropertys.

### Due Dilligance

- [x] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @JGlumanda,

The Primary Channel settings appear on the *Settings* tab of PRTG; therefore it is configured with `Set-ObjectProperty`

For more information on what properties are natively supported please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#overview)

**Comment by JGlumanda** [comment]
Im really sorry to ask again but can you give me an example bc it if I type in this: Get-Sensor -id 120 | Set-ObjectProperty -primarychannel "example", then it does not work. It just says that there is no Command named primarychannel.

**Comment by lordmilko** [comment]
Hi @JGlumanda,

Apologies, it looks like modifying the `-PrimaryChannel` is only available in the current *pre-release*. If you download PrtgAPI as per the [manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions you should find that your command above works as expected

**Comment by JGlumanda** [comment]
Thanks for the quick helpfull answere I will try it out :)
