### ISSUE TITLE
Getting a real disk name

### ISSUE THREAD

**Issue by carlbeechvuw** [lordmilko/PrtgAPI#250]
### What's going on?

I've managed to create SNMP disk sensors and that's working fine - however, I want to do some post / ongoing manipulation, but based on the actual name of the disk.
I can't guarentee that someone won't go in and change the name of the sensor, and I think its a little 'cludgy' to try to work out the name of a disk from the sensor name - I can see that PRTG has the 'real' disk / mountpoint under 'Disk free settings'...  can you let me know if there's a way to get the 'real' disk name given a specific sensor?

Hope that makes sense...

Many thanks

Carl.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @carlbeechvuw,

If you can see this information on the Settings page of the object in PRTG, you can retrieve this information via PrtgAPI using the `Get-ObjectProperty` cmdlet

```powershell
Get-Sensor -Id 1001 | Get-ObjectProperty -Raw
```

If the setting you see on the Settings page is in a read-only field, `Get-ObjectProperty` will not return this information (the next version of PrtgAPI will though) but as a workaround in the meantime you can still retrieve this field by inspecting its HTML and then executing `Get-ObjectProperty -RawProperty <name>`.

For example, on EXE/Script Advanced sensors there's a read-only div for the `exefilelabel`. If you do

```powershell
Get-Sensor -Id 1001 | Get-ObjectProperty -RawProperty exefilelabel
```

you would retrieve this value. Once you identify the property name to use from the HTML it should be pretty straight forward

**Comment by carlbeechvuw** [comment]
That is excellent - many thanks and much appreciated!
