### ISSUE TITLE
Extract paused sensors

### ISSUE THREAD

**Issue by SayotteMicrofix** [lordmilko/PrtgAPI#251]
### What's going on?

Hi there!

Sorry if this is something "simple", but I cannot figure how.
I need to make a CSV of all PAUSED sensors, but with the "few" commands I tried, I have gotten the content of the logs (get-objectlog), but get double, triple, etc, entry of the sensors, instead of just the single entry with the name, probe group device and message.

I just loaded the PowerShell module today, since I got the request NOW (lol), but I did try with get-object

Thank in advance for any help or pointer, Don't want to copy/paste over a 1000 entries 🤣 

Serge Ayotte

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @SayotteMicrofix,

You should be able to do this with

```powershell
Get-Sensor -Status Paused | Export-Csv C:\pausedsensors.csv -NoType
```

For more information on working with sensors please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Sensors#powershell)

Regards,
lordmilko

**Comment by SayotteMicrofix** [comment]
Good Friday to you!

Ho god… Feel so ashamed not to have even seen that command and tried it before opening the ticket!!! LOL!!!

Thank you and have a great weekend!


Serge Ayotte
Administrateur de Système System Administrator
***@***.***
***@***.***
Certifié ISO/IEC 27001:2013
www.equipemicrofix.com<http://www.equipemicrofix.com>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229
