### ISSUE TITLE
PRTG API v2

### ISSUE THREAD

**Issue by ArneBrucker** [lordmilko/PrtgAPI#254]
### What's going on?

Hey - once again many thanks for your work done with that Project.

Could you tell me about your project in regards of the new coming PRTG APIv2? 

Thank you

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
PrtgAPI does not currently support the PRTG APIv2; while Paessler provided me with early access to the new API over a year ago, significant areas of functionality supported by APIv1 are currently missing from APIv2; as such, it does not currently make sense to attempt to ship a version of PrtgAPI that limits the functionality you can perform if it detects your PRTG server is APIv2 compatible.
