### ISSUE TITLE
Set-ChannelProperty 

### ISSUE THREAD

**Issue by Maccamh** [lordmilko/PrtgAPI#257]
### Describe the bug

Hi LordMilko

When using the ChannelProperty commands I am unable to set the values for any field to blank

for example

I want cpuload sensor to have just Upper error limit of 100 and remove any existing upper warning lower warning or lower error limit.

here the below example - couldnt fin any details on how to do this in get-help or the below page

https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#set-1

below is example of what id like to do

$channels = Get-Sensor -Tags cpuloadsensor | Get-Channel Total

$channels | Set-ChannelProperty -UpperErrorLimit 100 -LowerWarningLimit **Blank** -UpperWarning Limit **Blank**

really hope you can help me.

Regards

### Steps to reproduce

```powershell
$channels = Get-Sensor -Tags cpuloadsensor | Get-Channel Total

$channels | Set-ChannelProperty -UpperErrorLimit 100 -LowerWarningLimit **Blank** -UpperWarning Limit **Blank**
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
Set-ChannelProperty : Missing an argument for parameter 'LowerWarningLimit'. Specify a parameter of type
'System.Double' and try again.
At line:1 char:33
+ $channels | Set-ChannelProperty -LowerWarningLimit
+                                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ChannelProperty], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,PrtgAPI.PowerShell.Cmdlets.SetChannelProperty
```

**Comment by lordmilko** [comment]
Hi @Maccamh,

To clear out these properties simply set them to `$null`

```powershell
$channels = Get-Sensor -Tags cpuloadsensor | Get-Channel Total

$channels | Set-ChannelProperty -UpperErrorLimit 100 -LowerWarningLimit $null -UpperWarning Limit $null
```

Regards,
lordmilko

**Comment by Maccamh** [comment]
Hi Lordmilko/Prtgapi

Really appreciate your quick response.

Really love the API !!

Regards
