### ISSUE TITLE
Change Inherited from Notificationtrigger

### ISSUE THREAD

**Issue by carsten0407** [lordmilko/PrtgAPI#267]
### What's going on?

Hi Lord,

is ist possible, to change the value  through the powershell API

**Inherit all triggers from parent objects and use the triggers defined above**
to
**Only use the triggers defined above**

![Noti](https://user-images.githubusercontent.com/64040868/152495413-a4d61244-3858-467b-80da-488fcaccb09e.png)

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @carsten0407,

Yes, you can do `Set-ObjectProperty -InheritTriggers`

For more information on what properties can be modified with PrtgAPI please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#overview)
