### ISSUE TITLE
SetObjectProperty only takes string

### ISSUE THREAD

**Issue by TheGfrerer** [lordmilko/PrtgAPI#269]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

I am currently inserting some settings of my sensors into their tags, because when retrieving a sensorobject, you cant access the "ExeParameters" for example. This works straight forward for me, but when these settings change i cant change them using the SetObjectProperty Method of the PRTGAPI client, because the method only takes a string and has  no other implementation. I know i can combine all my settings into a massive string, but i think this looks bad.

I thinks it would be nice to just have an implementation for changing the tag property by inserting a string[].

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

This has nothing to do with the UI.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
Hi @TheGfrerer,

All overloads of the `SetObjectProperty` method allow specifying an arbitrary `object` as the property value.

```powershell
public void SetObjectProperty(Either<IPrtgObject, int> objectOrId, ObjectProperty property, object value)
```
As such it should be possible to modify `ObjectProperty.Tags` by doing

```powershell
client.SetObjectProperty(1001, ObjectProperty.Tags, new[]{"first", "second"});
```
Are you able to provide more information about the issue you're having and the code you're trying to use?

**Comment by TheGfrerer** [comment]
Hello @lordmilko,

Thanks for the quick response!

Now i know what i did wrong. I was wrapping the PrtgClient in an interface for testing purposes, there i only implemented the method like `setObjectProperty(int id, ObjectProperty property, string newValue)`. Now i just made an overload to `setObjectProperty(int id, ObjectProperty property, string[] newValues)` in my interface.

Im sorry for wasting your time, this issue is obsolete.
