### ISSUE TITLE
Attempted to write progress on an uninitialized ProgressRecord

### ISSUE THREAD

**Issue by benclaussen1** [lordmilko/PrtgAPI#274]
### Describe the bug

While updating our deprecated DNS sensors, I was going to remove the old ones when I received this error:

``` powershell
PS C:\> $DNSSensors | ogv -pass | Remove-Object -Force
Remove-Object : Attempted to write progress on an uninitialized ProgressRecord. If this is a Release build, please
report this bug along with the cmdlet chain you tried to execute. To disable PrtgAPI Cmdlet Progress in the meantime
use Disable-PrtgProgress.
At line:1 char:27
+ $DNSSensors | ogv -pass | Remove-Object -Force
+                           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Object], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PrtgAPI.PowerShell.Cmdlets.RemoveObject
```

After running `Disable-PrtgProgress` my pipeline executed successfully.

### Steps to reproduce

```powershell
# This is specific to my actions which led to this error:

# Get a list of sensors
$DNSSensors = Get-Sensor -Filter (New-SearchFilter -Property Type -Operator Contains  -Value 'dns')

$DNSSensors | ogv -pass | Remove-Object -Force
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.19041.1320
PSEdition      : Desktop
OS             : Microsoft Windows 10 Enterprise
PrtgAPIVersion : 0.9.17
Culture        : en-US
CLRVersion     : 528372
PrtgVersion    : 22.1.74.1869
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment]
Hi @benclaussen1,

Please be advised a new pre-release version of PrtgAPI has now been released which should include a fix for this issue. Please see the [manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions for details on how to run this pre-release version.

This issue specifically only occurs when executing a pipeline in the form Variable -> Third Party Cmdlet PrtgAPI doesn't have special handling for (e.g. `Out-GridView`) -> PrtgAPI Cmdlet, so depending on how you use PowerShell this issue may or may not have a big impact in day to day usage of PrtgAPI

Regards,
lordmilko

**Comment by benclaussen1** [comment]
Awesome! Thanks for the prompt fix! I’m out of town until next week but will install when I return.

Out-GridView isn’t an everyday thing for me and PRTG. I submitted the issue since the error requested so ☺️

Have a good day!

Ben



Sent from a mobile device...




________________________________

**Comment by benclaussen1** [comment]
Tested this morning... Working perfectly for me. Thanks!
