### ISSUE TITLE
Wait longer for New-SensorParam

### ISSUE THREAD

**Issue by schoenm1** [lordmilko/PrtgAPI#277]
### What's going on?

I have some slow SNMP Devices.
When I try
`$temp = $device | New-SensorParameters -RawType snmplibrary -qt "*HUAWEI-SYS-MAN-MIB*" -Target *`
I will get an error

```$temp = $device | New-SensorParameters -RawType snmplibrary -qt "*HUAWEI-SYS-MAN-MIB*" -Target *
$temp = $device | New-SensorParameters -RawType snmplibrary -qt "*HUAWEI-SYS-MAN-MIB*" -Target *
New-SensorParameters : Failed to retrieve sensor information within a reasonable period of time. Check target device is accessible and that valid credentials have been supplied.
At line:1 char:19
\+ ... = $device | New-SensorParameters -RawType snmplibrary -qt "*HUAWEI-SY ...
    \+ CategoryInfo          : NotSpecified: (:) [New-SensorParameters], TimeoutException
    \+ FullyQualifiedErrorId : System.TimeoutException,PrtgAPI.PowerShell.Cmdlets.NewSensorParametersCommand```
```
I tried:
- include only really included oid in 'HUAWEI-SYS-MAN-MIB', but it will not help
- Set PRTGClient RetryCount=10 and RetryDelay=10

but with no success.
Is there a possiblity to wait longer for a reply?
If I do this in GUI, it will take a long time, but after the sensor will be displayed.
thanks

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
You can specify a `-Timeout` (in seconds)

**Comment by schoenm1** [comment]
Perfect!
