### ISSUE TITLE
AddNotificationTrigger TriggerParameters

### ISSUE THREAD

**Issue by matthewbjorklund** [lordmilko/PrtgAPI#278]
### The following information is wrong/spurious/misleading/missing. Fix it immediately!

Your current documentation in GITHub lists methods that are no longer in use with the most recent stable version. I am unable to find documentation on how to use TriggerParameters as a parameter for the AddNotificationTrigger method.  Below is your currently documentation.

Add
Brand new triggers can be defined on objects using the AddNotificationTrigger method. Due to the number of fields that can be defined on notification triggers across the variety of notification trigger types, in order to add (or modify) a notification trigger a TriggerParameters object must be defined.

PrtgAPI defines the following trigger parameter types for each type of notification trigger supported by PRTG

StateTriggerParameters
ChangeTriggerParameters
SpeedTriggerParameters
VolumeTriggerParameters
ThresholdTriggerParameters

### Link to the page/s containing/MISSING! this information

https://github.com/lordmilko/PrtgAPI/wiki/Notification-Triggers#add

**Comment by lordmilko** [comment]
Hi @matthewbjorklund,

Immediately following this are two examples of how `TriggerParameters` objects can be used with the `AddNotificationTrigger` method. Are you able to clarify which methods are no longer usable in the most recent version of PrtgAPI? I can see that one issue is that the `TriggerType` property should actually be called `Type` which I have corrected, however otherwise I don't have any other syntax errors when I copy and paste these examples into Visual Studio

**Comment by matthewbjorklund** [comment]
These are the methods:
StateTriggerParameters
ChangeTriggerParameters
SpeedTriggerParameters
VolumeTriggerParameters
ThresholdTriggerParameters

The addnotificationTriggers method only accepts the TriggerParameters object type.  It does not accept the mentioned object type from the code in your documentation listed below.

var parameters = new ThresholdTriggerParameters(2002, trigger)
{
    OnNotificationAction = action
};

//Add the trigger to the target object
var newTrigger = client.AddNotificationTrigger(parameters);

**Comment by lordmilko** [comment]
> These are the methods:

The documentation states

> PrtgAPI defines the following trigger parameter types for each type of notification trigger supported by PRTG

They are **types**, not **methods**. Each of these types derives from the base `TriggerParameters` type. This is implied both by the names of these types and the two examples which show these derived types being passed to the `AddNotificationTrigger` method. Are you able to advise whether you tried following the examples listed in the documentation?

**Comment by matthewbjorklund** [comment]
Oh wow my apologies. Yes, I do notice this now.  I am currently trying the statetrigger type from the documentation.  Thank you for the quick response.  I will close this issue out.

**Comment by matthewbjorklund** [comment]
After reviewing the documentation it is correctly written.  The different trigger types are clearly stated and how to craft the parameters to pass through the addnotificationtrigger method.
