### ISSUE TITLE
Add template to existing device

### ISSUE THREAD

**Issue by fab37100** [lordmilko/PrtgAPI#287]
### What's going on?

Hi

I was tried to add template on existing device with `Get-Device -Id XXXX | Set-ObjectProperty -RawProperty "devicetemplate_" -RawValue 'Template XXXX'` but it seems wouldn't work and I don't know if I use this cmdlet correctly.

I've tested the API PRTG and it's the same, I don't know if it's possible.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by kg7ski** [comment]
I had the same problem with groups.  Try this:
 get-device -id 12937 | Get-ObjectProperty -RawProperty devicetemplate
NSD-Switch.odt

$template = Get-DeviceTemplate "Generic Device (SNMP Enabled)"

 get-device -id 12937 | set-ObjectProperty -Rawparameters @{ devicetemplate_=1
devicetemplate__check=$template} -force -verbose

get-device -id 12937 | Get-ObjectProperty -RawProperty devicetemplate
Device Generic SNMP.odt

**Comment by fab37100** [comment]
Hi @kg7ski,

I used your feedback and it works very well, Thanks !
Now I cannot get all of templates of a device but it's another problem.

Thanks again !
