### ISSUE TITLE
Adding tags instead of overwriting tags.

### ISSUE THREAD

**Issue by ACASupport** [lordmilko/PrtgAPI#289]
### What's going on?

Can we add tags without overwriting the current tags ?

Consider the following code:
`$sensor | set-ObjectProperty -Tags 'test3'`

it overwrites all current tags, and replaces the tags with the a new tag (test3)

a sort of workaround is the following: 
`$sensor | set-ObjectProperty -Tags $($sensor.tags + 'test3')`

The problem however is, that $sensor.tags also has the inherited tags. so inherited tags get added as well.

Is there any way to know if a tag is inherited, without querying all devices before it ? or, is there an option to 'add' instead of overwrite?

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @ACASupport,

Originally the `-Tags` property was not supported (for exactly this reason), however at some point I discovered I had accidentally added support for it, and here we are.

If you do `$sensor | Get-ObjectProperty` you will be able to access the `Tags` and `ParentTags` separately
