### ISSUE TITLE
[QUESTION] Sensor parameters

### ISSUE THREAD

**Issue by Eazhi** [lordmilko/PrtgAPI#29]
Hi again @lordmilko!

I am currently trying to add a Windows Physical Disk I/O BETA `wmiphysicaldiskv2` on a device.
I would like to be able to choose the disk the sensor will monitor, I have tried to modify the parameter this way (this is before the creation of the sensor):
```C#
parameters["physicaldisk"] = "0 C:";
```
I also tried a few other combinations of the parameter name but none worked.
Is there a way to get the list of all the parameters that can be used for the sensor creation?
Or would you know how to modify this parameter ?

Thanks again,
Eazhi

**Comment by lordmilko** [comment]
Hi @Eazhi,

You need to specify a [Sensor Target](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#targets)

Please let me know if you have any further issues

Regards,
lordmilko

**Comment by Eazhi** [comment]
Thank you for being so responsive!
This solved my problem, but now I have another one.

I want to add a 'wmisqlserver2014' sensor to a device but cannot find how to modify "SQL Performance Counter" via the API.

Do you have any idea about how I could do that?

Thanks in advance,
Eazhi

**Comment by lordmilko** [comment]
Hi @Eazhi,

The SQL Performance Counter setting should correspond to the `sqlselection` property of the `DynamicSensorParameters`. If you press Ctrl+Shift+J in Chrome, you can use the selector to select one of the SQL Performance Counter radio buttons, and then observe the value that is used for each option

Are you able to confirm whether this resolves the issue?

Regards,
lordmilko

**Comment by Eazhi** [comment]
Yes, that worked!

Thank you,
Eazhi
