### ISSUE TITLE
Getting the acknowledged message

### ISSUE THREAD

**Issue by richardvdknaap** [lordmilko/PrtgAPI#293]
### What's going on?

Hi, 

When we acknowledge an alarm, we enter a corresponding message to the issue.
At the end of the month we generate a report for clear insights.

The only thing i'm missing is the message added when an alarm is acknowledged (see screenshot). Is there a way to get that?

![image](https://user-images.githubusercontent.com/33751610/178455940-ab880aa1-0546-4ff9-8fbc-efcffd5f72a5.png)

Regards,
Richard

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
The message you specify when you acknowledge a sensor is shown in the `Message` property of that object

```powershell
Get-Sensor -Id 1001 | select Id,Name,Message
```
