### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by Black-Pawn-C7** [lordmilko/PrtgAPI#296]
### What's going on?

Is there a possiblility to use SSO with PrtgAPI? 

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
PrtgAPI is simply a wrapper around the PRTG API. While PRTG may be able to integrate with Active Directory, to my knowledge there is no mechanism for PRTG API integrations to utilize SSO to magically automatically log you in in the same way that the VMware PowerCLI does.

To simplify authenticating with PrtgAPI I would recommend having a look at the [goprtg](https://github.com/lordmilko/PrtgAPI/wiki/Store-Credentials) cmdlets
