### ISSUE TITLE
Filter limits of a channel

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#297]
### What's going on?

Hello,
I am trying to get the limits/thresholds set on a channel and have it only show the non-empty values.

For example:
Get-device -Id 2097 | Get-sensor -Id 9038 | Get-Channel | where { $_.LimitsEnabled -eq "True"} | fl Name,*limit* | Format-Table -AutoSize | Out-String

And it shows me the following:
Name : Free Space
LimitsEnabled : True
UpperErrorLimit :
UpperWarningLimit :
LowerErrorLimit : 10
LowerWarningLimit : 25
ErrorLimitMessage :
WarningLimitMessage :

Is it possible to not display fields that don't have a value set?
Thanks in advance.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @mafer0410,

When you pass an object to the `Format-List` cmdlet, it transforms the input object into a *FormatEntryData* object, hence you should never pipe `Format-List` and `Format-Table` together as you are doing above. If you just want to select certain columns, use the `Select-Object` cmdlet

```powershell
blah | select Name,*limit* | Format-Table ...
```

In a table you would ostensibly have columns for each property. As such the simplest solution to me would simply be to do

```powershell
Get-device -Id 2097 | Get-sensor -Id 9038 | Get-Channel | where LimitsEnabled -eq "True" | select Name,*limit* | export-csv C:\list.csv -notype
```
Then you can filter the columns accordingly in Excel.

If you want to do some sort of manipulation in PowerShell, you'd need to get the PSObject of each `Channel` and then enumerate all of the limit related properties (the following is untested but more or less shows what to do)

```powershell
$channels = Get-device -Id 2097 | Get-sensor -Id 9038 | Get-Channel | where LimitsEnabled -eq $true

foreach($channel in $channels)
{
    $limitProps = $channel.psobject.properties|where name -like "*limit*"

    $result = New-Object PSObject
    $result | Add-Member Name $channel.Name

    foreach($prop in $limitProps)
    {
        if ($prop.Value -ne $null)
        {
            $result | Add-Member $prop.Name $prop.Value
        }
    }

    $result
}
```

**Comment by mafer0410** [comment]
Thanks!

**Comment by mafer0410** [comment]
I wanted to use the base script to get the values for the channels of various sensors but I get this error:
Add-Member : Cannot add a member with the name "LimitsEnabled" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.
