### ISSUE TITLE
Sensor data visualization

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#298]
### What's going on?

Hello,
I have the following script:

     # Name and ID of the device
     $dev_n=Get-Device -Id 2097 | select -expand Name
     $dev_i=Get-Device -Id 2097 | select -expand Id
    
     # Sensor data
     [array]$sen_n=$null
     $sen_n=Get-Device -Id 2097 | Get-Sensor | select -expand Name
     $sen_i=Get-Device -Id 2097 | Get-Sensor | select -expand Id
     $sen_s=Get-Device -Id 2097 | Get-Sensor | select -expand Status
    
     # Data visualization
     $General1 = @()
       $item = New-Object PSObject
       $item | Add-Member -type NoteProperty -Name 'Device' -Value $dev_n
       $item | Add-Member -type NoteProperty -Name 'Device ID' -Value $dev_i
       $item | Add-Member -type NoteProperty -Name 'Sensor' -Value $sen_n
     $General1 += $item | Format-Table -AutoSize | Out-String

     $General1

At the time of display it appears as follows:
![image](https://user-images.githubusercontent.com/51204835/185828179-52cc3d93-196a-43cc-b200-1fb35c125e98.png)

In the sensor column, the information appears between {}, is it related to the api or is it something specific to powershell? Is there a way for the prtg api to show it in a row each?

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
This is occurring because your `$sen_n` variable contains a list of elements. Also your logic is very redundant as you're retrieving the same set of sensors multiple times. Furthermore, all of the information you're retrieving is already present on `Sensor` objects by default!

As such you really just need to do `Get-Device -Id 2097 | Get-Sensor | select Name,ParentId,Device,Status`

**Comment by mafer0410** [comment]
I understand, but what I want is to join information from two different queries.

for instance:

$a= Get-Device -Id 2097 | Select Name,Id
$b = Get-Device -Id 2097 | Get-Sensor | select Name,Id,Status

$a , $b

and it shows me the following:

name id
---- --
calendar.rolosa.com 2097
Ping 8954
CPULoad 9036
Disk Free: / 9038
Memory: Physical memory 9044
Memory: Swap space 9045
Memory: Virtual memory 9046
(001) Lo Traffic 9178
