### ISSUE TITLE
Show full group path / breadcrumb

### ISSUE THREAD

**Issue by pbundschuh** [lordmilko/PrtgAPI#299]
### What's going on?

Hi.
Just made some tests with Powershell cmdlets using this simple code:

```
$sensors_down = get-sensor -status Down | sort-object -Property Probe
foreach ($sensor in $sensors_down){
	Write-Host $sensor.group
	Write-Host $sensor.device
	Write-Host $sensor.name
	Write-Host $sensor.probe
}
```
Works great and shows me all sensors in down state. But how can I display the full "breadcrumb"-path of the device?
I have e.g. several groups "Probe Customer A => Headquater => Network => Switches" and within this group my device.
Currently, only the last group (in this example "Switches") is shown.

Regards
Philipp

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
To do this you would need to recurse the entire object hierarchy by continuously doing `Get-Object -Id $current.ParentId`.

```powershell
function DisplayPath($current)
{
    if($current.ParentId -ne -1000)
    {
        $parent = Get-Object -Id $current.ParentId

        DisplayPath $parent

        Write-Host " => " -NoNewline
    }

    Write-Host "$current" -NoNewline
}

$sensors = Get-Sensor -Id 1001

foreach($sensor in $sensors)
{
    DisplayPath $sensor

    # Now write the rest of the sensor details...
}
```
