### ISSUE TITLE
Unit of channel

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#300]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

Hello,
I would like to know if it is possible with the command:
Get-Sensor -Count 1 | Get-Channel | fl *limit*
it shows the unit of each value?

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

I still don't know if it is possible to do it, since it would be useful to show the value and the unit to which it belongs.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
```powershell
Get-Sensor -Count 1 | Get-Channel | select *limit*,Unit
```
