### ISSUE TITLE
Ability to Remove Sensors/Devices/Groups?

### ISSUE THREAD

**Issue by technical-cory** [lordmilko/PrtgAPI#301]
### What's going on?

Do we have the ability to delete/remove objects with the PrtgAPI? I searched through the Wiki but couldn't find anywhere that mentioned it.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by technical-cory** [comment]
Just a note - I used Show-Command and filtered to PrtgAPI to find Remove-Object. This works perfectly. May be something to document in the Wiki if it isn't already there.

**Comment by technical-cory** [comment]
Just a note - I used Show-Command and filtered to PrtgAPI to find Remove-Object. This works perfectly. May be something to document in the Wiki if it isn't already there.

**Comment by Jackworley417** [comment]
Adding/Removing objects can cause issues when using the PRTG API, because of the complicated natural so its recommended to use the web interface but you can do it! Be sure to delete everything referenced with the object.

"/api/deleteobject.htm?id=objectid&approve=1"

**Comment by lordmilko** [comment]
https://github.com/lordmilko/PrtgAPI/wiki/Object-Organization
