### ISSUE TITLE
Getting Syslog Messages/Log

### ISSUE THREAD

**Issue by xasz** [lordmilko/PrtgAPI#304]
### What's going on?

I'am trying to get the messages from the syslog sensor.
In the UI, there is a special tab in a syslog sensor, which is not there on very sensor:
![image](https://user-images.githubusercontent.com/1305196/188174415-a0f8cee4-08ea-4fc6-8f78-b5fe6f3f0023.png)

I did not figure how if there is possible way to retrieve this informaion via your powershell module.

Thanks for your time and effort,

xasz

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
I've never seen this tab before; I believe in English this says "News"? I don't have access to PRTG at the moment, are you able to provide a screenshot of the content normally displayed on this tab?

**Comment by xasz** [comment]
This Tab only appears on a Syslog Sensor as far as i can tell.
I think i english the tab probably says "Messages" and contains the syslog messages which are received by the sensor syslog server:
![image](https://user-images.githubusercontent.com/1305196/188445233-dfea0f0e-83e6-4d37-a7eb-05429ffc6d8e.png)
I have now idea if that helps, but this is the "href" of the tab: /controls/sensormessages.htm?id=156345&udptype=syslog

**Comment by lordmilko** [comment]
Thanks @xasz,

Based on this I would say unfortunately it is not possible to retrieve this information using PrtgAPI

**Comment by xasz** [comment]
@lordmilko would be to perfect. I will give it a try to the prtg api by myself.
If i find something, i will post it here.
Thank you.
