### ISSUE TITLE
PowerShell - ShowTree and Export

### ISSUE THREAD

**Issue by SMB123** [lordmilko/PrtgAPI#307]
### What's going on?

Hi lordmilko,

I have created a tree using 'Get-PrtgTree -Options All' but I can't seem to get the 'ShowTree' command to work. I've tried several variations with no success on specifying which tree to show. Also, is there currently a way to export a tree via PowerShell? I didn't see anything on this in the wiki and thought I would ask while here. Conversely, how would one import a tree on a new PRTG instance? Thanks for all of your amazing work with this!

![image](https://user-images.githubusercontent.com/56882343/195695288-19927949-042b-4b97-9b18-bd4016ddbd23.png)

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @SMB123,

In the screenshot above, you aren't specifying a tree to show

```powershell
Get-PrtgTree -Options All | Show-PrtgTree
```

As noted on the wiki, the PrtgAPI Tree API is currently a work in progress. Importing trees into other PRTG servers is not currently supported
