### ISSUE TITLE
get-device -id 12312 | get-sensor -tag pingsensor | Get-NotificationTrig ...

### ISSUE THREAD

**Issue by carsten0407** [lordmilko/PrtgAPI#308]
### What's going on?

Hi Lord,

since yesterday we can no longer access the trigger notification via API with a Read/Write user (no admin-user)
We updated yesterday from version 22.1.75.1588+ to version 22.3.79.2108+.

This query still works on our other two core servers (version 22.1.75.1588+)

get-device -id 12312 | get-sensor -tag pingsensor | Get NotificationTrig...

Get-NotificationTrigger : Response status code does not indicate success: 403 (Forbidden).
At line:1 char:61
+ get-device -id $tempfound.id | get-sensor -tag pingsensor | Get NotificationTrig...
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : NotSpecified: (:) [Get-NotificationTrigger], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,PrtgAPI.PowerShell.Cmdlets.GetNotificationTrigger

thx

Carsten

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
PrtgAPI needs to execute an API request against `/controls/objectdata.htm?id=810` (which retrieves the web server options) to determine whether your PRTG server is using English or not; if not, it uses a slower code path (that executes many more API calls) in order to be compatible with non-English versions of PRTG

If this was working previously, it would seem that PRTG now restricts access to the web server options to admin users only. I can confirm that retrieving notification triggers still works when requesting as an admin user.

I can potentially look into modifying PrtgAPI to assume the server is *not* using English (and therefore default to taking the slower code path) when not using an admin user, however in the meantime to work around this  you will need to use an admin user

**Comment by lordmilko** [comment]
Hi @carsten0407,

I have pushed a commit that I believe should resolve this issue. Can you please follow the [manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions and advise whether you're able to retrieve notification triggers as a non-admin user using PrtgAPI 0.9.18-preview.7?

**Comment by carsten0407** [comment]
Hi LordMilko,

it works with the new PrtgAPI 0.9.18-preview.7?
No error message anymore

Thanx


Mit freundlichen Grüßen / best regards

i. A. Carsten Trautmann

Senior System Engineer
Operation Center
IT-Service
[http://support.it.konicaminolta.de/signatures/KM_LOGO.jpg]
Konica Minolta Business Solutions Deutschland GmbH
Mittlerer Pfad 1, 70499 Stuttgart, Germany
Phone:
+49 (711) 1385 - 131<tel:+497111385131>
Fax:
+49 (711) 1385 - 222
Mail:
***@***.******@***.***>
Web:
www.konicaminolta.de<http://www.konicaminolta.de>
District Court / Amtsgericht: Hannover, HRB 61209
Management / Geschäftsführer:
Joerg Hartmann & Jiro Tanaka
Aufsichtsratsvorsitzender: Jens Venrath
Informationen über die Verarbeitung Ihrer personenbezogenen Daten durch uns können Sie unter https://www.konicaminolta.de/de/business-solutions/meta/dseg.html einsehen.

[http://support.it.konicaminolta.de/signatures/emailPrinzip.jpg]

Von: lordmilko ***@***.***>
Gesendet: Samstag, 15. Oktober 2022 16:26
An: lordmilko/PrtgAPI ***@***.***>
Cc: Trautmann, Carsten ***@***.***>; Mention ***@***.***>
Betreff: Re: [lordmilko/PrtgAPI] get-device -id 12312 | get-sensor -tag pingsensor | Get-NotificationTrig ... (Issue #308)


[EXTERNAL E-MAIL] Use caution when following links or opening attachments.

Hi @carsten0407<https://github.com/carsten0407>,

I have pushed a commit that I believe should resolve this issue. Can you please follow the manual<https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual> installation instructions and advise whether you're able to retrieve notification triggers as a non-admin user using PrtgAPI 0.9.18-preview.7?
