### ISSUE TITLE
Clone-Object Error

### ISSUE THREAD

**Issue by oretom** [lordmilko/PrtgAPI#309]
### Describe the bug

I have an Issue using Clone-Object:
Clone-Object : PRTG was unable to complete the request. The server responded with the following error: The object is currently not valid. Try again later.
It works for the first one or two items and then I get the error above.

### Steps to reproduce

```powershell
My code looks like this:
$newDevice = Get-Device -Id $SourceDevice | Clone-Object -DestinationId $GroupID
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.17763.2931
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Datacenter
PrtgAPIVersion : 0.9.17
Culture        : de-AT
CLRVersion     : .NET Framework 4.7.2 (461814)
PrtgVersion    : 22.3.79.2108
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment]
Hi @oretom,

I tested against 22.3.79.2108 and was successfully able to clone a device in this way

Are you able to advise

* How many sensors you have in your PRTG installation?
* What the output of doing ` Get-Device -Id $SourceDevice | Clone-Object -DestinationId $GroupID -Verbose` is?

When providing the verbose output, please obscure any sensitive details such as your company name, username and passhash

**Comment by oretom** [comment]
Hi

16000 active sensors.
I have added the -Verbose switch and the script ran through with no error.

regards
oretom

**Comment by lordmilko** [comment]
This indicates to me that at the time you attempted to clone the object previously, PRTG timed out. Normally PrtgAPI knows how to deal with PRTG timing out, however it sounds like PRTG timed out in a way different from normal, so I need to see the output when you specify -Verbose one time when it does time out, which unfortunately could make things a bit tricky

**Comment by mxwi** [comment]
same here:

```
PS C:\Users\wdx> Get-Device server1 | Clone-Object -SourceId 81082 -Resume -SkipParent -Verbose
AUSFÜHRLICH: Ausführen des Vorgangs "Copy-Object" für das Ziel "'Internet DNS' (ID: 81082), Destination: 'Server1' (ID: 77671)".
AUSFÜHRLICH: Copy-Object: Synchronously executing request https://prtg.de/api/duplicateobject.htm?id=81082&name=Internet+DNS&targetid=77671&username=aa&passhash=11
Clone-Object : PRTG was unable to complete the request. The server responded with the following error: The object is currently not valid. Try again later.
In Zeile:1 Zeichen:24
+ ... server1 | Clone-Object -SourceId 81082 -Resume -SkipParent -Verbose ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Copy-Object], PrtgRequestException
    + FullyQualifiedErrorId : PrtgRequestException,PrtgAPI.PowerShell.Cmdlets.CloneObject
```

**Comment by lordmilko** [comment]
I have found a potential issue that may be causing this. Can you please try PrtgAPI 0.9.19-preview.1 via the [Manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) download instructions?

**Comment by mxwi** [comment]
Hi, looks pretty good to me.

Thanks!

**Comment by bajayb4u** [comment]
Hi @lordmilko, I am trying clone-object and running into same error. Where can I download PrtgAPI 0.9.19-preview.1 version from. It seems the latest build link is no longer valid. 

Thank you!

**Comment by squintfox** [comment]
I had this same problem and using the latest build version solved it for me as well.

**Comment by Maxell0089** [comment]
Hi have the same error : 

VERBOSE: Performing the operation "Copy-Object" on target "'Template Serveur [Windows]' (ID: 45327), Destination: 36316".                                                                                                                    VERBOSE: Copy-Object: Synchronously executing request https://******/api/duplicateobject.htm?id=45327&name=csvr-app01w-3&targetid=36316&host=csvr-app01w-3&username=PRTGApiCall&passhash=*********

Clone-Object : PRTG was unable to complete the request. The server responded with the following error: The object is currently not valid. Try again later.                                                                                   At Clone_device.ps1:100 char:41                                                                                                                                              + ... -Id 45327 | Clone-Object -DestinationId $GroupeID -host $DeviceHost   ...                                                                                                                                                              +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.9.18     PrtgAPI                             {Get-Channel, Get-Device, Get-DeviceTemplate, Get-Group...}

**Comment by lordmilko** [comment]
Hi @Maxell0089,

Can you try with the [latest build](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.zip)?
