### ISSUE TITLE
GetChannels not showing all channels for a "SQL 2016 Buffer Manager" sensor

### ISSUE THREAD

**Issue by quentin-dev** [lordmilko/PrtgAPI#31]
Hello there,

When I list all of the channels on a "SQL 2016 Buffer Manager" sensor, it lists only 
``` Buffer cache hit ratio``` when instead, it should list ```Buffer cache hit ratio``` , ```Database pages```, and  ```Page life expectancy``` .

Do you know if I can do anything to solve this problem ?
If not, do you have an idea on how to go about solving it ?
I have checked in PRTG that those 3 channels do exist if I try to create a trigger on said sensor.

Thanks in advance,

**Comment by lordmilko** [comment]
Hi @quentin-dev,

I created a WMI SQL Server 2016 sensor and was able to see all three channels in the response from `GetChannels`

If you copy and paste the URL

```
http://<server>/api/table.xml?content=channels&columns=lastvalue,objid,name&count=*&id=<id>&username=<username>&password=<password>
```

where `<server>` is your server, `<id>` is the ID of the sensor, `<username>` is your username and `<password>` is your password into your address bar and inspect the table.xml file that is downloaded, does it contain the missing channels?

If everything is working properly you should have a response like this

```xml
<?xml version="1.0" encoding="UTF-8"?>
<channels listend="1" totalcount="0">
<prtg-version>17.4.33.3283</prtg-version>
<item>
    <objid>-4</objid>
    <objid_raw>*000000004</objid_raw>
    <name>Downtime</name>
</item>
<item>
    <lastvalue>100 %</lastvalue>
    <lastvalue_raw>100.0000</lastvalue_raw>
    <objid>6</objid>
    <objid_raw>0000000006</objid_raw>
    <name>Buffer cache hit ratio</name>
</item>
<item>
    <lastvalue>42,852 #</lastvalue>
    <lastvalue_raw>42852.0000</lastvalue_raw>
    <objid>20</objid>
    <objid_raw>0000000020</objid_raw>
    <name>Page life expectancy</name>
</item>
<item>
    <lastvalue>100,518 #</lastvalue>
    <lastvalue_raw>100518.0000</lastvalue_raw>
    <objid>7</objid>
    <objid_raw>0000000007</objid_raw>
    <name>Database pages</name>
</item>
</channels>
```

Finally, can you check the settings of the missing channels and confirm the value of their "Table Rendering" settings? Channels that are set to Hide from Tables are excluded by PRTG in API requests

Regards,
lordmilko

**Comment by quentin-dev** [comment]
Hello again,

Here is the response I got from the url :
`<?xml version="1.0" encoding="ISO-8859-1"?>
<channels listend="1" totalcount="0">
<prtg-version>18.3.42.1748</prtg-version>
<item>
<objid>-4</objid>
<objid_raw>*000000004</objid_raw>
<name>Downtime</name>
</item>
<item>
<lastvalue>100 %</lastvalue>
<lastvalue_raw>100.0000</lastvalue_raw>
<objid>6</objid>
<objid_raw>0000000006</objid_raw>
<name>Buffer cache hit ratio</name>
</item>
<item>
<lastvalue>378,245 #</lastvalue>
<lastvalue_raw>378245.0000</lastvalue_raw>
<objid>20</objid>
<objid_raw>0000000020</objid_raw>
<name>Page life expectancy</name>
</item>
<item>
<lastvalue>731,748 #</lastvalue>
<lastvalue_raw>731748.0000</lastvalue_raw>
<objid>7</objid>
<objid_raw>0000000007</objid_raw>
<name>Database pages</name>
</item>
</channels>`

As you can see, the output is correct.
Furthermore, I checked the channel settings and they are all set to ```Show in Tables```.

Any ideas on what might be causing it ?

Thanks a lot,
Quentin

**Comment by lordmilko** [comment]
Can you please show me the C# code that you've written?

**Comment by quentin-dev** [comment]
```C#
foreach (var c in client.GetChannels(sensor.Id))
                {
                    Console.WriteLine(c.Name);
                }
```

**Comment by lordmilko** [comment]
Are you using PrtgAPI 0.8.6?

**Comment by quentin-dev** [comment]
Yep, from NuGet

**Comment by lordmilko** [comment]
Can you potentially [download the source](https://github.com/lordmilko/PrtgAPI/archive/master.zip), create a quick test solution, add the PrtgAPI.csproj project into your solution, then set a breakpoint [here](https://github.com/lordmilko/PrtgAPI/blob/master/PrtgAPI/Request/PrtgClient.Generated.cs#L37)?

When you step, you'll get the XML that was returned from the request you executed manually. Can you confirm it contains all the channels, then potentially continue stepping through the GetChannelsInternal method and see at what point the channels disappear?

**Comment by quentin-dev** [comment]
I just created a simple solution with the the exact same code as mentioned above, but I specified the exact sensor ID, to see only the channels for that one sensor, and it worked fine.

Is there anything I could be doing that messes with GetChannels ?

**Comment by lordmilko** [comment]
In your code

```c#
foreach (var c in client.GetChannels(sensor.Id))
                {
                    Console.WriteLine(c.Name);
                }
```
Are you able to confirm the ID of the sensor on that sensor object exactly matches the ID you manually specified? The implication here is that you retrieved a bunch of buffer manager sensors and are now looping through them; by default, buffer manager sensors only include the `Buffer cache hit ratio` channel, so potentially one of the sensors you're querying does not have all the other channels

In your original solution, can you add a LogVerbose event handler to intercept the request that was executed to retrieve the channels

```c#
client.LogVerbose += (s, e) =>
            {
                Console.WriteLine(e.Message);
            };
```

We want to confirm that the URL that was executed exactly matches the one you executed manually, and is targeting the same sensor ID

Failing this, can you potentially remove the reference to PrtgAPI from your original solution, add PrtgAPI.csproj as a project in the solution and then add a reference to it, and then step through GetChannels to see at what point the channels disappear?

**Comment by quentin-dev** [comment]
Good morning,

At first I thought that the glitch might be coming from the `foreach` so I changed it a bit to this:
```C#
var Channels = client.GetChannels(sensor.Id);
foreach (var c in Channels)
{
            Console.WriteLine("Sen ID : {0} - Channel Name : {1}", sensor.Id, c.Name);
}
```

I had to further mess around with my code a bit to implement what you said, but this is the response I got when I pasted the request url into a browser : 
```xml <?xml version="1.0" encoding="ISO-8859-1"?>
<channels listend="1" totalcount="0">
<prtg-version>18.3.42.1748</prtg-version>
<item>
<objid>-4</objid>
<objid_raw>*000000004</objid_raw>
<name>Downtime</name>
</item>
<item>
<lastvalue>0 %</lastvalue>
<lastvalue_raw>0.0000</lastvalue_raw>
<objid>6</objid>
<objid_raw>0000000006</objid_raw>
<name>Buffer cache hit ratio</name>
</item>
<item>
<lastvalue>378,245 #</lastvalue>
<lastvalue_raw>378245.0000</lastvalue_raw>
<objid>20</objid>
<objid_raw>0000000020</objid_raw>
<name>Page life expectancy</name>
</item>
<item>
<lastvalue>731,394 #</lastvalue>
<lastvalue_raw>731394.0000</lastvalue_raw>
<objid>7</objid>
<objid_raw>0000000007</objid_raw>
<name>Database pages</name>
</item>
</channels>
```

But I have confirmed that the sensor is indeed the same one in both cases.

I'm now going to try your last suggestion, I'll update this issue as soon as I can

> Failing this, can you potentially remove the reference to PrtgAPI from your original solution, add PrtgAPI.csproj as a project in the solution and then add a reference to it, and then step through GetChannels to see at what point the channels disappear?

**Comment by quentin-dev** [comment]
I am having a lot of issues with PrtgAPI.csproj as it is not targeting the same version of the .Net framework as my solution. Furthermore I cannot get it to add it to my solution via a using, although I have added it as a reference beforehand. What should I do ?

**Comment by lordmilko** [comment]
What version of .NET are you using in your solution?

**Comment by lordmilko** [comment]
You can upgrade the PrtgAPI.csproj project by opening PrtgAPI.sln, right clicking the PrtgAPI project in Visual Studio -> Properties and then upgrading it on the Application tab

The most direct approach to figure out what's going on is to do a quick debug as mentioned above and confirm that the response returned from .NET is the same as the response you get in your web browser. Stepping back a bit however, the fact the request worked in a new solution and didn't work in your existing one suggests there is something different about your current solution that is either affecting .NET or PrtgAPI, so it's simply a matter of identifying what this is

A great test we can do is to execute the following, identical code, in your current solution vs a new solution

```c#
var newClient = new PrtgClient(server, username, password);
var channels = newClient.GetChannels(sensorId);
```
Do not re-use any existing clients, any existing objects, variables, anything - simply hardcode in the server, username, password and sensor ID and confirm whether you get the same results. If there's a difference, what happens if you move these two lines to the very beginning of your project, making them the first two lines that are called? Do you get the same response then?

Furthermore, what type of project is the main project you're working on. It appears it may be a simple Console application. Is that correct?

**Comment by quentin-dev** [comment]
Yes it is a console application. But the last xml response I mentioned comes from my initial solution, where I am having the issue. So the request goes out and the right response comes in but for some reason only the first element is parsed ??

**Comment by lordmilko** [comment]
What do you mean the first element parsed is "??"

You said the last XML response you provided came from your *web browser*, after pasting in the *URL from your initial solution*. Therefore we now need to see what happens internally when your solution executes the request itself, as well as what happens when you execute the code as mentioned above

**Comment by quentin-dev** [comment]
Alright so at the beginning of my main function right after declaring the client, I called 

> var channels = newClient.GetChannels(sensorId);

And it does have all 3 channels 
![image](https://user-images.githubusercontent.com/20909347/43771633-25cb3b28-9a40-11e8-99aa-3022fe7a447f.png)

**Comment by quentin-dev** [comment]
Might the issue be due to the fact that I call GetChannels right after creating the sensor ?
Maybe the sensor hasn't had time to initialize everything ?

**Comment by lordmilko** [comment]
Hang on, are you saying you're *creating* a sensor with the `AddSensor` method and then trying to retrieve the channels of it?

As mentioned above

> by default, buffer manager sensors only include the Buffer cache hit ratio channel

If you create the sensor manually in the PRTG UI, you'll find that the second and third channels only appear after the sensor is up. As such, you'll probably want to do this

```c#
var sensor = client.AddSensor(parameters).First();

while(sensor.Status != Status.Up)
{
    client.RefreshObject(sensor.Id);
    sensor = client.GetSensors(Property.Id, sensor.Id);
    Thread.Sleep(5000);
}
```

Are you able to confirm whether this was your issue?

**Comment by quentin-dev** [comment]
Yep, that was the issue ! I must've missed it above. Sorry for taking up so much of your time, but thank you for sticking with it !

Hope the good work continues !
Thanks again for everything !
