### ISSUE TITLE
Recovery log events two date

### ISSUE THREAD

**Issue by Hablaip** [lordmilko/PrtgAPI#315]
### What's going on?

Hello
need retrive all evento log two date 
Sample
    var client = new PrtgClient("x", "u", "p");
var Log1 = client.GetLogs(RecordAge.All, 500,LogStatus.Created);
![image](https://user-images.githubusercontent.com/88395506/202611568-69b922d5-bf14-4a84-a935-fcbf830ed876.png)

Need trive all information log not filter 

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
`GetLogs` has an override that allows you to specify a start and end date

**Comment by Hablaip** [comment]
PLase send sample 
Need list all evento day

**Comment by lordmilko** [comment]
Please [read the wiki](https://github.com/lordmilko/PrtgAPI/wiki/Historical-Information#logs)

> // Retrieve the last 400 logs from the object with ID 2034 between now and three days ago
> var logs = client.GetLogs(2034, endDate: DateTime.AddDays(-3), count: 400);

The `startDate` parameter is the point closest to now to retrieve logs from (implicitly `DateTime.Now` if not specified) and the `endDate` is the point in time furthest away from now to retrieve logs to
