### ISSUE TITLE
Enhance Get-ObjectProperty to include more types of usernames and inheritence info

### ISSUE THREAD

**Issue by solipsist01** [lordmilko/PrtgAPI#316]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

I'd like to query which usernames are configured on objects which don't have inheritence enabled.
Dell EMC, Fortigate etc, aren't availble in the Get-ObjectProperty output.

I actually don't know if the PRTG Api allows for this, but if it does, it would be nice if it could be added.

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

When i check the settings of a device, group, or probe, i can configure these credentials.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
You can view all raw properties on an object by doing `Get-ObjectProperty -Raw`
