### ISSUE TITLE
Geoloc Set-ObjectProperty Location "adress"

### ISSUE THREAD

**Issue by lucile2janvier** [lordmilko/PrtgAPI#318]
### What's going on?

Hello, thanks a lot for PrtgAPI. I use it every weekend and i love it !
I want to add massive geolocalisation on PRTG by prgAPI. 
Is this possible to set it with an address like this : 

Get-Device -Id XXXX | Set-ObjectProperty Location "my adress here"

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @lucile2janvier,

Yes, you can do that. PrtgAPI will automatically invoke PRTG's geolookup API endpoint and resolve the full address + latitude/longitude of the address so it shows properly on the map
