### ISSUE TITLE
403 Forbidden on Connect-PRTGServer

### ISSUE THREAD

**Issue by anthonym-iress** [lordmilko/PrtgAPI#319]
### What's going on?

I'm trying to log onto our PRTG Server with the PowerShell Module. My PRTG server is version 22.4.81.1532 x64.

Our PRTG API Version is 0.9.18

I've tried the following PowerShell script (passwords removed):

```
Connect-PrtgServer prtg.mycoolsite.com (New-Credential "XXXX" "XXXX")
```

However whenever we try to log on we get the following error: **"Response status code does not indicate success: 403 (Forbidden)."**

We can connect to the PRTG Server API with curl with the same credentials without issue.

I have checked the following past issues but they do not seem to be related:

https://github.com/lordmilko/PrtgAPI/issues/308
https://github.com/lordmilko/PrtgAPI/issues/314

I have also checked the troubleshooting section here without any success (https://github.com/lordmilko/PrtgAPI/wiki/Troubleshooting)

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
* Are you able to advise whether you were able to connect using PrtgAPI previously?
* Does your PRTG server use http or https?
* If it uses HTTPS, does it have an invalid SSL certificate?

**Comment by anthonym-iress** [comment]
> * Are you able to advise whether you were able to connect using PrtgAPI previously?

This is our first time using PrtgAPI 

> * Does your PRTG server use http or https?

It uses HTTPS

> * If it uses HTTPS, does it have an invalid SSL certificate?

The certificate is considered valid by Firefox, it does not expire until August.

**Comment by lordmilko** [comment]
When you generate the error, are you able to provide the output of

```powershell
$error[0].Exception.StackTrace
```
In addition, what happens if you intentionally type the wrong username and password?

The error that you're meant to get upon entering invalid credentials is

```powershell
Connect-PrtgServer : Could not authenticate to PRTG; the specified username and password were invalid.
```
The fact you're getting the error you're getting indicates potentially something else is getting in the way. Is there a proxy in your environment? Does PrtgAPI work from the PRTG Core server itself? My lab has the same PRTG version as you and I can confirm PrtgAPI works without issue

**Comment by anthonym-iress** [comment]
> When you generate the error, are you able to provide the output of
> 
> ```powershell
> $error[0].Exception.StackTrace
> ```

Here is the strack trace:

```
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at PrtgAPI.Request.RequestEngine.ValidateHttpResponse(HttpResponseMessage responseMessage, PrtgResponse response)
   at PrtgAPI.Request.RequestEngine.ValidateHttpResponse(PrtgClient client, PrtgRequestMessage request, HttpResponseMessage responseMessage, PrtgResponse response)
   at PrtgAPI.Request.RequestEngine.ExecuteRequest(PrtgRequestMessage request, CancellationToken token, Func`2 responseParser)
   at PrtgAPI.Request.RequestEngine.ExecuteRequest(IJsonParameters parameters, Func`2 responseParser, CancellationToken token)
   at PrtgAPI.PrtgClient.GetPassHash(String password)
   at PrtgAPI.PrtgClient..ctor(String server, String username, String password, AuthMode authMode, IWebClient client, IXmlSerializer xmlSerializer)
   at PrtgAPI.PrtgClient..ctor(String server, String username, String password, AuthMode authMode, Boolean ignoreSSL)
   at PrtgAPI.PowerShell.Cmdlets.ConnectPrtgServer.Connect(PSCmdlet cmdlet)
   at PrtgAPI.PowerShell.Cmdlets.ConnectPrtgServer.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

> In addition, what happens if you intentionally type the wrong username and password?

The same error. 403 Forbidden.

> The error that you're meant to get upon entering invalid credentials is
> 
> ```powershell
> Connect-PrtgServer : Could not authenticate to PRTG; the specified username and password were invalid.
> ```
> 
> The fact you're getting the error you're getting indicates potentially something else is getting in the way. Is there a proxy in your environment? Does PrtgAPI work from the PRTG Core server itself? My lab has the same PRTG version as you and I can confirm PrtgAPI works without issue

I'll need to check as I don't look after this PRTG Server, I just connect to it. It works if I just hit the server up with requests in python or curl. Is there something on the backend that connects differently?

**Comment by anthonym-iress** [comment]
Can I request you close this request? A coworker gave me an internal only address that doesn't get the error, I suspect a WAF or something like that is between me and the PRTG server.
