### ISSUE TITLE
question: can the api create new rest custom sensors?

### ISSUE THREAD

**Issue by olsonnn** [lordmilko/PrtgAPI#32]
question: can the api create new rest custom sensors with specific values in the custom  header settings?
The wiki is a bit unclear for me...

**Comment by lordmilko** [comment]
Hi @olsonnn,

You can create a new REST Custom BETA sensor by creating a set of [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters)

The following provides an example of how you might add a new REST Custom BETA sensor

```powershell
$params = Get-Device -count 1 | New-SensorParameters -RawType restcustom

$params.usecustomheaders = "yes"
$params.customheaders = "some: header`nanother: header"
$params.query = "awesome query"

Get-Device -Id 1234 | Add-Sensor $params
```

PRTG requires each header be separated by a newline character, which we achieve in PowerShell by typing `n

Please let me know if you require any further assistance

Regards,
lordmilko

**Comment by olsonnn** [comment]
thanks! works perfectly.!
