### ISSUE TITLE
Only use the trigger defined above automation

### ISSUE THREAD

**Issue by FirstNetworkingFreak** [lordmilko/PrtgAPI#321]
### What's going on?

I have a large number of sensors and using the get-sensors command I have found which ones have the "only use the triggers defined above" specified. I am trying to come up with a way to automate selecting the "inherit all triggers from parent objects and use the triggers defined above" button instead. I did not see a way to do it through set-sensor, set-notificationtrigger, or set-notificationtriggerproperty. Please help. Thanks
![image](https://user-images.githubusercontent.com/97697278/217046020-9b54afac-69c5-4bc4-a7f9-067423333af8.png)

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @FirstNetworkingFreak,

This setting is considered by PRTG to be an "object property", and as such is modified via the `Set-ObjectProperty` cmdlet

```powershell
Get-Device -Id 1001 | Set-ObjectProperty -InheritTriggers $true
```
Please see the help files linked in the Overview of the [Property Manipulation](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation) article for more information on properties that can be modified via `Set-ObjectProperty`

The `InheritTriggers` property is mentioned on the [Notification Triggers](https://github.com/lordmilko/PrtgAPI/wiki/Notification-Triggers) page, however I will update this page to maybe include an example as this question has come up more than once
