### ISSUE TITLE
HowTo: New-SerchFilter in pipeline

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#322]
### What's going on?

Hi...

I'm trying to do a recursive search with a searchfilter..
This does not work, since it only gets the direct descendants
```powershell
  $retVal = $Local:filter | Get-Group -ParentId $ObjectParent.Id -Recurse:$recurse
```

```powershell
  $retVal = $ObjectParent | $Local:filter | Get-Group -ParentId -Recurse:$recurse
+  $ObjectParen | $Local:filter | Get-Group  -Recurse:$recurse
+                 ~~~~~~~~~~~~~
Expressions are only allowed as the first element of a pipeline.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpressionsMustBeFirstInPipeline
```

Is there a way to pass the parent object directly ?
Like
```powershell
  $retVal = $Local:filter | Get-Group -Parent $ObjectParent -Recurse:$recurse
```

Thanks
  JR

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

Assuming the value of `$recurse` is `$true`, do you get the results you expect if you instead do

```powershell
$ObjectParent | Get-Group -Filter $local:filter -Recurse:$recurse
```
The `Get-Group` cmdlet allows you to specify several potential values by pipeline input
* The parent `-Probe`
* The parent `-Group`
* A `-Filter` to use

In your case, it seems like you want to specify both a parent (`-Probe` or `-Group`) and a `-Filter`. Only one of those can be specified by pipeline input, so for the other you will need to pass the value to the parameter directly

Are you able to advise if this resolves your issue?

**Comment by JRAndreassen** [comment]
Hello again @lordmilko ...

That was a quick turn-around...

Outstanding... 
  That does indeed take care of the problem...

Thank you Sir... :)
