### ISSUE TITLE
Add-Device - Setting the destination of the device

### ISSUE THREAD

**Issue by justhacking2** [lordmilko/PrtgAPI#323]
### What's going on?

I am using PRTGapi to add multiple devices via the csv import and Powershell. I have a variable DestGroupID of where I want the new device to go,  but cannot figure out how to call it. Any better way to make this work? Thanks in advance!

Here is my code 

$thisdevice = Get-Probe "FTWIN-PRTG1 (Data centers)" | Add-Device $Device.NewDeviceName $Device.NewIP -AutoDiscover -Template $Device.TemplateID

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
if `$DestGroupID` pertains to a group, you would do

```powershell
Get-Group -Id $DestGroupID | Add-Device ...
```
Are you able to advise if this answers your question?

**Comment by justhacking2** [comment]
It is not working at this point. I have put in a ticket with PRTG to see if it is something in the server settings.

Here is my updated code. 
Get-Group -Id $DestGroupID  | Add-Device $Device.NewDeviceName $Device.NewIP -AutoDiscover -Template $Device.TemplateID
It results in nothing being created and the following error message :

![8E5C6C59-CA97-4157-9FD2-5CE8576B6045](https://user-images.githubusercontent.com/124810932/217974973-3cdbbffc-5943-458c-86df-f28eb2c295ae.png)
