### ISSUE TITLE
Add another Template on existing Device

### ISSUE THREAD

**Issue by miguelfpj** [lordmilko/PrtgAPI#324]
### What's going on?

Hi support,
If i create a new Device i can add multiple Templates to it. Once its created, i cant find a command which would allow me to add an extra template to that device. I am able to add sensors to the device but i would like to enable another template.

Is that possible?

thanks!

Miguel

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @miguelfpj,

Please see #287 which should answer this question

**Comment by miguelfpj** [comment]
Perfect Thank you very much!

## Array for current and new Template
$Template = @()

## Get current Template used on the Device
$currentTemplate = Get-device -Name "SRV1" | Get-ObjectProperty -RawProperty devicetemplate

## Add it to the array
$Template += Get-DeviceTemplate $currentTemplate

## Get a second Template and add it to the array
$Template += Get-DeviceTemplate "Template - Service - XYZ"

## Set both Templates into the device
Get-Device -Name "SRV1" | Set-ObjectProperty -Rawparameters @{ devicetemplate_=1;devicetemplate__check=$Template} -Force
