### ISSUE TITLE
Is there a way to clone a 'SensorParameters' Object

### ISSUE THREAD

**Issue by PRTGC** [lordmilko/PrtgAPI#328]
### What's going on?

Hi ...
Is there a way to avoid calling '$device | New-SensorParameters ...' over and over ?
Is there a way to clone it and just change the name etc ?
Thanks
   JR

```
PS C:\> $Local:newParam = get-device -Id 159035 | New-SensorParameters -RawType 'exexml' -Timeout 3 -erroraction 'silentlycontinue'
PS C:\> $Local:newParam.copy()
Method invocation failed because [PrtgAPI.Parameters.DynamicSensorParameters] does not contain a method named 'copy'.
At line:1 char:1
+ $Local:newParam.copy()
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

PS C:\> $Local:newParam.clone()
Method invocation failed because [PrtgAPI.Parameters.DynamicSensorParameters] does not contain a method named 'clone'.
At line:1 char:1
+ $Local:newParam.clone()
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
As per the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#introduction-1) if the parameters do not contain fields specific to the device/probe they were queried from, you can simply store them in a variable and pass to `Add-Sensor`

```powershell
$params = get-device -Id 159035 | New-SensorParameters -RawType 'exexml'

Get-Device *foo* | Add-Sensor $params
```
```powershell
$params = get-device -Id 159035 | New-SensorParameters -RawType 'exexml'

$params.someprop = "someval"
Get-Device foo | Add-Sensor $params

$params.someprop = "someotherval"
Get-Device bar | Add-Sensor $params
```
In the case of EXEXML sensors, the `Targets` property will list all of the scripts present on the probe of the device that was queried. If a sensor is created on a device on another probe that does not contain a specified script, the sensor will be created, however will go into an error status stating that the script file cannot be found.
