### ISSUE TITLE
Installation without Online Connection (Forbidden)

### ISSUE THREAD

**Issue by ArneBrucker** [lordmilko/PrtgAPI#330]
### What's going on?

Hello LordMilko,

thank you for your Module which is very helpfull in working with PRTG. Now I try to install your Module on a maschine without Internet connection and downloaded  your zip- file - the Installation as described is not working. The "build.cmd" leads to a workspace; with an command "Invoke-PRTGBuild"  the next steo is a "Get https://dotxxxxxx" which could not reached. Is there any way to work with your module without any internet connection? And if you - please explain how.

Thank you

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @ArneBrucker,

It appears you are not looking at the correct page of the wiki; `build.cmd` is used to *compile PrtgAPI from scratch*, which requires downloading dependencies from the internet if such dependencies are not already installed

As per the [Manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions, you can simply download `PrtgAPI.zip`, unblock and extract it.

**Comment by lordmilko** [comment]
Hi @ArneBrucker,

Upon further investigation it seems the issue is that because I haven't released a new build of PrtgAPI in more than 6 months, Appveyor has deleted the latest artifact. You can also find a copy of `PrtgAPI.zip` on the [Releases](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.18) page
