### ISSUE TITLE
PRTGAPI Set ObjectProperty RAW

### ISSUE THREAD

**Issue by egulpen2** [lordmilko/PrtgAPI#332]
Hi,

Im trying to create some sensors in bulk using the PRTGAPI. When i try to change the RawProperty 'paessler-rest-rest_settings_section-rest_group-url' on the sensor it doesn't seem to do anything.

A sensor that i created by hand shows this properties;
name                                                                           : Unifi Site - test
parenttags                                                                     : 
tags                                                                           : rest
paessler-rest-rest_settings_section-rest_group-url                             : https://URLTOCHECK/api/site/8ul9cwkb
paessler-rest-rest_settings_section-rest_group-http_method                     : get
paessler-rest-rest_settings_section-rest_group-timeout                         : 30
paessler-rest-rest_settings_section-rest_group-content_type                    : json
paessler-rest-rest_settings_section-rest_group-sensor_message                  : 
paessler-rest-channel_section-channel_group-channel1_jsonpath                  : $[0].disconnected_aps
paessler-rest-channel_section-channel_group-channel1_name                      : Disconnected AP's
paessler-rest-channel_section-channel_group-channel1_unit                      : AP's
paessler-rest-channel_section-channel_group-channel1_up_states                 : 
paessler-rest-channel_section-channel_group-channel1_warning_states            : 
paessler-rest-channel_section-channel_group-channel1_down_states               : 
paessler-rest-channel_section-channel_group-channel1_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel2                           : disable
paessler-rest-channel_section-channel_group-channel2_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel2_name                      : 
paessler-rest-channel_section-channel_group-channel2_unit                      : 
paessler-rest-channel_section-channel_group-channel2_up_states                 : 
paessler-rest-channel_section-channel_group-channel2_warning_states            : 
paessler-rest-channel_section-channel_group-channel2_down_states               : 
paessler-rest-channel_section-channel_group-channel2_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel3                           : disable
paessler-rest-channel_section-channel_group-channel3_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel3_name                      : 
paessler-rest-channel_section-channel_group-channel3_unit                      : 
paessler-rest-channel_section-channel_group-channel3_up_states                 : 
paessler-rest-channel_section-channel_group-channel3_warning_states            : 
paessler-rest-channel_section-channel_group-channel3_down_states               : 
paessler-rest-channel_section-channel_group-channel3_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel4                           : disable
paessler-rest-channel_section-channel_group-channel4_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel4_name                      : 
paessler-rest-channel_section-channel_group-channel4_unit                      : 
paessler-rest-channel_section-channel_group-channel4_up_states                 : 
paessler-rest-channel_section-channel_group-channel4_warning_states            : 
paessler-rest-channel_section-channel_group-channel4_down_states               : 
paessler-rest-channel_section-channel_group-channel4_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel5                           : disable
paessler-rest-channel_section-channel_group-channel5_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel5_name                      : 
paessler-rest-channel_section-channel_group-channel5_unit                      : 
paessler-rest-channel_section-channel_group-channel5_up_states                 : 
paessler-rest-channel_section-channel_group-channel5_warning_states            : 
paessler-rest-channel_section-channel_group-channel5_down_states               : 
paessler-rest-channel_section-channel_group-channel5_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel6                           : disable
paessler-rest-channel_section-channel_group-channel6_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel6_name                      : 
paessler-rest-channel_section-channel_group-channel6_unit                      : 
paessler-rest-channel_section-channel_group-channel6_up_states                 : 
paessler-rest-channel_section-channel_group-channel6_warning_states            : 
paessler-rest-channel_section-channel_group-channel6_down_states               : 
paessler-rest-channel_section-channel_group-channel6_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel7                           : disable
paessler-rest-channel_section-channel_group-channel7_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel7_name                      : 
paessler-rest-channel_section-channel_group-channel7_unit                      : 
paessler-rest-channel_section-channel_group-channel7_up_states                 : 
paessler-rest-channel_section-channel_group-channel7_warning_states            : 
paessler-rest-channel_section-channel_group-channel7_down_states               : 
paessler-rest-channel_section-channel_group-channel7_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel8                           : disable
paessler-rest-channel_section-channel_group-channel8_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel8_name                      : 
paessler-rest-channel_section-channel_group-channel8_unit                      : 
paessler-rest-channel_section-channel_group-channel8_up_states                 : 
paessler-rest-channel_section-channel_group-channel8_warning_states            : 
paessler-rest-channel_section-channel_group-channel8_down_states               : 
paessler-rest-channel_section-channel_group-channel8_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel9                           : disable
paessler-rest-channel_section-channel_group-channel9_jsonpath                  : 
paessler-rest-channel_section-channel_group-channel9_name                      : 
paessler-rest-channel_section-channel_group-channel9_unit                      : 
paessler-rest-channel_section-channel_group-channel9_up_states                 : 
paessler-rest-channel_section-channel_group-channel9_warning_states            : 
paessler-rest-channel_section-channel_group-channel9_down_states               : 
paessler-rest-channel_section-channel_group-channel9_unlisted_string_handling  : down
paessler-rest-channel_section-channel_group-channel10                          : disable
paessler-rest-channel_section-channel_group-channel10_jsonpath                 : 
paessler-rest-channel_section-channel_group-channel10_name                     : 
paessler-rest-channel_section-channel_group-channel10_unit                     : 
paessler-rest-channel_section-channel_group-channel10_up_states                : 
paessler-rest-channel_section-channel_group-channel10_warning_states           : 
paessler-rest-channel_section-channel_group-channel10_down_states              : 
paessler-rest-channel_section-channel_group-channel10_unlisted_string_handling : down
stack                                                                          : 0
stackunit                                                                      : ?raw-AP's|AP's
writeresult                                                                    : DiscardResult
intervalgroup                                                                  : 1
inherittriggers                                                                : 1
scheduledependency                                                             : 1
maintenable                                                                    : 0
maintstart                                                                     : 2023,03,31,22,29,00
maintend                                                                       : 2023,03,31,22,30,00
dependencytype                                                                 : 0
depdelay                                                                       : 0
AccessGroup                                                                    : 0
accessrights                                                                   : 1
unitconfiggroup                                                                : 1
id                                                                             : 63670
anti-csrf-token                                                                : YmYzN2JiZGI0NzQwZDNhN2Y0OWU3MzA0MGUxMjY0OWJkOTk1ZjVjMmE4NTViZTA5Y2FhNWFlNjUwZDdhOWI0Yg==
priority                                                                       : 3
primarychannel                                                                 : 1|Disconnected AP's (AP's)|
interval                                                                       : 60|60 seconds
errorintervalsdown                                                             : 1
schedule                                                                       : -1|None|
accessrights_26199                                                             : -1
accessrights_51698                                                             : -1
accessrights_61323                                                             : -1
accessrights_59445                                                             : -1
accessrights_45805                                                             : -1
accessrights_15358                                                             : -1
accessrights_42681                                                             : -1
accessrights_60250                                                             : -1
accessrights_26084                                                             : -1
accessrights_33302                                                             : -1
accessrights_26348                                                             : 200
accessrights_62537                                                             : -1
accessrights_21679                                                             : -1
accessrights_18603                                                             : -1
accessrights_15294                                                             : -1
accessrights_201                                                               : -1
accessrights_47855                                                             : 0
paessler-rest-rest_settings_section-rest_group-post_body                       : 
paessler-rest-rest_settings_section-rest_group-custom_header                   : 
dependencyvalue                                                                : 0

So i want to clone the existing sensor, then change the 'paessler-rest-rest_settings_section-rest_group-url' property.
Any idea how to do this? The sensors are of type REST Custom v2 (BETA).

Thanks!
Eric

**Comment by squintfox** [comment]
@egulpen2 Use 'paessler-rest-rest_settings_section-rest_group-url_'.  I actually just did the exact same setup the other day.

**Comment by egulpen2** [comment]
> @egulpen2 Use 'paessler-rest-rest_settings_section-rest_group-url_'. I actually just did the exact same setup the other day.

Thats it! Thanks for the support!
