### ISSUE TITLE
new-sensor : Parameter '-ServiceName' requires a value, however an empty collection was specified.

### ISSUE THREAD

**Issue by MikeSouthwell** [lordmilko/PrtgAPI#335]
When I enter the following command I get this error:

new-sensor : Parameter '-ServiceName' requires a value, however an empty collection was specified.

`get-device -id $deviceID.Id | new-sensor -WmiService "*$WMIServiceSensorName*" -StartStopped $false`

I have confirmed that $deviceID and $WMIServiceSensorName both return the correct value.

Do you know why it keeps asking for **-ServiceName**?

**Comment by MikeSouthwell** [comment]
Figured it out. This was because the service the sensor was being created to monitor didn't exist on the device. Is there any way to create the sensors prior to the Windows service being created?

**Comment by lordmilko** [comment]
You should be able to do this using [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell)

**Comment by lordmilko** [comment]
Just to provide a bit more context on this, you would either need to create a fake target object (not recommended) or simply grab the dynamic parameters from another device that *does* have the required service, and then apply it to all the other devices you're interested in (including devices that don't have the service yet). The act of "querying" only has to be performed once. For any device that doesn't have the service, the sensor will show "service not found" until the service is created
