### ISSUE TITLE
How to manipulate businessprocess sensor thresholds

### ISSUE THREAD

**Issue by MPrica12** [lordmilko/PrtgAPI#336]
### What's going on?

Hello,

I am trying to manipulate using Powershell and the PrtgAPI the threshold settings of a businessprocess sensor.

We have a number of devices that we monitor using a businessprocess sensor, which goes into error state when a specific number(based on a percentage) goes done.

Doing so we need to manipulate using scripts the percentage of the threshold using Powershell scripts. We have tried to pull this data by using Get-ObjectProperty -Raw: 

*Get-Probe -Id *id of probe* | Get-ObjectProperty -Raw*

Problem is that we cannot see in the terminal the Property that allows us to manipulate these 2 values.

These settings are in the "Business Process Specific Settings" of PRTG.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Business Process sensors are a very complex sensor type. One of the properties of the sensor contains JSON that stores the configuration data. For more information, please see [this issue](https://github.com/lordmilko/PrtgAPI/issues/179)

In short, you will most likely need to do something along the lines of the following

```powershell
# Get the raw data
$raw = Get-Sensor -Id 1001 | Get-ObjectProperty -Raw

# Get PowerShell object you can interact with
$json = ConvertFrom-Json $raw.businessprocessdefinitions

# Make the changes you want to the data in the $json variable

# Convert back to JSON
$str = $json | ConvertTo-Json

# Update the sensor
Get-Sensor -Id 1001 | Set-ObjectProperty -RawProperty businessprocessdefinitions_ -RawValue $str
```
Note the above is completely untested but should hopefully be enough to point you in the right direction

**Comment by MPrica12** [comment]
Hello,

Thanks a lot for the information, however I seem to face issues when trying to get this property, it shows as empty, like below:

businessprocessdefinitions : 

There is nothing showing after businessprocessdefinitions, after converting the value from Json it still seems to be empty.

Is there perhaps something I am missing in this conversion? Thanks for your support!

**Comment by lordmilko** [comment]
If the property is empty this indicates a configuration has not been specified for the sensor yet. If you navigate to the Settings page within PRTG and inspect the HTML of the page there should be a businessprocessdefinitions property there with some value. If it's empty in PrtgAPI I would expect it to be empty on the Settings page too. You can also trace saving the Settings page with [Fiddler Classic](https://www.telerik.com/download/fiddler) and see what values PRTG submits back to the web server; I would again expect it to be submitting an empty value if nothing has been configured yet. The issue I linked above shows what the normal value of this property should approximately look like

**Comment by lordmilko** [comment]
> I checked and the JSON initial is in a single single, but when converting it goes from a top to bottom string instead.
I am not sure what this means. Are you able to provide an example of the format PRTG uses and the value of `$str` you have?

**Comment by MPrica12** [comment]
Here it is,

This is what it looks like initially, what PRTG uses:
[{"objects":[78140,78141,78142,78143,78144,78145,78146,78147,78148,78149,78150,78151,78152,78153,78154,78155,78156,78157,78158,78159,78160,78161,78162,78164,78163,78166,78165,78167,78168,78169,78170,78171,78172,78173,78174,78175,78176,78177,78178,78179,78180,78181,78182,78183,78185,78184,78186,78187,78188,78189,78190,78191,78192,78193,78194,78196,78195,78197,78198,78199,78200,78201,78202,78203,78204,78205,78206,78207,78208,78209,78210,78211,78212,78214,78213,78215,78216,78217,78218,78219,78220,78221,78223,78224,78225,78226,78227,78228,78229,78230,78232,78231,78233,78234,78235,78236,78237,78238,78239,78240,78241,78242,78243,78244,78245,78246,78247,78248,78249,78250,78251,78252,78253,78254,78256],"warningthreshhold":99,"errorthreshhold":97,"channelname":"Status"}]

And this is the value $str has:

{
  "objects": [
    78140,
    78141,
    78142,
    78143,
    78144,
    78145,
    78146,
    78147,
    78148,
    78149,
    78150,
    78151,
    78152,
    78153,
    78154,
    78155,
    78156,
    78157,
    78158,
    78159,
    78160,
    78161,
    78162,
    78164,
    78163,
    78166,
    78165,
    78167,
    78168,
    78169,
    78170,
    78171,
    78172,
    78173,
    78174,
    78175,
    78176,
    78177,
    78178,
    78179,
    78180,
    78181,
    78182,
    78183,
    78185,
    78184,
    78186,
    78187,
    78188,
    78189,
    78190,
    78191,
    78192,
    78193,
    78194,
    78196,
    78195,
    78197,
    78198,
    78199,
    78200,
    78201,
    78202,
    78203,
    78204,
    78205,
    78206,
    78207,
    78208,
    78209,
    78210,
    78211,
    78212,
    78214,
    78213,
    78215,
    78216,
    78217,
    78218,
    78219,
    78220,
    78221,
    78223,
    78224,
    78225,
    78226,
    78227,
    78228,
    78229,
    78230,
    78232,
    78231,
    78233,
    78234,
    78235,
    78236,
    78237,
    78238,
    78239,
    78240,
    78241,
    78242,
    78243,
    78244,
    78245,
    78246,
    78247,
    78248,
    78249,
    78250,
    78251,
    78252,
    78253,
    78254,
    78256
  ],
  "warningthreshhold": 99,
  "errorthreshhold": 97,
  "channelname": "Status"
}

**Comment by lordmilko** [comment]
Aside from the fact the PowerShell version is formatted, I can see that PRTG's string has a leading "[" and "]". This indicates PRTG expects that the value will be an array

To force the resulting JSON to be an array, you should be able to do the following

```powershell
$sensor = Get-Sensor -Id id | Get-ObjectProperty -RawProperty businessprocessdefinitions

$json = convertfrom-json $sensor

$json.warningthreshhold = value

$str = ConvertTo-Json @($json)

Get-Sensor -Id id | Set-ObjectProperty -RawProperty businessprocessdefinitions_ -RawValue $str -Force
```
The key change here is the following:

```powershell
ConvertTo-Json @($json)
```
`@()` forces PowerShell to interpret the value as an array (in case it's not, or no longer an array), and then by specifying the array to the `-InputObject` parameter directly (*not* by piping) `ConvertTo-Json` will parse the value as is - as an array, which should resting in a `$str` value containing leading and trailing square brackets

**Comment by MPrica12** [comment]
Cheers, it's working as expected now, I was able to modify the values, thanks a lot!
