### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mikepowell** [lordmilko/PrtgAPI#337]
### What's going on?

I hope sending this as an issue doesn't create too much unnecessary overhead for you, but I don't have a problem or question - I just wanted to show my appreciation for your work here. This module is just an absolute pleasure to work with and enables some truly amazing one-liners in powershell. And the documentation is SO complete, even full examples that are super helpful. I know it's a ton of work and just wanted to say thanks!

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by mikepowell** [comment]
Just closing so it doesn't appear as an open issue.

**Comment by lordmilko** [comment]
Thanks!
