### ISSUE TITLE
How to tag existing devices

### ISSUE THREAD

**Issue by erikcurtis** [lordmilko/PrtgAPI#339]
### What's going on?

I have several devices that need tags. How can I set them?

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
You can modify object properties by doing `Set-ObjectProperty -Tags`. For more information on using `Set-ObjectProperty` please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#set-1)

Note that modifying the tags of an object will completely *replace* any existing tags the object has (tags inherited from parent objects won't be affected). If you want to append tags to those that already exist, you need to construct an array of all the tags that should exist. The easiest way to get the tags defined on an object directly is to do `Get-ObjectProperty` and use the `Tags` property on the returned object
