### ISSUE TITLE
[0.8.6] Dynamic parameter name for SQL sensors

### ISSUE THREAD

**Issue by Eazhi** [lordmilko/PrtgAPI#34]
Hi!

I still am on the version 0.8.6 of the API, but I've encountered a problem which I think has not been fixed in 0.9, I will check soon (I need to change the code that breaks with the update).

When I try to do :

> var parameters = client.GetDynamicSensorParameters(4478, "wmisqlserver2016");
parameters.Name = "This should work";
client.AddSensor(4478, parameters);

The name of the sensor ends up to 

> SQL Server (SQL2008R2) Buffer Manager

instead of "This should work".

I've tried with other sensor types like ''wmiprocessor" and it works just fine.

What is weird is the sensor name being like a 2008R2 SQL sensor while I am requesting the creation of a 2016 SQL sensor.
Am I doing something wrong?

EDIT: Actually there is a parameter (that I was not setting) for SQL sensors in PRTG that may override the `parameters.Name`.

Thanks in advance,
-- Eazhi

**Comment by lordmilko** [comment]
Hi @Eazhi,

WMI SQL Server 2016 sensor names are dynamically generated based on the settings that were used to create the sensor. If you attempt to create a WMI SQL Server 2016 sensor in the PRTG UI you should find you cannot specify a name there either, and that rather the sensor will be named based on the specified instance + performance counter type.

Finally, if you inspect the default name of the dynamic sensor parameters, you will likely find the default name is "Base Sensor". Any time you see a sensor named "Base Sensor" by default, this indicates the sensor name will be dynamically generated.

Are you able to advise whether this resolves your issue?

Regards,
lordmilko

**Comment by Eazhi** [comment]
Hi,

Yes, it does work, thanks a lot!

And thanks for the info about the "Base Sensor" name!
-- Eazhi
