### ISSUE TITLE
Adding new sensors not working after update to version 23.3.86.1520

### ISSUE THREAD

**Issue by imaderaya** [lordmilko/PrtgAPI#345]
### Describe the bug

Hello,

After updating PRTG to version 23.3.86.1520, Adding sensors is not working any more.
The error message : Could not authenticate to PRTG; the specified username and password were invalid

### Steps to reproduce

```powershell
Code Example:

Connect-PrtgServer -Server "https://prtgserver.com" (New-Credential "username" "passwd");
$device = Get-Device -Id 126556;
$device | New-SensorParameters -RawType ping | Add-Sensor

Result:

Add-Sensor : Could not authenticate to PRTG; the specified username and password were invalid.
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.20348.1850
PSEdition      : Desktop
OS             : Microsoft Windows Server 2022 Standard
PrtgAPIVersion : 0.9.18
Culture        : fr-CH
CLRVersion     : 528449
PrtgVersion    : 23.3.86.1520
PrtgLanguage   : english.lng
```

### Additional context

There is no issue with:
  - Add-Device
  - Set-ObjectProperty
  - Set-ChannelProperty

**Comment by lordmilko** [comment]
Hi @imaderaya,

I have deployed a fix for this issue. Can you please follow the [manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions and advise whether this issue is resolved in PrtgAPI 0.9.19-preview.2?

**Comment by r0m1CH** [comment]
Hi @imaderaya @lordmilko 

Thanks. I will give it a try. Where can I download the PrtgAPI 0.9.19-preview.2 ? 
I cannot find it anywhere. 

Thanks

**Comment by TheUdK** [comment]
Any chance of building a release and publishing to PSGallery as release or prerelease?

**Comment by poa-swillemen** [comment]
Hi @lordmilko, we are testing with PRTG  23.3.86.1520 and PrtgAPI 0.9.19-preview.2 but we are not able to add a sensor. There is no error after running the code and but there is no sensor created in PRTG. Do you have an idea how to solve this? Thank you in advance!

Sample code:

`$Device = Get-Device -Id 3833 -Probe $Probe`
`$Device | New-SensorParameters -RawType ping | Add-Sensor -Verbose`

Output (some private content in parameters has been changed):

`VERBOSE: Performing the operation "Add-Sensor" on target "Ping (Destination: SERVERNAME (ID: 3833))".`

`VERBOSE: Add-Sensor: Synchronously executing request https://prtg/api/table.xml?content=sensors&columns=objid,name,probe,group,favorite,lastvalue,device,downtime,downtimetime,downtimesince,uptime,uptimetime,uptimesince,knowntime,cumsinc
e,lastcheck,lastup,lastdown,minigraph,schedule,basetype,baselink,notifiesx,intervalx,access,dependency,position,status,comments,priority,message,parentid,tags,type,active&count=*&filter_parentid=3833&filter_type=ping&username=username&pa
sshash=hash1234`

`VERBOSE: Add-Sensor: Synchronously executing request https://prtg/controls/addsensor2.htm?id=3833&sensortype=ping&username=username&passhash=hash1234`

`VERBOSE: Add-Sensor: Synchronously executing request https://prtg/addsensor5.htm?name_=Ping&priority_=3&inherittriggers=1&intervalgroup=1&interval_=60%7C60+seconds&errorintervalsdown_=1&tags_=pingsensor&timeout_=5&size_=32&countmethod_=
1&count_=5&delay_=5&autoacknowledge_=0&anti-csrf-token=%token%&sensortype=ping&id=3833&tmpid=14`

**Comment by schoenm1** [comment]
> Hi @lordmilko,
> 
> I confirm that the issue is resolved in PrtgAPI 0.9.19-preview.2.
> 
> Great job.

Same here. After installing current Prelease, my Scripts are working again.

**Comment by MikeyMing** [comment]
I still get the issue with the latest version.

Add-Sensor : Could not authenticate to PRTG; the specified username and password were invalid.
At line:14 char:34
+ Get-Device -Id $ParentDeviceId | Add-Sensor $params
+                                  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Sensor], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,PrtgAPI.PowerShell.Cmdlets.AddSensor

get-command add-sensor

CommandType     Name                                               Version    Source                                                                                                                                                                                                                           
-----------     ----                                               -------    ------                                                                                                                                                                                                                           
Cmdlet          Add-Sensor                                         0.9.18     PrtgAPI

**Comment by MikeyMing** [comment]
Get-PrtgClient -Diagnostic


PSVersion      : 5.1.14393.5582
PSEdition      : Desktop
OS             : Microsoft Windows Server 2016 Standard
PrtgAPIVersion : 0.9.18
Culture        : da-DK
CLRVersion     : .NET Framework 4.8 (528049)
PrtgVersion    : 23.3.86.1520
PrtgLanguage   : english.lng

**Comment by xasz** [comment]
@MikeyMing not sure if you are using the Preview. 
I have not tested the preview - I need to, but had no time - So my prtg upgrade to the newest version will have to wait. But your version sys 0.9.18 and not 0.9.19-preview.2

**Comment by MikeyMing** [comment]
How do I get the preview?  When I click on the link it downloads the latest zip directly.

Thanks

**Comment by MikeyMing** [comment]
Looks like it was released a few minutes ago

**Comment by lordmilko** [comment]
You need to follow the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) to use the latest preview build, however I am actively in the process of trying to release PrtgAPI 0.9.19, I'm just trying to resolve some issues with my build system

**Comment by lordmilko** [comment]
Please be advised PrtgAPI 0.9.19 has now been released. Please do `Update-Module PrtgAPI` and then reopen your PowerShell session

**Comment by MikeyMing** [comment]
Thanks.  Its working now.  God bless PrtgAPI

**Comment by MikeSouthwell** [comment]
Hi LordMilko,

I have updated to 0.9.19, but I am still getting the same error.

Can you please take another look?

PSVersion : 5.1.17763.4974
PSEdition : Desktop
OS : Microsoft Windows Server 2019 Datacenter
PrtgAPIVersion : 0.9.19
Culture : en-AU
CLRVersion : .NET Framework 4.8 (528049)
PrtgVersion : 23.3.88.1421
PrtgLanguage : english.lng

Set-ObjectProperty : PRTG was unable to complete the request. The server responded with the following error: The validation of the data you entered has failed. Authorization: Required field, not defined. The object has not been changed.

**Comment by lordmilko** [comment]
Can you please provide a code sample which is generating this error?

**Comment by MikeSouthwell** [comment]
Please see relevant code snippet below that is causing that error:

`Get-Sensor -Name "Template" -count 1 | Clone-Object -DestinationId $resellerID.Id -Name $backupSensorName -Resume
Get-Sensor -Name $backupSensorName | Set-ObjectProperty -RawProperty paessler-microsoft365-mailbox_section-mailbox_group-filter_subject_string_ -RawValue "$subjectString" -Force`

**Comment by carsten0407** [comment]
Where can I download the PrtgAPI 0.9.19-preview.2?  the manuial download lis broken

https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.zip
{"message":"Artifact not found or access denied."}

**Comment by lordmilko** [comment]
PrtgAPI 0.9.19 has now been released

To update PrtgAPI, please run `Update-Module PrtgAPI` in PowerShell and then close and reopen the window

**Comment by carsten0407** [comment]
Yessss, it works, thx
