### ISSUE TITLE
Add-Sensor : Could not authenticate to PRTG; the specified username and password were invalid.

### ISSUE THREAD

**Issue by r0m1CH** [lordmilko/PrtgAPI#346]
### Describe the bug

Hi,

I updated to the latest version of PRTG and since then, it seems that my script that automatically clean and recreate a new sensor EXE/XML sensor failed with the generic error Could not authenticate.

![image](https://github.com/lordmilko/PrtgAPI/assets/373802/afb0c9fb-d243-4235-a83a-b0af5b42b52f)

I think this is related to this issue also: https://github.com/lordmilko/PrtgAPI/issues/268

### Steps to reproduce

```powershell
$nsCertificateSensorParam = New-SensorParameters ExeXml "NS Certificates SSL Expiration" "NetScaler-CertExpiration.ps1"
$nsCertificateSensorParam.ExeParameters = "%device %linuxuser %linuxpassword"
$nsCertificateSensorParam.Interval = "02:00:00"
Get-Device NETSCALER* | Add-Sensor $nsCertificateSensorParam
```

The last command gives the error: 
Add-Sensor : Could not authenticate to PRTG; the specified username and password were invalid.
At line:1 char:26

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.17763.4644
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Datacenter
PrtgAPIVersion : 0.9.18
Culture        : fr-CH
CLRVersion     : .NET Framework 4.8 (528049)
PrtgVersion    : 23.3.86.1520
PrtgLanguage   : english.lng
```

### Additional context

I remain available for any test or if you need more info.

**Comment by lordmilko** [comment]
Hi @r0m1CH,

Please see #345 for a resolution to this issue

**Comment by derSchweiger** [comment]
Yep it's working. Thank you very much and sorry for the duplicate!
