### ISSUE TITLE
SNMP Traffic Raw Parameters, doesn't format right with Powershell

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#35]
Trying to use Add-Sensor to filter SNMP Traffic Sensors to only connected sensors.

This works fine:

```powershell
$snmpTrafficParams = New-SensorParameters -device $prtgDevice -RawType snmptraffic 
$SNMPTrafficParams | Add-Sensor
```
But only adds the first sensor in the target list.

This works fine as well and adds all sensors in the target list

```powershell
$snmpTrafficParams = New-SensorParameters -device $prtgDevice -RawType snmptraffic 
$snmpTrafficParams.interfacenumber__check = $snmpTrafficParams.targets.interfacenumber__check
$SNMPTrafficParams | Add-Sensor
```

However, trying to apply any sort of filtering breaks it. This doesn't work
```powershell
$snmpTrafficParams = New-SensorParameters -device $prtgDevice -RawType snmptraffic 
$snmpTrafficParams.interfacenumber__check = $snmpTrafficParams.targets.interfacenumber__check | where {$PSItem.properties[2] -match '^Connected$'}
$SNMPTrafficParams | Add-Sensor
```

Looking at it in Fiddler, it looks like the "filtered" parameters aren't getting formatted right by PRTGAPI:

Correct (2nd example)
![image](https://user-images.githubusercontent.com/15258962/44678420-2cdfae00-a9ed-11e8-8403-debf437133bf.png)

Incorrect (3rd example)
![image](https://user-images.githubusercontent.com/15258962/44678399-1fc2bf00-a9ed-11e8-8169-22b9669cd4aa.png)

I verified the array types and objects are the same, so not sure what's happening here. 

For now I have a post-creation script that goes back and deletes the sensors I didn't want, but I'd rather cut down on the API calls and "do it right the first time!" :)

**Comment by JustinGrote** [comment]
UPDATE: Using interfacenumber__check[1..5] works fine, so may be something incompatible with how where-object is creating the new collection. Gonna try to pull the indices with the filter and create using that instead as a workaround.

**Comment by lordmilko** [comment]
Hi @JustinGrote,

This is in fact a bug; the issue here is not that `Where-Object` returns an array, but rather that it returns an array of *PSObject*. `DynamicSensorParameters` has the sensor to unwrap as *single* object of type `PSObject`, but doesn't consider it might have to unwrap a whole array of them.

This issue will be rectified in PrtgAPI 0.9.1.

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @JustinGrote,

PrtgAPI 0.9.1 has now been released, which contains a fix for this issue. To update PrtgAPI, simply run

```powershell
Update-Module PrtgAPI
```

and reopen your PowerShell

Thanks for raising this issue!

Regards,
lordmilko
