### ISSUE TITLE
Artifact not found or access denied

### ISSUE THREAD

**Issue by solipsist01** [lordmilko/PrtgAPI#350]
### Describe the bug

I'd like to download the latest build, as per the documentation.

However, this url gives the following message:
https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.zip

`{"message":"Artifact not found or access denied."}`

### Steps to reproduce

```powershell
Try to download the zip file in a browser.
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
Irrelevant.
```

**Comment by lordmilko** [comment]
Appveyor automatically deletes artifacts after 1 month

I have kicked off a [rebuild](https://ci.appveyor.com/project/lordmilko/prtgapi), this should hopefully be done in an hour

**Comment by solipsist01** [comment]
Thank you :) !
