### ISSUE TITLE
Creat paessler.rest.rest_custom_v2_sensor

### ISSUE THREAD

**Issue by Simisled** [lordmilko/PrtgAPI#355]
### What's going on?

Hello Everyone,

Can the api create new rest custom sensors V2 with specific values for the differents channels?

Best regards,

Simis

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
PrtgAPI should be able to create any type of sensor using [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters)
