### ISSUE TITLE
Deploying Vendor Sensors - Juniper/IPM

### ISSUE THREAD

**Issue by bmcgrath-pr** [lordmilko/PrtgAPI#357]
### What's going on?

Hello Sir,

Thank you kindly for this repo, has helped us streamline a tonne of work.
We're attempting to automate certain deployments of monitoring, and hit a little snag around IPM Sensors.

Code we've attempted to deploy:
Write-Host "Adding iPMI Sensors"
$ipmi = Get-Device $device | New-SensorParameters -RawType ipmi -Target * | Add-Sensor

To add the following Sensors:
IPMI Sensor Fan
IPMI Sensor Power Supply
IPMI Sensor Temperature
IPMI Sensor Voltage

Response from Powershell:
New-SensorParameters : Cannot process query for sensor type 'ipmi': sensor type 'ipmi' is not valid.
At line:2 char:30
+ ... Device $device | New-SensorParameters -RawType ipmi -Target * | Add-S ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SensorParameters], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PrtgAPI.PowerShell.Cmdlets.NewSensorParametersCommand

Question:
Are there certain Sensors that can't be added via the API?
If these can be added, how can we troubleshoot these errors?

Many Thanks for all you work here

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Are you sure `ipmi` is the correct name for the sensor type you wish to add?

The `Get-SensorType` cmdlet can be used to list available sensor types

```
Get-SensorType *ipmi*
```

**Comment by bmcgrath-pr** [comment]
In my defense, I have only been using your cmdlets for under a week!

That showed the Sensor is actually named ipmisensor, now working!

Thank you very much, this repo is a god send. <3
