### ISSUE TITLE
Question: can the api create new PRTG report?

### ISSUE THREAD

**Issue by fabiozanella** [lordmilko/PrtgAPI#36]
Hello!

Great framework you've created here.
How I can create a new PRTG report using powershell script?

I meant the prtg reports, not the reports based on custom queries:
https://www.paessler.com/manuals/prtg/reports

Thanks in advance,
 Fabio.

**Comment by lordmilko** [comment]
Hi @fabiozanella,

PrtgAPI does not currently support the PRTG Reporting API; reports, tickets and libraries are something that would be nice to implement, however are currently fairly low priority as I don't imagine these having fairly high use cases.

What sort of report are you trying to automate the generation of? Do you want to clone and tweak the same report a hundred times for all of your clients or something like that?

**Comment by fabiozanella** [comment]
Hi LordMilko,
We are using PRTG in order to monitor different SQL Server instances. Each
of them gets a different named instance, in different server for each
customer.
Now we have used successfully your api to create the “PerfCounter Custom”
sensors, but, as you guess, we need to create a report for each customer.

I have seen that is possible add sensor to an existing report using Passler
API, but would be nice create the report from scratch and add sensor using
your powershell.

Best regards,
  Fabio Zanella.



Il giorno ven 31 ago 2018 alle ore 15:51 lordmilko <notifications@github.com>
ha scritto:

**Comment by lordmilko** [comment]
If you run [Fiddler](https://www.telerik.com/fiddler) (ideally against a PRTG server without HTTPS) and create a new report, you will be able to see the URL that PRTG executes to create the report. The URL you are looking for in this case is the one that targets the /editsettings web page. If you simply copy the parameters that were posted to the page and append `&username=<username>=passhash=<passhash>` you can create new reports using `Invoke-WebRequest`

You can view your PassHash by doing `Get-PrtgClient`

Your final code should look similar to the following

```powershell
Invoke-WebRequest "https://prtg.example.com/editsettings?id=new&blah=123&etc=etc&username=prtgadmin&passhash=12345678"
```

By substituting specific parameter values for PowerShell variables, you can substitute the parts of the report needed to make the report apply to your specified sensor. Note that if configuring a report requires going through multiple PRTG UI web pages, you may need to execute multiple requests yourself to get the job done

**Comment by suxstellino** [comment]
hey there @lordmilko 
really cool stuff! do you know if PRTG is thinking about an API in the future? we're going to start to implement the report part (@fabiozanella is one of my peer) and I'd like to understand the effort we need for doing that "api".

**Comment by lordmilko** [comment]
Hi @suxstellino,

I don't know what Paessler's future plans for reporting related APIs are; in terms of PrtgAPI, I currently have no plans for expanding reporting API support; designing, implementing and polishing such API's is about a month's worth of effort, which at this stage I do not feel is worth it for the level of usage I envisage of the feature.

In terms of existing support, you can retrieve existing Report objects using the `Get-Object` cmdlet, and can also retrieve and report properties using `Set-ObjectProperty -RawProperty <name>` and `Get-ObjectProperty -Raw` respectively

```powershell
get-object summary* -type report|get-objectproperty -raw
```

**Comment by lordmilko** [comment]
The following is a complete example of how you would create a new report and add an object to it

```powershell
$server = "http://prtg.example.com"

# Create the report
$redirect = invoke-webrequest "$server/editsettings?name_=Report&tags_=&template_=A42+Graph+with+Data+Table+-+Graph+1h+-+Table+24h.htm&ownerid_=100%7CPRTG+System+Administrator%7C&timezone_=Taipei+Standard+Time%7C%28UTC%2B08%3A00%29+Taipei&papersize_=letter&orientation_=0&comments=&tagfilter_=&filtertag_=&scheduletype_=0&specifichour_=0&dayweek_=1&daymonth_=1&date_=&maildisk_=1&emailaddress_=&emailgroup_=-1&usecompression_=0&dataperiod_=1&reporttype_=1&reportday_=0&reportweek_=1&reportmonth_=1&reportyear_=1&schedule_=-1%7CNone%7C&percentileshow_=0&percentile_=95&percentileaverage_=300&percentilemode_=1&savedatafiles_=nofiles&reportheader_=&reportfooter_=&accessrights_=1&accessrights_=1&accessrights_201=0&objecttype=report&id=new&addid=&targeturl=%2Freport.htm%3Ftabid%3D4&username=prtgadmin&password=prtgadmin" -MaximumRedirection 0 -ErrorAction SilentlyContinue

# Extract the ID of the new report
$redirectUrl = $redirect.Headers.Location
$reportId = $redirectUrl -replace ".+id=(.+)",'$1'

# Add the object with ID 7844 to the report
Invoke-WebRequest "$server/api/reportaddsensor.htm?id=$reportId&addid=7844&username=prtgadmin&password=prtgadmin"

Write-Host "Created report $reportId"
```

**Comment by suxstellino** [comment]
Great @lordmilko,
I'm pretty sure we'd get a possible "unique" solution for SQL Server PerfCounter custom sensors. We'll come back with a PR if you'd like to review it. These counters are the "standard ones" for proactive and cycling monitoring with PRTG in a DBA powered solution. Hope this could be useful for your repo too.

**Comment by lordmilko** [comment]
Thanks @suxstellino,

PrtgAPI is mostly written in C#; as such any new functionality such as reporting needs to be accessible from both C# and PowerShell. I generally try to make PrtgAPI's cmdlets as generic as possible; that way it is easy to glue multiple pieces together to achieve a result. I can't imagine under what scenario cmdlets that targeted the reporting API would require specialized processing for a particular sensor type; regardless, feel free to post a response to this issue containing your solution if you'd like to know what I think ;)

I will close this issue for now; please let me know if you have any issues!

Regards,
lordmilko

**Comment by suxstellino** [comment]
I was actually thinking about some PrtgSQLStandardAPI, not the reports (which are something for our baseline analysis). I'd like to add a set of api for creating the custom SQL Sensors for a DBA monitoring cycle. I'll explain the real scenario in another issue.

**Comment by lordmilko** [comment]
No problem; for reference, you can create just about any sensor type using [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters)

**Comment by suxstellino** [comment]
In that case, I can add it to our repo using your proposed solution. Thanks.
