### ISSUE TITLE
Work with PRTG API-Key / API-Token

### ISSUE THREAD

**Issue by roseg-gfo** [lordmilko/PrtgAPI#360]
### What's going on?

Hello,

I would like to work with the PRTG API key/token so that a login with username/password is no longer necessary.

Is this possible?

Unfortunately, I have not been able to find any corresponding documentation here.

Thank you in advance for your feedback and support.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by roseg-gfo** [comment]
Thanks for the quick response. Basically, I wanted to switch to the API token because I am currently getting the following error message when creating new sensors and I am not sure where it comes from:

```
Could not authenticate to PRTG; the specified username and password were invalid.
    + CategoryInfo          : NotSpecified: (:) [New-Sensor], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,PrtgAPI.PowerShell.Cmdlets.NewSensor
    + PSComputerName        : hostname.domain
```

the code
`Get-Device -Host $Server | New-Sensor -ExeXml -Name "XXXX - $($Service.ServiceName)" -ExeFile $ExeFile -ExeParameters $ExeParameters | Set-ObjectProperty -Comments $InfoURL`

The connection to the PRTG server using username and password/passhash works perfectly, but unfortunately creating sensors fails

**Comment by lordmilko** [comment]
This sounds like a duplicate of #345

Can you provide the output of `Get-PrtgClient -Diagnostic`?

You may need to update to PrtgAPI 0.9.19

**Comment by roseg-gfo** [comment]
`Get-PrtgClient -Diagnostic`
```
PSVersion      : 5.1.22621.2428
PSEdition      : Desktop
OS             : Microsoft Windows 11 Enterprise
PrtgAPIVersion : 0.9.18
Culture        : de-DE
CLRVersion     : 533320
PrtgVersion    : 23.3.86.1520
PrtgLanguage   : german.lng
```
ok, i try `PrtgAPI 0.9.19`
