### ISSUE TITLE
SNMP V3 / Add New authentication method and Encryption mode

### ISSUE THREAD

**Issue by sebastien-salle** [lordmilko/PrtgAPI#362]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

in PrtgApi SNMP V3 used SHA and MD5 for authentication method. DES and AES for Encryption mode

they added several options for the authentication method SHA-224, SHA-256, SHA-384 and SHA-512 and for the Encryption mode they added AES-192 and AES-256
![prtg](https://github.com/lordmilko/PrtgAPI/assets/144334762/5acc2c18-27b6-4230-b9d1-c70a3c9298a1)

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

as it's an XML return problem by prtg, I can't get around it

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
This is related to #342

Instead of doing `Get-ObjectProperty`, you can work around this for now by doing `Get-ObjectProperty -Raw`

**Comment by sebastien-salle** [comment]
Thanks for the solution

**Comment by sebastien-salle** [comment]
Thanks for the solution
