### ISSUE TITLE
to chose the disk to create in this dynamic parameter ?

### ISSUE THREAD

**Issue by sebastien-salle** [lordmilko/PrtgAPI#363]
### What's going on?

 parameters_sensors["disk__check"] = parameters_sensors.Targets["disk__check"]; 

Do you have a solution in C# to chose the disk to create in this dynamic parameter?

Thank

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
What you've written looks correct

You can find more information on dynamic parameter targets [here](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#targets)
