### ISSUE TITLE
General Question about the PRTG API regarding to limits and channels

### ISSUE THREAD

**Issue by nook24** [lordmilko/PrtgAPI#367]
### What's going on?

Hello, I have a question about the PRTG API in general, which is not related to your library.
I need to query all sensors and all channels using the API. Due to API v2 is still in a alpha state, I need to use the API v1. I never used the PRTG API before, and using your library as a reference (I use Go lang).

The docs say that all requests are limited to 500 records, but I didn't find anything about pagination.
Is the only way to get all sensors calling `/api/table.json?content=sensors` read the value of `treesize` and call the API again using `count=<value-of-treesize>`?

Did you know of a method to query multiple sensors with channels at once? I only find a way to query the channels for each sensor separately which would probably cause a high load on the API.

I know this is super unrelated to your project and I'm sorry for the off-topic.
Many thanks in advance

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
In your PRTG installation, see the `/api.htm?tabid=3` page for information on how to paginate (the `count` and `start` parameters). You can specify `count=*` to get all objects at once, or you can request 0 objects, look at the `totalcount` field, and then paginate based on that.

```powershell
# You now know there are 31 sensors in total
http://prtg.example.com/api/table.xml?content=sensors&count=0&username=prtgadmin&password=prtgadmin

<?xml version="1.0" encoding="UTF-8"?>
<sensors totalcount="31" listend="0">
   <prtg-version>23.4.90.1299</prtg-version>
</sensors>
```

I would note however that unless you have a specific need to integrate your PRTG code with another system, you would be better off using PrtgAPI's PowerShell library to write a simple script that performs your PRTG specific needs than writing a PRTG API wrapper from scratch.

If you are still keen to use Go however, you can reverse engineer how PrtgAPI works by specifying the `-Verbose` parameter to PrtgAPI's PowerShell cmdlets. This will show you the raw API call it is making. Note that the public PRTG API is quite limited; PrtgAPI uses many undocumented API calls to provide its full suite of functionality. There is no channel API in PRTG API v1 that can retrieve all channels in the system at once like there is in PRTG API v2. I would not be concerned about the load that multiple API calls would cause however; querying the channels of a sensor with 5 channels using PrtgAPI's `Get-Channel` cmdlet would result in 6 API calls (1 for the general channel info and then another undocumented API call for each channel to get the properties Paessler doesn't expose in their public API). You only tend to run into performance issues when making modifications to PRTG; stuff like creating sensors, modifying settings, etc

**Comment by nook24** [comment]
Perfect! Many thanks for your information and time.
I appreciate this!
