### ISSUE TITLE
Library/Notification Template cmdlets in PS

### ISSUE THREAD

**Issue by Sergiu-X** [lordmilko/PrtgAPI#368]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

I am trying to create a structure amongst multiple core devices so I am doing it by creating a unique script which will be connecting on all of them and create everything with the same configuration.

I created some groups with custom tags via PrtgAPI but I cannot create libraries and add library nodes/group nodes to the library via custom tags for example and assign already existent notification templates to these libraries. Also creating and assigning a notification template via API would be helpful :) Note that I am using powershell for running my scripts.

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

Yes, you go to Libraries>Add Library then you open the library and on the management tab you select create library node and select the desired group where all the devices will be member of your library.

For notification templates you go at Setup>Notification Templates>Add Notification template and configure it then select the notification trigger to your library and make it use your customized notification template.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
There are several types of entities that PrtgAPI has limited support for, including notification actions (referred to "notifications" and "notification templates" in the PRTG UI), schedules, libraries, users and groups. While I have considered enhancing support for these objects to make PrtgAPI more "feature complete", in the past I have decided against it on the basis it would take a fairly large amount of effort for a feature I don't see most people as ever needing to use.

When you're automating something via a script, you're probably got a very large number of entities that you need to apply an action to. I question why anybody would need to create so many notification templates that they need a way to automate it. PrtgAPI does provide some support for interacting with notification templates: you can retrieve them via the `Get-NotificationAction` cmdlet and modify instances that already exist via the `Set-ObjectProperty` cmdlet. I would also question how many libraries anyone really *needs* to create.

Perhaps the biggest nail in the coffin however may be that PRTG API v2 completely breaks every single facet of PrtgAPI, so it doesn't make sense for me to invest much time into something that will disappear when PRTG API v1 support is removed from PRTG.
