### ISSUE TITLE
get-objectlog

### ISSUE THREAD

**Issue by MikeyMing** [lordmilko/PrtgAPI#372]
This just started happening yesterday,  I am guessing it cant handle some element of the new entry?

`get-objectlog -EndDate (get-date).AddDays(-1)`

`get-objectlog : Could not deserialize value '728' as it is not a valid member of type 'PrtgAPI.LogStatus'. Could not process XML '<status>Invalid Push Device</status><status_raw>728</status_raw><message><div class="lo
gmessage">New ticket: Push contact removed We removed a mobile device from your Notification Contacts because we detected that push notifications to that device cannot be delivered anymore. Most likely this is because
 you have deleted the PRTG app from your mobile device.<div class="moreicon"></div></div></message>'
At line:1 char:1
+ get-objectlog -EndDate (get-date).AddDays(-1)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ObjectLog], XmlDeserializationException
    + FullyQualifiedErrorId : PrtgAPI.XmlDeserializationException,PrtgAPI.PowerShell.Cmdlets.GetObjectLog`

```
PS C:\Windows\system32> get-module *prtg*

ModuleType Version    Name                                ExportedCommands                                                                                                                                               
---------- -------    ----                                ----------------                                                                                                                                               
Binary     0.9.5      PrtgAPI                             {Add-Device, Add-Group, Add-NotificationTrigger, Add-Sensor...}  
```

**Comment by lordmilko** [comment]
Can you please use the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) and see whether this issue is resolved in PrtgAPI 0.9.20-preview.1
