### ISSUE TITLE
Modul Signing

### ISSUE THREAD

**Issue by JonasHagendorfKZVKDO** [lordmilko/PrtgAPI#379]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

Due to Company Restrictions we can not import Modules to Powershell that are not signed (I'm sure, we are not the only one). I triedto sign it by myself but none of the used methods worked (that normaly worked on other Modules). 

Can you sign the Module and share the certficate to import it as trusted sources? 

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

no 

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
This is not something I am interested in exploring.

You may be able to bypass any signing policies by running PowerShell as follows

```powershell
powershell -bypass
```
