### ISSUE TITLE
set-objectproperty snmpv3EncryptionKey not working

### ISSUE THREAD

**Issue by farcb7** [lordmilko/PrtgAPI#382]
### Describe the bug

I'm working on trying to script out a large deployment.  I've got almost everything working except for setup of the SNMP credentials.  I noticed that although I can use set-objectproperty snmpv3password ******* without any issue, when I try to set the snmpv3EncryptionKey it is not working correctly.  The command runs fine, but SNMP doesn't respond.  If I go into the GUI and manually paste the encryption key into the field, SNMP begins working just fine.  

I also tested this by updating the both the snmpv3password and snmpv3EncryptionKey on an already setup device (tested one at a time).  I can update the snmpv3password through the API without any issue, but if I do the same with the snmpv3EncryptionKey, the SNMP sensors on the device will begin to fail until I go in and paste the key into the GUI.

### Steps to reproduce

```powershell
$device | set-objectproperty snmpv3password ****************
$device | set-objectproperty snmpv3EncryptionKey ****************
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.22621.2506
PSEdition      : Desktop
OS             : Microsoft Windows 11 Enterprise
PrtgAPIVersion : 0.9.19
Culture        : en-US
CLRVersion     : 533320
PrtgVersion    : 24.1.90.1306
PrtgLanguage   : english.lng
```

**Comment by farcb7** [comment]
I should also mention I've tried the commands both with and without quotes around the key, with no difference in results.

**Comment by lordmilko** [comment]
I wonder if maybe there's a character in the SNMP V3 Encryption Key that PrtgAPI is URL escaping

If you do `$device | set-objectproperty snmpv3EncryptionKey **************** -Verbose`

you should see the API request that PrtgAPI is executing. Does the encryption key in the URL match what you entered? If there's any characters like < > or & or a space, they'll get escaped and look different

**Comment by farcb7** [comment]
Thank you!  That was the issue.  Turns out I needed to put the key in single quotes, instead of double quotes to get it to properly pass the $ in the key.

**Comment by lordmilko** [comment]
Ah yes, correctly handling $ in strings is a common PowerShell gotcha
