### ISSUE TITLE
PRTGAPI in Powershell under Linux

### ISSUE THREAD

**Issue by JR-Otava** [lordmilko/PrtgAPI#384]
### What's going on?

Quick question.

Have you run PRTG in powershell for Linux ?
Does it work ?
If not, are you planning on making it work ?

Thanks
   JR

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
PrtgAPI is cross platform and should work on Windows, Mac and Linux

**Comment by JR-Otava** [comment]
Thank you...
