### ISSUE TITLE
Using the API to Sort Devices and Sensors Alphabetically

### ISSUE THREAD

**Issue by roseg-gfo** [lordmilko/PrtgAPI#386]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

Hey,

there is the sorting function?

Greetings Robert

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

http://[prtg-url]/api/sortsubobjects.htm?id=[object-or-group-id]

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
This can be done with the `Sort-PrtgObject` cmdlet. For more information please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Object-Organization#sorting-1)
