### ISSUE TITLE
New-SensorParameters -RawType wmivitalsystemdata -Target "*Pagefile: Usage (%) _Total*"

### ISSUE THREAD

**Issue by MikeSouthwell** [lordmilko/PrtgAPI#387]
### What's going on?

I'm trying to add the WMI Vital System Data sensors, but the "Pagefile: Usage (%) _Total" and "Pagefile: Usage (%) \??\C:\pagefile.sys" sensors have the same name and are differentiated by their instance, rather than name like the rest of the sensors.

Is there an argument similar to "-Target" that allows me to specify the "Instance"?

How can I get " -Target "*Pagefile: Usage (%)*" ", but only add the "Pagefile: Usage (%) _Total" sensor?

![image](https://github.com/lordmilko/PrtgAPI/assets/56582133/c1f2028a-ebc8-466e-8a90-3b93a7802526)

Is there perhaps a way to edit the "datafieldlist__check" attribute if you create use New-SensorParameters  with -Target "*Pagefile: Usage*" as this adds both of them and results in them both being created with Get-Device "device" | Add-Sensor $newSensor

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
PrtgAPI provides a `-Target` parameter to the `New-SensorParameters` cmdlet for convenience, however you can also customize the sensor targets selected (with more flexibility) yourself, as follows:

If you do

```
$params = New-SensorParameters -RawType wmivitalsystemdata

$params.Targets.datafieldlist__check
```
It should show you all of the options available for this field, including all of their other properties (which would include stuff like _Total and \??\C:\pagefile.sys). You should be able to filter against this list to select the ones you want

```
$params.datafieldlist__check = $params.Targets.datafieldlist__check | where <# filter by whatever you need here #>
```

**Comment by MikeSouthwell** [comment]
Thanks for clarifying @lordmilko. We will use "$params.Targets.datafieldlist__check" and filter with "Where" as suggested. 

This issue can be closed.
