### ISSUE TITLE
Use new objectproperty subproperty API for Get-Channel, etc.

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#39]
PRTG Version 18.3.44.2054 added an "official" API method for getting channel properties and other subobject properties. Get-Channel and the like should be updated to use this instead of screenscraping channeledit.htm and the like.

https://www.paessler.com/prtg/history/stable?utm_source=prtg&utm_medium=referral&utm_campaign=webgui-autoupdate

> The API call /getobjectproperty.htm now supports subnodes like, for example, channels, notification triggers, and notification contacts. For example, the call /api/getobjectproperty.htm?id=&subtype=channel&subid=0&name=limitwarningmsg&show=nohtmlencode returns the warning message that is defined for a channel limit.

**Comment by lordmilko** [comment]
It sounds like getobjectproperty.htm only supports retrieving a single property at a time however. Unless it's possible to retrieve all properties for a given channel in a single request it is still more performant to scrape channeledit.htm.

While this wouldn't have much utility in PowerShell, I can implement a new overload of `GetObjectProperty` for retrieving individual subobject properties for use in C#. I will look into shipping this feature in either PrtgAPI 0.9.2 or 0.9.3.

Thanks for bringing this to my attention!

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @JustinGrote,

This feature has now been implemented

You can now specify an `-Id`, `-SubId` and `-RawSubType` to `Get-ObjectProperty` to retrieve individual sub object properties. In C#, there is a new overload of `GetObjectPropertyRaw` that achieves the same goal.

To update to PrtgAPI 0.9.2, simply run

```powershell
Update-Module PrtgAPI
```

and reopen your PowerShell. For a full list of changes please see [the release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.2)

Regards,
lordmilko
