### ISSUE TITLE
Core Server Shows Error "probe Disconnected (disconnected)".

### ISSUE THREAD

**Issue by K10SEG** [lordmilko/PrtgAPI#391]
### What's going on?

I appreciate your urgent help because we are having the error "Probe disconnected (Disconnected)" in the CORE server and the remote probes are disconnected, the monitoring of our customers this stopped tests are performed from remote probes Core server responds without problem the core probe was updated to the latest version, Windows was restarted, but the disconnection error is still presented. we do not know why this behavior because the CORE server was working without problem, 

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by SwissJay** [comment]
I doubt this has anything to do with PRTGApi. That being said, did you give the remote probes time to update to the latest version after updating the core? This process usually takes a few minutes, depending on connection speed. We've been using PRTG for many years now and have never had this issue, with multiple remote probes.

**Comment by lordmilko** [comment]
Please contact Paessler support regarding this issue
