### ISSUE TITLE
Creating sensors with custom names

### ISSUE THREAD

**Issue by Dieg12** [lordmilko/PrtgAPI#393]
### What's going on?

Hello,

I'm trying to create custom SNMP memory sensors, I used the commands that you described in this issue : https://github.com/lordmilko/PrtgAPI/issues/66 
`$device = Get-Device "***" `
`$params = $device | New-SensorParameters -RawType snmpmemory -Target *Physical*`
`$params.Name = "Test nom custom"`
`$device | Add-Sensor $params`

However, when the sensor is created the name is still the default one for this kind of sensor : 
![image](https://github.com/lordmilko/PrtgAPI/assets/90573913/c664ab08-7e4b-4761-b3f2-3192d0ee2aaf)

Maybe I did something wrong and you can help me on that.

Thank you in advance and excuse me if my English is not perfect.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by Dieg12** [comment]
Thank you very much for the answer, does the command `Add-Sensor` return the newly created sensor so I can modify its properties directly ?

**Comment by lordmilko** [comment]
Yes

**Comment by Dieg12** [comment]
Thank you very much for the quick answer, I use PrtgAPI in my job so thank you for not leaving me stuck for too long :)
