### ISSUE TITLE
Get all devices and their (auto-discovery with specific) device templates 

### ISSUE THREAD

**Issue by u1b4n** [lordmilko/PrtgAPI#396]
#### What are you trying to do?
I want to find out which device templates are used by which devices for auto-discovery.

####  existing functionality:
Get-DeviceTemplate
Get-Device

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

The process in the UI:
1. Go to the settings of every device.
2. Under "Auto-Discovery Settings">"Auto-Discovery Level", if "Auto-discovery with specific device templates" is ticked, you can see all used device templates.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
This can be done using the `Get-ObjectProperty` cmdlet

```powershell
C:\> Get-Device -Id 1001 | Get-ObjectProperty -Raw
```

Properties of interest will be `discoverytype`, `devicetemplate` and `devicetemplate__check`. You can see what properties respond to what by inspecting the HTML on the Settings page of PRTG

**Comment by u1b4n** [comment]
Thank you so much, @lordmilko, for your fast response and help. Looks like I didn't ~read~ *search* the docs *correctly*. ^^

For future reference, this is how I solved it:
```powershell
#requires -Modules PrtgApi
Connect-PrtgServer prtg.mycoolsite.com

$devices = Get-Device | Select-Object -Property Name, Id

$deviceTemplates = ""
foreach ($device in $devices) {
    $d = Get-Device -Id $device.Id | `
        Get-ObjectProperty -Raw
    
    $deviceTemplates += $d.devicetemplate__check
}

# remove entries with no ".odt" in the name
$outp = $deviceTemplates.split("|").trim() | `
    Where-Object { $_ -like "*.odt" } | `
    Select-Object -Unique

# output the list of used device templates
$outp | Sort-Object | Format-List
```

**Comment by u1b4n** [comment]
Thank you so much, @lordmilko, for your fast response and help. Looks like I didn't ~read~ *search* the wiki *correctly*. ^^

For future reference, this is how I solved it:

**Comment by u1b4n** [comment]
Thank you so much, @lordmilko, for your fast response and help. Looks like I didn't read/search the wiki correctly. Excuse me for that!

For future reference, [here you can find how I solved it.](https://gist.github.com/u1b4n/28141ae9ea64f3e44e9af2e031bb7421)
