### ISSUE TITLE
Can connect to PRTG server, but none of the get commands give an output.

### ISSUE THREAD

**Issue by jonasvtr** [lordmilko/PrtgAPI#397]
### What's going on?

I'm trying to setup and use your module in PowerShell. I've been able to connect to my PRTG server, but sadly none of the GET commands I've tried have given me any information. They don't give errors either, which has made it hard to troubleshoot this myself, which is why I've come here for help. I was able to change the retry count and loglevel, but nothing more. The PRTG user I'm using only has read privileges at the moment, I hope this isn't what is causing this issue.
<img width="239" alt="image" src="https://github.com/user-attachments/assets/cb469372-4db4-4d6b-9cc1-b5c75d21939b">

To my knowledge, I've followed the guide completely up to this point. If you require any further information, feel free to ask for it.

All the commands I've tried so far in PowerShell.
<img width="504" alt="image" src="https://github.com/user-attachments/assets/834d318c-4e4d-4291-bb0b-a1017ff7a6f2">

I also wasn't able to do the compilation step and build, as I got errors I wasn't able to solve. See error below (was trying to build it using comandline) 
<img width="765" alt="image" src="https://github.com/user-attachments/assets/e3cf5fa3-c08f-414b-9a0e-67ecbb4d7869">

My excuses in advance if I'm making a very stupid mistake, as I'm not used to working with PowerShell modules and such.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Can you provide the output of `Get-PrtgClient -Diagnostic`

**Comment by jonasvtr** [comment]
the output of "Get-PrtgClient -Diagnostic"
<img width="852" alt="image" src="https://github.com/user-attachments/assets/b92637cc-1b26-4b34-b4b8-42a7a6b46fb6">

**Comment by lordmilko** [comment]
What version of PRTG are you running?

**Comment by jonasvtr** [comment]
We recently updated to version "24.2.96.1375"

**Comment by lordmilko** [comment]
Are you able to test with an admin user? Read-only users should work, but this will be an important troubleshooting step. My test server seems to have the same version as yours so it should work

**Comment by jonasvtr** [comment]
I just made the user read/write user with admin privileges and tested it again and it worked.
The diagnostic now looks like this:
<img width="365" alt="image" src="https://github.com/user-attachments/assets/12830986-8975-43a7-8547-1aa9ea5432eb">

I also tried another "get-sensor ping" command and it worked flawlessly. Thanks for the help, I only feel a bit stupid at the moment.
