### ISSUE TITLE
Adding a Schedule to a sensor

### ISSUE THREAD

**Issue by zarat** [lordmilko/PrtgAPI#398]
### What's going on?

I'm trying to add a new sensor using Add-Sensor and New-SensorParameters. Is there a way to add a schedule to a sensor using the API? I found this thread https://kb.paessler.com/en/topic/66047-use-api-to-assign-schedules-to-sensors but it changes the schedule of a device, not a sensor. Are the parameters used by New-SensorParameters all the available ones? 

```
@{
        name_ = "My new sensor"
        tags_ = "xmlexesensor"
        priority_ = 3
        exefile_ = ""
        exeparams_ = ""
        environment_ = 1
        usewindowsauthentication_ = 1
        mutexname_ = "testMutex"
        timeout_ = 60
        writeresult_ = 0
        intervalgroup = 0
        interval_ = "60"
        errorintervalsdown_ = 2
        sensortype = "exexml"
}
```

Friendly regards

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
You can set the schedule using `Set-ObjectProperty` after the sensor has been created. See #155 for an example of how to do this

**Comment by zarat** [comment]
Hi and thank you for the quick response. Sorry for my bad english but i am asking for the schedule returned by Get-PRTGSchedule not the notifications returned by Get-NotificationAction.

**Comment by lordmilko** [comment]
The first example in #155 shows how to do this

```powershell
Get-Probe -Id 17834 | Set-ObjectProperty -RawParameters @{
    "scheduledependency" = 0
    "schedule_" = Get-PrtgSchedule "Alerting Hours 7am ~11pm"
} -Force
```
Substitute `Get-Probe` with `Get-Sensor`
