### ISSUE TITLE
Internationalization error? XmlDeserializationException

### ISSUE THREAD

**Issue by ddobert** [lordmilko/PrtgAPI#4]
This could be an i18n error: 

`Get-Probe : An error occurred while attempting to deserialize an object of type 'Access', possibly caused by the following XML:`
`'<access>Vollzugriff</access>'. Der angeforderte Wert "Vollzugriff" konnte nicht gefunden werden.`
`In Zeile:1 Zeichen:1`
`+ Get-Probe`
`+ ~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [Get-Probe], XmlDeserializationException`
`    + FullyQualifiedErrorId : PrtgAPI.XmlDeserializationException,PrtgAPI.PowerShell.Cmdlets.GetProbe`

This is after a successful Connect-PRTGServer and a simple Get-Probe

The translation of the german lines would be
`'<access>full access</access>'. The expected value "full access" could not be found.'`
`in line: 1 character: 1`

**Comment by lordmilko** [comment]
Hi @ddobert,

That's quite interesting; I wouldn't have expected PRTG would use german to describe its internal data structures; I'd imagine this sort of thing would cause all kinds of deserialization issues!

I will do some investigation into this and get back to you when I've gotten to the bottom of this

Regards,
lordmilko

**Comment by ddobert** [comment]
Thank you and let me know if I can help with testing!

**Comment by lordmilko** [comment]
Hi @ddobert,

This issue has now been resolved. Please update to PrtgAPI 0.6.10 by executing the following command

```powershell
Update-Module PrtgAPI
```

If you had already loaded PrtgAPI in the current session, please reopen PowerShell to access the newer version.

Please let me know if you have any further issues

Regards,
lordmilko

**Comment by ddobert** [comment]
Thank you for the quick solution. I just tested it and all is well!
