### ISSUE TITLE
MultiDisk Sensor  (not channel) limits.

### ISSUE THREAD

**Issue by rwatson2** [lordmilko/PrtgAPI#400]
### What's going on?

Hello - A liitle guidance needed ref WMI MultiDisk sensor -   Is this call supported by PrtgAPI?

Get-Device  | Get-Sensor | Get-ObjectProperty  does not return properties for disk limits at the sensor level but api call supports this  (/api/getobjectproperty.htm?id=3004&name=lowerlimiterrorbyte).

get-device | get-sensor | get-channel does show properties at channel level.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
To get the limits of a multi disk sensor, do `Get-ObjectProperty -Raw`
