### ISSUE TITLE
Channel Manipulation - Set Vertical Axis Scaling

### ISSUE THREAD

**Issue by andreasloibingdorferbmdat** [lordmilko/PrtgAPI#404]
### What's going on?

Good Day,
Trying to manipulate some Channels, specifically the Vertical Axis Scaling in Ping v2 Sensors.
Seems like its not supported yet?
But also tried with Raw Properties:

$Sensor | Get-Channel "Response Time" | Set-ObjectProperty -RawParameters @{
    VerticalAxisScaling = "Manual"
    VerticalAxisMax_ = 140
    VerticalAxisMin_ = 0
    } -Force

Should this work?

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Channels are manipulated using the `Set-ChannelProperty` cmdlet, however according to `Get-Help about_ChannelSettings`, modifying vertical axis properties is not currently supported
