### ISSUE TITLE
Trying to read out a property (maybe a raw property) from a SNMP Custom String

### ISSUE THREAD

**Issue by carsten0407** [lordmilko/PrtgAPI#405]
### What's going on?

Hi LordMilko,

I am trying to read out a property (maybe a raw property) from a SNMP Custom String
Only to read out, to check if it is empty.

Thanks 

Carsten

![SNMP Custom String](https://github.com/user-attachments/assets/e64c832e-38bc-461b-a214-d44a27be167e)
![SNMP Custom String1](https://github.com/user-attachments/assets/a63494cf-9542-456b-aa0a-f991827f8054)

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Do `Get-Sensor -Id 1001 | Get-ObjectProperty -Raw`. This will list all of the properties on the settings page, which should include the property you're after
