### ISSUE TITLE
Get more Values from Get-SystemInfo -Type System (-Count not working)

### ISSUE THREAD

**Issue by m4xr1s** [lordmilko/PrtgAPI#406]
### What's going on?

Hi, I am trying to export Asset Data from PRTG.
Some Devices have a lot of entries that I need in their SystemInformation Data in the System Category.

However I can not export all the entries, since there is the limit of 500 entries for the request.
The -Count doesnt seem to work with the Get-SystemInfo Commandlet.

Is there another way to achieve this?

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by m4xr1s** [comment]
Yes it can show up to 1000 entries in the UI
From the Browser Console the request looks like this
https://FQDN/controls/table.htm?content=sysinfo&category=system&customtitle=%26%23040%3BSystem%26%23041%3B&sortby=_displayname&sortable=true&refreshable=true&columns=_key%2C_value&headers=Name%2CWert&varexpand=headers&_=1727771088426&id=9532&count=1000

**Comment by lordmilko** [comment]
Thanks @m4xr1s,

It seems like you can specify a `count` parameter to do this. PrtgAPI does not support specifying a count when requesting System Info objects. I would need to add support for doing this. Unfortunately however, I have moved on to other projects and am no longer looking to make enhancements to PrtgAPI. If the servers you're trying to query are within your domain, I would recommend using WMI via PowerShell
