### ISSUE TITLE
Get-ObjectProperty en masse or with Get-Object/Sensor/Probe/etc

### ISSUE THREAD

**Issue by unkinected** [lordmilko/PrtgAPI#408]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

We'd like to source control all our PRTG objects and their settings. Get-Object/Sensor/Probe/etc is a huge start, but we also need each individual object's settings. The Get-ObjectProperty call right now only allows you to query one object at a time, requiring a separate HTTP call for each one. When you have hundreds or thousands of objects, the paradigm of looping through the objects one-by-one and calling Get-ObjectProperty is very expensive. 

I would love a way to retrieve all object settings at once, in one call. That should be theoretically much faster than having to query each object individually (though I don't know PRTG internals, so maybe this is an impossibility). 

Perhaps alternatively, provide a way to retrieve the settings at the same time you make a call to Get-Object/Sensor/Probe/etc. Maybe with a switch parameter "-IncludeSettings."

Thanks! This product is awesome!

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

I guess the closest option is to go to the devices list, management tab, and ctrl+select multiple objects and look in the right hand settings pane. But this is rather limited in usefulness/scope.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
The "normal" PRTG API only allows retrieving a single *setting* per API request. PrtgAPI enables you to retrieve *all* settings on a given object by scraping the contents of the *Settings* page of that object, and then parsing this into a coherent object model. This is a huge step up from what PRTG "officially" supports doing via API requests; I am not aware of any mechanism that would allow retrieving the settings for *all* objects via a single API request.

If `Get-ObjectProperty` is too slow for your requirements, my recommendation would be to parse the *PRTG Configuration.dat* file directly using PowerShell. This file merely contains XML, however note that depending on how often changes are being made to your PRTG instance, *PRTG Configuration.dat* may contain out of date data (PRTG only periodically persists changes made to its config file)

**Comment by unkinected** [comment]
Thank you for the tips. I just discovered that PRTG has released a v2 API in beta, and it contains what I'm looking for, so I will switch to that. Thanks for the consideration!
