### ISSUE TITLE
Set up monitoring with changing OID

### ISSUE THREAD

**Issue by jonasvtr** [lordmilko/PrtgAPI#409]
### What's going on?

Hi,
I've been wanting to monitor the status of a IKEv2 VPN tunnel, but it's OID changes after every re-key.
For this, I was wanting to make a script that could perform an SNMP walk to read the OID and then import that oid into the sensor every couple minutes or so.

I have been looking around with the 'objectProperty' commands, but cant seem to find a way to alter the OID of a custom SNMP sensor.

Do you know how I could do this?
Worst case, I can maybe create a new sensor every time the OID changes and delete remove the old one. But I don't know if it's possible to even create a custom SNMP sensor with this module.

The vendor has recommended removing the list few digits of the OID as they are the ones that change.
But when I don't give PRTG the exact OID the sensor gives me errors.

I am using the PowerShell version of this module btw.

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @jonasvtr,

If you do `Get-Sensor -Id 1001 | Get-ObjectProperty -Raw` where `1001` is whatever the ID of this sensor is, this will show you all of the settings that exist on that sensor and their associated values, which should hopefully include the OID property

You should then be able to modify the property via the `Set-ObjectProperty` cmdlet. This property is like a read-only property; modifying read-only properties is not strictly supported by the PRTG API, however in practice it can be hit or miss whether it will actually work or not. For more information on modifying properties, please see [the wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#raw-unsupported-1)
