### ISSUE TITLE
SetObjectPropertyRaw C#

### ISSUE THREAD

**Issue by Ford0S** [lordmilko/PrtgAPI#410]
### What's going on?

Hello! Im trying to set scheduler for device, but i really cant understand how to do :(
Can u please teach me?

SetObjectPropertyRaw(id, .......) whats a name of property
tried a lot, maybe i missing something

### Due Dilligance

- [ ] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by Ford0S** [comment]
SetObjectPropertyRaw(id, .......)
tried a lot, maybe i missing something

**Comment by lordmilko** [comment]
Hi @Ford0S,

The [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#raw-unsupported-1) happens to show how to do this in PowerShell

```powershell
Get-Sensor ping | Set-ObjectProperty -RawParameters @{
    "scheduledependency" = 0
    "schedule_" = Get-PrtgSchedule "Weekdays Nine-To-Five*"
}
```
the equivalent in C# would be something like this

```c#
client.SetObjectPropertyRaw(
    1001,
    new CustomParameter("scheduledependency_", 0),
    new CustomParameter("schedule_", schedule)
);
```
where `schedule` is a `Schedule` returned from `PrtgClient.GetSchedule` / `PrtgClient.GetSchedules`

**Comment by Ford0S** [comment]
Thx @lordmilko ! 
When I try to get schedules i get exception The input string had an incorrect format
Bug or my mistake? :)

```
System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
    System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
    System.Convert.ToInt32(String value)
    PrtgAPI.Schedules.TimeTable.<>c.<InitializeSlots>b__9_0(Input i)
    System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
    System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
    System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    PrtgAPI.Schedules.TimeTable.InitializeSlots(List`1 inputs)
    PrtgAPI.Schedules.TimeTable..ctor(List`1 inputs)
    PrtgAPI.Request.ResponseParser.LoadTimeTable(Schedule schedule, String response)
    PrtgAPI.PrtgClient.GetSchedulesInternal(ScheduleParameters parameters, CancellationToken token)
    PrtgAPI.PrtgClient.GetSchedules()
```

**Comment by Ford0S** [comment]
@lordmilko 
i mean trying like this
client.GetSchedules()

**Comment by lordmilko** [comment]
This seems like a bug. Can you please advise the version of your PRTG server and what version of PrtgAPI you're using?
