### ISSUE TITLE
Clone Object

### ISSUE THREAD

**Issue by eternia** [lordmilko/PrtgAPI#42]
How to rename a cloned object with use this method:

Get-Device "$Servername*" | Clone-Object -SourceId 5603 "CPU $Servername"

**Comment by lordmilko** [comment]
`Clone-Object -SourceId` is used for cloning a single object to multiple locations with no modification. If you want to modify the cloned objects based on the device they were cloned to, you can do so using a `foreach` loop

```powershell
Get-Device "$Servername*" | foreach { $_ | Clone-Object -SourceId 5603 | Rename-Object "CPU $($_.Name)" -PassThru }
```

`$_` refers to *the current element in the pipeline* - i.e. the current device we are processing.

Inside the `foreach` loop, we refer to the device in two locations: as the input to the `Clone-Object` cmdlet as well as inside the name we pass to the `Rename-Object` cmdlet. At the end of our `foreach` block, we specify `-PassThru` to output our created objects to the pipeline.

Note that as `-PassThru` simply outputs the original object that was passed in to `Rename-Object`, these objects *won't* reflect the names we renamed them to, however if you view them in the PRTG UI or re-retrieve them you will see they have been renamed correctly.

Are you able to advise whether this answers your question?

Regards,
lordmilko

**Comment by eternia** [comment]
Perfect ! Thanks
