### ISSUE TITLE
Create WmiRemotePing

### ISSUE THREAD

**Issue by eternia** [lordmilko/PrtgAPI#44]
Hi ! How to create a wmiremoteping sensor in device (powershell) ? I have no idead to add the target (ip) parameters on this sensor

**Comment by lordmilko** [comment]
Hi @eternia,

Have you looked at the [Sensor Creation](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#sensor-creation-1) section of the wiki?

**Comment by eternia** [comment]
Yeah, just no information about add a parameters for target

**Comment by lordmilko** [comment]
The Sensor Creation page mentions that

> PrtgAPI only includes native support for a limited subset of this range. For all other sensor types, PrtgAPI defines an interface that allows custom sensor parameters to be [generated](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters) and created.

The [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell) page describes the process of creating arbitrary sensor types as a three step process
1. Identify the sensor type
2. Create the sensor parameters
3. Apply the parameters to one or more objects

For a WMI Remote Ping sensor, we can retrieve the raw sensor type from an arbitrary device

```powershell
PS C:\> get-device -count 1|get-sensortype *ping*

Id             Name             Description
--             ----             -----------
cloudping      Cloud Ping       Monitors the Ping t
ping           Ping             Monitors connectivi
ptfpingjitter  Ping Jitter      Monitors the Statis
sipoptionsping SIP Options Ping Monitors connectivi
sshremoteping  SSH Remote Ping  Remotely monitors t
wmiremoteping  WMI Remote Ping  Remotely monitors t
```

Now that we know the raw type name is *wmiremoteping*, we can construct a set of dynamic sensor parameters

```powershell
PS C:\> $params = get-device -count 1|New-SensorParameters -rawtype wmiremoteping
PS C:\> $params


targetaddress     :
timeout           : 5
buffersize        : 32
Targets           : {}
Source            : Probe Device
SensorType        : wmiremoteping
Priority          : Three
InheritTriggers   : True
InheritInterval   : True
Interval          : 00:01:00
IntervalErrorMode : OneWarningThenDown
Name              : Remote Ping
Tags              : {pingsensor, wmisensor, wmipingsensor, remotepingsensor}
Cookie            : False
```

If you have a look at the properties contained in the `DynamicSensorParameters` object, you will see there is a `targetaddress` property. This most likely corresponds to the *Target* property we are looking for

```powershell
PS C:\> $params.targetaddress = "google.com"
PS C:\> get-device -count 1 | add-sensor $params

Name                         Id     Device
----                         --     ------
Remote Ping                  8045   Probe Device
```
If we then open the device in our web browser we can see that the sensor has been successfully created

Are you able to advise whether this resolves your query?

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @eternia,

As I haven't heard back from you I will assume this answered your question. Please let me know if you have any further issues

Regards,
lordmilko
