### ISSUE TITLE
using Get-channel

### ISSUE THREAD

**Issue by xcom923** [lordmilko/PrtgAPI#45]
when I try to use Get-Channel (I've tried passing the sensor and also just using the sensor ID), I keep getting the following

Get-Channel : An error occurred while attempting to deserialize XML element 'injected_showchart': cannot assign 'null' to value type 'Boolean'.

again I've tried doing 
`$sensor | Get-Channel` 
from a for loop where $sensor is the individual sensor. I also outputted the sensor ID just to make sure that the sensor had correct data

`Get-Channel -SensorId 15210`
this one I just used the ID and I still got the same error.

**Comment by lordmilko** [comment]
Hi @xcom923,

Are you able to advise what type of sensor this is?

**Comment by xcom923** [comment]
Sorry for the delay. I thought it would be that one but I couldn't find that update installed on my machine. Then I tested this out on the PRTG server itself which is on a Win server 2012R2. I'm seeing the same error on that one. The sensor is a CPU sensor. As for the version are you talking about the API version? (0.9.2) I had just installed this and our PRTG is also the latest (to my knowledge) at 18.4.45.1898+

**Comment by xcom923** [comment]
I tried some random sensors and got the same error, so it's not just cpu types.

**Comment by lordmilko** [comment]
Hi @xcom923,

Just following up on this. Are you potentially able to advise whether you are limited to read only access on the sensors you are trying to interface with?

I am close to releasing PrtgAPI 0.9.3, which will contain a number of fixes pertaining to interfacing with PRTG with read only user permissions, This will certainly resolve your issue, however I would just like to confirm there wasn't some other reason PRTG isn't returning certain channel properties so I may include all required fixes in this release

Regards,
lordmilko

**Comment by xcom923** [comment]
I'm sorry about being a ghost on this subject. I need to get something to my superiors so I ended up using the REST API. To answer your question, yes I am using an account with RO access. We try to grant more permissions than needed. At the time I didn't think I would need anything more than RO access. Please let me know when the update is released. I'll try out the new version since I still would like to be able to use more than one tag for my project.

**Comment by lordmilko** [comment]
Hi @xcom923 ,

I have compiled a release candidate for PrtgAPI 0.9.3 which should include a fix for this issue. Can you please perform the following steps and confirm whether the issue has been resolved?

1. Download the [release candidate](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI/bin/Release/PrtgAPI.zip)
2. Right click **PrtgAPI.zip** -> **Properties**
3. On the *General* tab, under *Security* select **Unblock**
4. Unzip the file
5. Inside the extracted folder, double click the file **PrtgAPI.cmd** to open a PowerShell prompt with the  release candidate loaded in it
6. Connect to your PRTG server and confirm you can run commands like `Get-Sensor -count 1 | Get-Channel` and `Get-Sensor -count 1 | Get-ObjectProperty`

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @xcom923,

Based on my testing I am confident this issue has been resolved. As such, PrtgAPI 0.9.3 has now been released.

To update to the latest version, please run `Update-Module PrtgAPI` and then reopen PowerShell

Regards,
lordmilko

**Comment by xcom923** [comment]
Thanks for the info. Not sure if I'll be able to test it out any time
soon with the holidays coming up combined with a big EOY project
(shoot me now) I'll let you know as soon as I get a chance to test
this though.
