### ISSUE TITLE
Adding device name to get-sensorhistory query 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#46]
Hi Lord Milko,

I need to pull out CSV for a number of sensor histories on traffic sensors across a number of groups with the names included. Im running into a few issues. 

So far all i have is this paltry attempted :) 

```
goprtg 1 

$outside = get-group *Stratus* | get-sensor *Outside*
$thnsensor = get-device *THN*| get-sensor *stratus* 

foreach ($id in $outside){
Get-sensor -id $id.id | get-sensorhistory |export-csv -path "C:\output\($thnsensor).name Report Usage.csv"
}
```

But thats not selecting each ID nor is it running correctly nor is it returning anything other than device ID for identification. I can add in another step to lookup ID and then attach names but i feel like thats a really crap solution for an elegant API :)

**Comment by lordmilko** [comment]
Hi Sam,

Is this the same thing you were trying to do [previously](https://github.com/lordmilko/PrtgAPI/issues/26)?

In your code above, the `$outside` variable contains a list of `Sensor` objects. As such, there is no need to *re-retrieve* these objects inside the `foreach` loop - they can simply be piped straight to `Get-SensorHistory`. You appear to have the general right idea, however the reference to `($thnsensor).name` in the `Export-Csv -Path` looks both wrong and suspicious (it should either be `$($thnsensor.name)` or `$($id.device)`

Are you able to advise whether this answers your question?
