### ISSUE TITLE
httppushdataadvanced 

### ISSUE THREAD

**Issue by eternia** [lordmilko/PrtgAPI#50]
Hi !

It's possible to get the value GUID of an httppushdataadvanced ?

**Comment by lordmilko** [comment]
Hi @eternia,

You can get any property of a sensor not supported by PrtgAPI by using `Get-ObjectProperty` with the `-Raw` parameter

```powershell
Get-Sensor -Type httppushdataadvanced | Get-ObjectProperty -Raw
```

It sounds like the property you may be after may be the "httppushtoken" that will be output from this command

Does this answer your question?

Regards,
lordmilko

**Comment by lordmilko** [comment]
`Get-ObjectProperty` does get properties of existing sensors. Can you please try the command advise whether it retrieves the information you are looking for.

For more information please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#unsupported-properties-1)
