### ISSUE TITLE
Running autodiscover on a created device with powershell? 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#51]
Hi there, i notice you have a C# method for triggering an autodiscover on an existing device. Sadly my C# is even worse than my powershell so working out how to port this to powershell or indeed work out if it is possible are worse than my usual troubleshooting :P 

Before i embarass myself infront of a dev, is this possible :)

**Comment by lordmilko** [comment]
Where did you notice there is a C# method for performing an auto-discovery?
