### ISSUE TITLE
Problem with fixed timeout

### ISSUE THREAD

**Issue by Rebkas** [lordmilko/PrtgAPI#52]
The timeout in the method WaitForSensorTargetResolution is set to 60s which is to short for the method GetDynamicSensorParameters. I experience the same when I do it in the prtg interface: it takes more than one minute. Could you please make the timeout adjustable, maybe in the constructor or as a property? 
Regards

Dieter

**Comment by lordmilko** [comment]
What type of sensor parameters are you trying to retrieve that take more than 60 seconds?

**Comment by Rebkas** [comment]
Those sensors are WMI Sensors. Sometimes, but very rarely, they answer within a minute. I guess the problem ist the big number of WMI Sensors.

Regards

Dieter Good
Softwareingenieur Informatik

dieter.good@swibi.ch<mailto:dieter.good@swibi.ch>
________________________________


[SWIBI Logo]<http://www.swibi.ch/>

[SWIBI LinkedIn]<https://www.linkedin.com/company/swibi-ag>  [SWIBI Youtube] <https://www.youtube.com/channel/UCdSUkRgar8lgWVQZ9k1qImQ>




[Oranges Quadrat]
_______SWiBi AG
_______Bahnhofstrasse 51
_______CH-7302 Landquart
_______T: +41 58 458 60 00<tel:+41%2058%20458%2060%2000>
_______F: +41 58 458 60 89
_______info@swibi.ch<mailto:info@swibi.ch>
_______www.swibi.ch<http://www.swibi.ch>


Haben Sie die SWiBiNEWS<https://www.swibi.ch/#anmeldung-swibinews> abonniert und folgen Sie uns auf LinkedIn<https://www.linkedin.com/company/swibi-ag> sowie Youtube<https://www.youtube.com/channel/UCdSUkRgar8lgWVQZ9k1qImQ>? Dadurch bleiben Sie stets aktuell informiert - rund um Ihre Energie.


Von: lordmilko <notifications@github.com>
Gesendet: Dienstag, 18. Dezember 2018 13:13
An: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Good Dieter <Dieter.Good@swibi.ch>; Author <author@noreply.github.com>
Betreff: Re: [lordmilko/PrtgAPI] Problem with fixed timeout (#52)


What type of sensor parameters are you trying to retrieve that take more than 60 seconds?

**Comment by lordmilko** [comment]
Thanks @Rebkas,

I will implement a `timeout` parameter for retrieving sensor targets / dynamic sensor parameters and hopefully release PrtgAPI 0.9.4 within the next couple of days

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @Rebkas,

PrtgAPI 0.9.4 has now been released, which includes a fix for this issue. You can now update PrtgAPI from the NuGet Package Manager or by running `Update-Package PrtgAPI` from the NuGet Package Manger Console

For a full list of changes please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.4)

Regards,
lordmilko

**Comment by Rebkas** [comment]
Hi lordmilko
Downloaded and testet: perfekt! Thank you very much!
Regards
Dieter
