### ISSUE TITLE
All Triggers

### ISSUE THREAD

**Issue by oretom** [lordmilko/PrtgAPI#53]
Hello

Is there a way to retrieve all triggers from our system? Like $SensorList=Get-Sensor  will get all sensors, but when I use this with $TriggerList= Get-Trigger an object is needed

Is there a simple way to get all triggers?

BR
Thomas

**Comment by lordmilko** [comment]
Hi @oretom,

Notification Triggers are classified as *sub-objects* - their existence depends upon a *primary* object such as a sensor, device, group or probe. As such, it is not possible to retrieve information about notification triggers without also specifying the object the triggers pertain to.

If you want to enumerate all triggers in your system, I would recommend requesting a list of all sensors, devices, groups and probes, and then iterating over each one to retrieve any notification triggers found within.

```powershell
PS C:\> (Get-Sensor),(Get-Device),(Get-Group),(Get-Probe) | foreach { $_ | Get-Trigger -Inherited:$false }

Type      ObjectId SubId Inherited ParentId Latency Condition Threshold Unit       OnNotificationAction
----      -------- ----- --------- -------- ------- --------- --------- ----       --------------------
State     1001     1     False     1001     900     Equals    Down                 Email and push notifi...
State     1002     1     False     1002     900     Equals    Down                 Email and push notifi...
Threshold 2055     4     False     2055     75      Equals    7                    Email and push notifi...
Change    2055     5     False     2055             Change                         Ticket Notification...
State     2055     1     False     2055     70      Equals    Down                 Email and push notifi...
Speed     2055     2     False     2055     80      Below     30        Kbit/Min   Email and push notifi...
Volume    2055     3     False     2055             Equals    5         KByte/Day  Email to all members...
State     0        1     False     0        600     Equals    Down                 Ticket Notification
```

By specifying `-Inherited:$false` we ensure we only retrieve the triggers defined on each object we query; we will retrieve the inherited triggers when we query the object they were defined on.

Regards,
lordmilko

**Comment by oretom** [comment]
Hello
This I know, but this takes for ever. I wanted to have a quick dump of of all triggers. 
Thx
