### ISSUE TITLE
Modifying a traffic sensor to include more channels

### ISSUE THREAD

**Issue by jones-g** [lordmilko/PrtgAPI#54]
When autodiscovering a network device ports are imported as "SNMP Traffic Sensor". By default the sensor includes channels for Traffic In, Traffic Out and Traffic Total.

By modifying the sensor in the PRTG web interface it is possible to enable additional channels like so:
![traffic sensor](https://user-images.githubusercontent.com/5399484/50966251-aaa3e200-14d4-11e9-870d-ec02eab4bf3f.png)

Is there a way to modify this via API? I have about 94 sensors right now that I need to set additional channels on and would very much prefer to do this in one go :)

We are on 18.4.47.1962.

**Comment by lordmilko** [comment]
Hi @jones-g,

As these channels are simply settings on the sensor object, you can enable these channels using the `Set-ObjectProperty` cmdlet

```powershell
Get-Sensor -Type snmptraffic | Set-ObjectProperty -RawProperty trafficmode_ -RawValue errors,discards
```

You can see the names to use for each channel by viewing the page's HTML (Ctrl+Shift+J in Chrome then use the selector to select one of the checkboxes)

```html
<input type="checkbox" class="checkbox" name="trafficmode_" value="errors" checked="checked" id="trafficmode_errors" style="display: none;">
```

The `value` of each checkbox is the name you should use to enable it

Are you able to advise whether this answered your question?

Regards,
lordmilko

**Comment by jones-g** [comment]
Hi @lordmilko,

This is exactly what I was looking for. Thank you! I though that the -RawProperty might be the way to do it but unaware of how. And with the disclaimer on the Wiki about modifying Raw properties I wasn't about to just jump in :)
