### ISSUE TITLE
latest build

### ISSUE THREAD

**Issue by eternia** [lordmilko/PrtgAPI#58]
Hi,

The link for download the latest build (manual install) are broken. Possible to fix it ? because i need for install on old server (powershell V3...) thx

**Comment by lordmilko** [comment]
Hi @eternia,

Thanks for raising this issue. The URL has been fixed. You can download the latest build [here](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.PowerShell/bin/Release/PrtgAPI.zip).

In addition, you can also find all released builds under [releases](https://github.com/lordmilko/PrtgAPI/releases)

Regards,
lordmilko
