### ISSUE TITLE
Object reference not set to an instance of an object in Powershell ISE

### ISSUE THREAD

**Issue by Chopp3rDave** [lordmilko/PrtgAPI#62]
I'm new to the project and looking forward to using this module for some powershell scripts. I'm having an issue where if I run the code to make a connection to a PRTG server in the ISE I get the error:

```powershell
Connect-PrtgServer : Object reference not set to an instance of an object.
At line:7 char:1
+ Connect-PrtgServer -Server $PRTGServer -Credential $PRTGCredential -P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PrtgServer], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,PrtgAPI.PowerShell.Cmdlets.ConnectPrtgServer

The specific commands I am running:
$PRTGServer = "myservername"
$PRTGCredential = ""
$PRTGUser = "myusername"
$PRTGPassHash = "mypasshash"

$PRTGCredential = New-Credential -UserName $PRTGUser -Password $PRTGPassHash
Connect-PrtgServer -Server $PRTGServer -Credential $PRTGCredential -PassHash -IgnoreSSL
```
If I run the exact same code in a standard powershell window it works. It only fails in the ISE (both running as administrator under the same user).

**Comment by lordmilko** [comment]
Hi @Chopp3rDave,

After you get this error can you please run the command `$Error[0].Exception.StackTrace` and output the result?

Can you also confirm the version of PrtgAPI you are running? You can do this by typing
```powershell
ipmo prtgapi; gmo prtgapi
```

In addition, can you also confirm what version of the PowerShell ISE you're running and on what version of Windows. You can check the version of the PowerShell ISE by typing

```powershell
$PSVersionTable
```

**Comment by Chopp3rDave** [comment]
> After you get this error can you please run the command $Error[0].Exception.StackTrace and output the result?

`PS C:\> $Error[0].Exception.StackTrace
   at PrtgAPI.Request.PrtgWebClient..ctor(Boolean ignoreSSL, String server)
   at PrtgAPI.PowerShell.Cmdlets.ConnectPrtgServer.Connect(PSCmdlet cmdlet)
   at System.Management.Automation.CommandProcessor.ProcessRecord()`

> Can you also confirm the version of PrtgAPI you are running?

PS C:\> ipmo prtgapi; gmo prtgapi

ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Binary     0.9.5      PrtgAPI                             {Add-Device, Add-Group, Add-NotificationTrigger, Add-Sensor...}

> In addition, can you also confirm what version of the PowerShell ISE you're running and on what version of Windows.

PS C:\> $PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.17763.316                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.17763.316                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1       

Please let me know anything else I can provide.

**Comment by lordmilko** [comment]
Thanks @Chopp3rDave,

This tells me the issue exists in one of the few lines of code in the [PrtgWebClient constructor](https://github.com/lordmilko/PrtgAPI/blob/master/PrtgAPI/Request/PrtgWebClient.cs#L22-L38)

There are an extremely small number of lines that could be at fault here; my best guess would be that your `DefaultWebProxy` is somehow `null`

Can you please advise what the output of the following command is?

```powershell
[Net.WebRequest]::DefaultWebProxy -eq $null
```

**Comment by Chopp3rDave** [comment]
Indeed it is True, while my powershell session is False.

**Comment by lordmilko** [comment]
Thanks @Chopp3rDave,

According to MSDN, it is a perfectly valid scenario for this value to potentially be `null` (though you would not normally expect it to be `null` by default). As such, this is definitely a bug in PrtgAPI. I will include a fix in PrtgAPI 0.9.6 due out in a few weeks which will resolve this issue.

Are you able to advise what you changed the `DefaultWebProxy` to? *SystemWebProxy* or something to that effect?

**Comment by Chopp3rDave** [comment]
I tried to set it manually to just http://localhost:80. However it does not appear to be persistent. After restarting the ISE, it is back to $null. I'm still researching how to change this in the ISE to not be null and have it remain that way.

**Comment by lordmilko** [comment]
In the ISE, can you run `notepad $profile` and confirm whether you have anything in your PowerShell profile?

**Comment by Chopp3rDave** [comment]
#Script Browser Begin
#Version: 1.3.2
Add-Type -Path 'C:\Program Files (x86)\Microsoft Corporation\Microsoft Script Browser\System.Windows.Interactivity.dll'
Add-Type -Path 'C:\Program Files (x86)\Microsoft Corporation\Microsoft Script Browser\ScriptBrowser.dll'
Add-Type -Path 'C:\Program Files (x86)\Microsoft Corporation\Microsoft Script Browser\BestPractices.dll'
$scriptBrowser = $psISE.CurrentPowerShellTab.VerticalAddOnTools.Add('Script Browser', [ScriptExplorer.Views.MainView], $true)
$scriptAnalyzer = $psISE.CurrentPowerShellTab.VerticalAddOnTools.Add('Script Analyzer', [BestPractices.Views.BestPracticesView], $true)
$psISE.CurrentPowerShellTab.VisibleVerticalAddOnTools.SelectedAddOnTool = $scriptBrowser
#Script Browser End
# load all 'autoload' scripts
#get-childitem "C:\Users\da_carter\OneDrive for Business\Code\Powershell\AutoLoad\*.ps1" | %{.$_}

**Comment by Chopp3rDave** [comment]
I just cleared it out, and reloaded ise and [Net.WebRequest]::DefaultWebProxy -eq $null is now False. Not sure exactly which line resulted in the change yet.

**Comment by lordmilko** [comment]
Hi @Chopp3rDave,

Please be advised that PrtgAPI 0.9.6 has now been released, which includes a fix for this issue.

To update to the latest version, run the command

```powershell
Update-Module PrtgAPI
```

Then close and reopen PowerShell

For more information on the changes in this release, please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.6)

Regards,
lordmilko
