### ISSUE TITLE
Get-SensorTarget WmiService Exception

### ISSUE THREAD

**Issue by MCC79** [lordmilko/PrtgAPI#64]
Hi Lord Milko,

i'm getting the following error when querying a service that is in StopPending status
` $device | Get-SensorTarget WmiService wuauserv`
Even if the service I query is Started/Stopped it will fail if another service is in StopPending
```
Get-SensorTarget : Requested value 'Stop Pending' was not found.
At line:1 char:11
+ $device | Get-SensorTarget WmiService wuauserv
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SensorTarget], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,PrtgAPI.PowerShell.Cmdlets.GetSensorTarget

```

Thanks!

**Comment by lordmilko** [comment]
Hi @MCC79,

Are you able to advise what version of PrtgAPI you're running? Run `Get-Module PrtgAPI` after you experience this error to see

It sounds like you're running a version prior to [PrtgAPI 0.9.1](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.1), which should have fixed this issue

> Changed WmiServiceTarget.Status from type ServiceControllerStatus to new type WmiServiceStatus

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @MCC79,

Just following up on this. Are you able to advise regarding the above?

**Comment by MCC79** [comment]
Hi Lordmilko,

I can't reproduce the error anymore.  Having version 0.9.1

Thanks!

**Comment by lordmilko** [comment]
Looking at the changes made for PrtgAPI 0.9.1 I feel like I may have found an issue wherein some of the various *pending* types could fail to deserialize properly. This could be what was causing the issues you were experiencing.

I have resolved this issue and will include these changes in PrtgAPI 0.9.6, hopefully due in a week or two

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @MCC79,

Please be advised that PrtgAPI 0.9.6 has now been released, which should include a fix for this issue

To update to the latest version of PrtgAPI, run

```powershell
Update-Module PrtgAPI
```

and reopen PowerShell. For more information on the changes in the latest release, please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.6)

Regards,
lordmilko

**Comment by MCC79** [comment]
thanks a lot! doing it now :)

Regards!
mcc
