### ISSUE TITLE
PowerShell: Modify only one notification trigger

### ISSUE THREAD

**Issue by ITHole** [lordmilko/PrtgAPI#68]
Well, another think that I now tried but didn't establish. I want to modify just ONE notification trigger.

In the [Wiki](https://github.com/lordmilko/PrtgAPI/wiki/Notification-Triggers#modify-1) there is only a description how to change one or all properties of ALL triggers at once. But in my case I just want to modify a specific trigger.

For example, I have some triggers for sensor with id 3251.
```
PS C:\Windows\system32> $paramsEdit = Get-Sensor -Id 3251 | Get-Trigger
PS C:\Windows\system32> $paramsEdit

Type      ObjectId SubId Inherited ParentId Latency Condition Threshold Unit       OnNotificationAction
----      -------- ----- --------- -------- ------- --------- --------- ----       --------------------
Threshold 3251     11    False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     6     False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     12    False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     14    False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     13    False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     2     False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     1     False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     3     False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     5     False     3251     86400             20                   E-Mail an IT Manager senden
Threshold 3251     4     False     3251     86400             20                   E-Mail an IT Manager senden
```
Now I want to just modify e.g. the property `Latency` for the second trigger (SubId 6). How can I do that. Is there any way. If not, can you add a functionality to do so. 

Cheers

**Comment by lordmilko** [comment]
Hi @ITHole,

Simply run the following command

```powershell
Get-Sensor -Id 3251 | Get-Trigger | where SubId -eq 6 | Edit-TriggerProperty Latency 400
```

Are you able to advise what you mean by "tried but didn't establish" however? Are you saying on the [latest version](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.PowerShell/bin/Release/PrtgAPI.zip) your issue with custom HTTPS ports was not resolved?

Regards,
lordmilko

**Comment by ITHole** [comment]
> Are you able to advise what you mean by "tried but didn't establish" however? Are you saying on the [latest version](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.PowerShell/bin/Release/PrtgAPI.zip) your issue with custom HTTPS ports was not resolved?

No, I meant that I didn't solve how to change just one trigger! Gonna check the SSL issue as soo as possible. Maybe I can do that not before Friday :(
