### ISSUE TITLE
PRTG Maps

### ISSUE THREAD

**Issue by sofyane123** [lordmilko/PrtgAPI#70]
Hello,
i would like to copy maps from old core server to a new one . in there an way to perform that ?.

Best regards

**Comment by lordmilko** [comment]
Hi @sofyane123,

Interesting question. I would say the only way you can do this is to create a new map on your new server, then replace its XML in `C:\ProgramData\Paessler\PRTG Configuration.dat` with the definition from your old server (updating any ID references to the ID of the new server). Take a backup of your configuration file first in case it doesn't go well

Failing that, you may need to contact Paessler support, stressing you don't care whether it's *supported* or not, you just want to know what you can possibly *try*

Regards,
lordmilko

**Comment by SwissJay** [comment]
@sofyane123 
> Interesting question. I would say the only way you can do this is to create a new map on your new server, then replace its XML in `C:\ProgramData\Paessler\PRTG Configuration.dat` with the definition from your old server (updating any ID references to the ID of the new server). Take a backup of your configuration file first in case it doesn't go well

I have done exactly this as I migrated PRTG from one server to another and it works. The only downside is that the core service has to be shutdown while you edit the configuration file. Just be very careful and take your time while making the changes.

Paessler really needs to step up on this as copying a map as XML from one instance to another is not wizardry and could be done easily through the PRTG web GUI.

Cheers,
Jay
