### ISSUE TITLE
GetSensorHistory - Get raw value

### ISSUE THREAD

**Issue by iambigred** [lordmilko/PrtgAPI#71]
Hi,

Currently it appears that the raw data values are not accessible from the GetSensorHistory method.  Is my understanding correct?  Is there any way to retrieve these?

Thanks,
Alex

**Comment by lordmilko** [comment]
Hi @iambigred,

I can see you're right, currently only the display value is accessible.

I will rename the current `Value` property to `DisplayValue` and add add a new `Value` property containing the raw value in the next release of PrtgAPI. Until then I believe you'll need to continue manipulating the current `Value` property to try and get a numeric value.

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @iambigred,

Please be advised that PrtgAPI 0.9.7 has now been released, which includes a fix for this issue

The existing `ChannelHistoryRecord.Value` member has been renamed to `DisplayValue`, and a new `Value` property containing the raw value has been added. The new `Value` property will always be expressed in the lowest unit value possible for a given channel (e.g. if the `DisplayValue` is in megabytes, the `Value` will be in bytes)

Also note that the `SensorHistoryData` type has been renamed to `SensorHistoryRecord`. To update to the latest version, run

```powershell
Update-Package PrtgAPI
```

from within the NuGet Package Manager. For a full list of changes (including any breaking changes that may affect you) please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.7)

Regards,
lordmilko
