### ISSUE TITLE
Rename Group

### ISSUE THREAD

**Issue by eternia** [lordmilko/PrtgAPI#73]
Hi !

Is possible to rename a group with the API ? Or i need to create a new group and clone object and loose all my data of my object ?

**Comment by lordmilko** [comment]
```powershell
Get-Group -Id 1001 | Rename-Object "New Name"
```

For more information please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Object-Organization#renaming-1)

Regards,
lordmilko
