### ISSUE TITLE
New-DeviceParameters

### ISSUE THREAD

**Issue by eternia** [lordmilko/PrtgAPI#74]
Why is not functionnal:

 $newdevice = New-DeviceParameters "$serverName"  "$serverIp"
                        $newdevice.windowslogindomain = "$auth[0]"
                        $newdevice.windowsloginusername = "$auth[1]"
                        $newdevice.windowsloginpassword = "$auth[2]"

**Comment by lordmilko** [comment]
Type the following command

```powershell
$newdevice
```

You will get output similar to the following

```powershell
Host                  : dc-1
IPVersion             : IPv4
AutoDiscoveryMode     : Manual
AutoDiscoverySchedule : Once
DeviceTemplates       :
Name                  : dc-1
Tags                  :
Cookie                : False
```

As you can see, the `New-DeviceParameters` cmdlet does not have properties called `windowslogindomain`, `windowsloginusername` or `windowsloginpassword`. For maintainability purposes the `NewDeviceParameters` type only supports the most critical properties pertinent to device objects.

To set these properties you will need to first create the device and then set the properties afterwards using the `Set-ObjectProperty` cmdlet

```powershell
$device = Get-Group -Id 1001 | Add-Device $serverName $serverIp
$device | Set-ObjectProperty -WindowsDomain $auth[0] -WindowsUserName $auth[1] -WindowsPassword $auth[2]
```
