### ISSUE TITLE
Set ChannelSetting 

### ISSUE THREAD

**Issue by ClemensLasslesberger** [lordmilko/PrtgAPI#76]
Hi

I Tried to set a channel Proberty with the API using smth like this.

Get-Sensor -Id ##### |Get-Channel -Id # |Set-ChannelSetting LimitsEnabled False
Get-Sensor -Id ##### |Get-Channel -Id # |Set-ChannelSetting ValueLookup eventlog

When I Try to change this it doesnt switch to the lookup values. Only if I open the channel in the gui and press ok or apply, it switches to the Lookup I specified. I Figured out that it has something to do with the DisplayLastValue setting..

Kind Regards and many thanks upfront 

C

**Comment by lordmilko** [comment]
Hi @ClemensLasslesberger,

It seems when the ValueLookup is specified, PRTG requires it be specified in the form

```powershell
<name>|<name>
```

PrtgAPI is not currently serializing it in this format. It appears that certain sensors (such as SNMP, which my Integration Test suite tests against) may not be as sensitive to this incorrect format, hence why this issue has not been detected.

Are you able to advise whether it works if you execute the following?

```powershell
Get-Sensor -Id ##### |Get-Channel -Id # |Set-ChannelSetting ValueLookup "eventlog|eventlog"
```

Regards,
lordmilko

**Comment by ClemensLasslesberger** [comment]
Hey Lord Milko 

Thank you very much this fixed the issue. 

Cheers, 
Clemens

**Comment by lordmilko** [comment]
Hi @ClemensLasslesberger,

Please be advised that PrtgAPI 0.9.7 has now been released, which includes a fix for this issue. To update to the latest version of PrtgAPI, run

```powershell
Update-Module PrtgAPI
```

and reopen PowerShell. For a full list of changes in this release, including any breaking changes, please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.7)

Regards,
lordmilko
