### ISSUE TITLE
Dynamic Sensor Parameters -> SNMP Traffic

### ISSUE THREAD

**Issue by Z3nto** [lordmilko/PrtgAPI#79]
Hi @lordmilko  ,

there is a little thing i need your help with.
At the moment I'm working with the Dynamic Sensor Parameters. I try to create SNMP Traffic sensors with it.
I want this sensors to additionally monitor the errors and discards, but I'm not able to figure out how to add more then one.

Thats my Code:
```c#
DynamicSensorParameters dynamicParameters = PRTGclient.GetDynamicSensorParameters(device, "snmptraffic");
dynamicParameters["trafficmode"] = "errors";
dynamicParameters["interfacenumber__check"] = dynamicParameters.Targets["interfacenumber__check"].Where(t => t.Properties.Contains("Connected"));
List<Sensor> sensor = PRTGclient.AddSensor(device, dynamicParameters);
```
I've already tried a few thinks like `dynamicParameters["trafficmode"] = "errors, discards";` or `dynamicParameters["trafficmode"] = "errors discard";`, but I can't find the solution

At browser I can see that the query to addsensor5.htm has 3 times the "trafficmode_" parameter:
```javascript
trafficmode_: standinfornoselection
trafficmode_: errors
trafficmode_: discards
```
Is there anything I've missed?

Thanks,
Z3nto

**Comment by lordmilko** [comment]
Hi @Z3nto,

You are not [the first person](https://prtg.hrblock.com.au/addsensor4.htm?id=9530&tmpid=46) to encounter this issue!

Based on my [resolution](https://github.com/lordmilko/PrtgAPI/issues/12#issuecomment-383469361) I would conclude that your issue is you are not thinking object orientedly enough :P

```c#
dynamicParameters["trafficmode"] = new[]{"errors", "discards"};
```

Please let me know how you go

Regards,
lordmilko

**Comment by Z3nto** [comment]
Hi @lordmilko,

it works! Thank you!!
Maybe you can add this hint to your wiki? :)

BR, Z3nto

**Comment by lordmilko** [comment]
Hi @Z3nto,

Good idea; the wiki has been updated accordingly

Regards,
lordmilko
