### ISSUE TITLE
Is there a way to create sensors for specific IIS App Pools?

### ISSUE THREAD

**Issue by ninjo99** [lordmilko/PrtgAPI#81]
Hello,

I've been trying to create IIS App Pool sensors (sensor type pciisapppool) but I can't seem to figure out how to specify what app pool to monitor with this sensor. Is it possible to do this with the API?

Thanks!

**Comment by lordmilko** [comment]
Hi @ninjo99,

To create an IIS App Pool sensor you need to create a set of [DynamicSensorParameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell) and then specify the targets the sensor parameters should apply to

```powershell
C:\> $params = Get-Device -Id 1001 | New-SensorParameters -RawType pciisapppool
C:\> $params

instance          : 1
instance__check   : _Total
Targets           : {[instance__check, PrtgAPI.Targets.GenericSensorTarget[]]}
Source            : exch-1
SensorType        : pciisapppool
Priority          : Three
InheritTriggers   : True
InheritInterval   : True
Interval          : 00:01:00
IntervalErrorMode : OneWarningThenDown
DynamicType       : False
Name              : Base Sensor
Tags              : {performancecounter, pciisapppool}
Cookie            : False
```

The app pool targets can be found under the `$params.Targets.instrance__check` property. Specify any targets you want to the `$params.instance__check` property and then create the sensor

```powershell
C:\> $params.instance__check = $params.Targets.instance__check | where { $_.Name -eq "_Total" -or $_.Name -eq ".NET v4.5" }

C:\> Get-Device -Id 1001,1002,1003 | Add-Sensor $params
```

You can also specify a wildcard value to the `-Target` parameter of the `New-SensorParameters` cmdlet to have it populate the desired targets for you

For more information please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell)

Regards,
lordmilko
