### ISSUE TITLE
Powershell New-SearchFilter -Property device -Operator NotEquals

### ISSUE THREAD

**Issue by Rtw915** [lordmilko/PrtgAPI#82]
I think this should work. 

New-SearchFilter -Property device -Operator NotEquals "server.domain.com"
'New-SearchFilter : Cannot filter where property 'Device' notequals 'server.domain.com'. PRTG only supports filters where string values 'Equal' or 'Contain' other string values.
At line:1 char:1
+ New-SearchFilter -Property device -Operator NotEquals "rds.nbsupply.c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SearchFilter], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,PrtgAPI.PowerShell.Cmdlets.NewSearchFilter'

**Comment by lordmilko** [comment]
Hi @Rtw915,

You think it should, but I think you'll find that it doesn't :P

PrtgAPI knows that PRTG is unable to execute certain types of requests and tries to protect you from these by throwing an exception so you aren't wondering why PRTG returned spurious results. If you think that PrtgAPI is wrong, you can bypass these validations by specifying the `-Illegal` parameter to `New-SearchFilter

```powershell
$filter = New-SearchFilter device NotEquals server.domain.com -Illegal
$filter | Get-Sensor -Verbose
```

On my system the `-Verbose` parameter shows me my request correctly contains the string `filter_device=@neq(server.domain.com)`; regardless of whether or not I have a device called this however I always get no results. As such, the only way to filter string values is client side

```powershell
Get-Sensor | where device -ne server.domain.com
```

Regards,
lordmilko
