### ISSUE TITLE
get-objectproperty failed

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#84]
get-device -tag *power* | get-objectproperty "Name" , "DependentObjectId"

Error:
Get-ObjectProperty : Cannot bind parameter 'Property'. Cannot convert value "DependentObjectId" to type "PrtgAPI.ObjectProperty". Error: "Unable to match the identifier name
DependentObjectId to a valid enumerator name. Specify one of the following enumerator names and try again:
Active, InheritLocation, Location, LocationName, InheritWindowsCredentials, WindowsDomain, WindowsUserName, WindowsPassword, InheritLinuxCredentials, LinuxUserName,
LinuxLoginMode, LinuxPassword, LinuxPrivateKey, WbemProtocolMode, WbemPortMode, WbemPort, SSHPort, SSHElevationMode, SSHElevationSuUser, SSHElevationSudoUser,
SSHElevationPassword, SSHEngine, InheritVMwareCredentials, VMwareUserName, VMwarePassword, SNMPPortNameTemplate, SNMPPortNameUpdateMode, SNMPPortIdMode, SNMPInterfaceStartIndex, SNMPInterfaceEndIndex, InheritChannelUnit, BandwidthVolumeUnit, BandwidthSpeedUnit,
BandwidthTimeUnit, MemoryUsageUnit, DiskSizeUnit, FileSizeUnit, InheritAccess, Name, Tags, Priority, DebugMode, Url,ProxyPassword, Timeout, PingPacketSize, PingMode, PingCount, PingDelay, AutoAcknowledge,
InheritInterval, Interval, IntervalErrorMode, GraphType, ExeFile, ExeParameters, SetExeEnvironmentVariables, UseWindowsAuthentication, Database,
UseCustomInstance, InstanceName, SqlEncryptionMode,  InheritTriggers, Comments,
Host, Hostv4, Hostv6, ServiceUrl, AutoDiscoveryMode, AutoDiscoverySchedule"

**Comment by lordmilko** [comment]
Hi @mafer0410,

PrtgAPI does not currently support retrieving the `DependentObjectId` property directly (and in fact, from my testing PRTG doesn't appear to support this). To retrieve this property you must use the `Get-ObjectProperty` cmdlet with no parameters, which you can then reduce to just the `Name` and `DependentObjectId` properties using the `Select-Object` cmdlet

```powershell
Get-Device -tag power | Get-ObjectProperty | select Name,DependentObjectId
```

Regards,
lordmilko

**Comment by mafer0410** [comment]
Hi, i need your help.
