### ISSUE TITLE
On resume do not enable sensors that were already paused?

### ISSUE THREAD

**Issue by embusalacchi** [lordmilko/PrtgAPI#88]
When using the UI or Web Interface when you pause and then resume a device the previously paused sensors stay paused.  For example - a device in our DR site may have services stopped by design and the sensor for that service is paused:

web1 -> IIS Service (paused) and ping (enabled)

If you pause web1 in the interface and then resume the web1 device will come back in the same state - IIS Service (paused) and ping (enabled).  When I use PowerShell I am not seeing the same behavior.  This may be in fact because I am missing something, so I do apologize if that's the case.  Here's the Powershell I'm using to pause / resume -

```
foreach ($server in $allWindowsServers) {

Write-Output "Pausing $server ... "
Get-Device -Name $server | Pause-Object -Duration 180 -Message "Octopus Deploy"

}
```

And then when we're done with the deploy I'm running the following -

```
foreach ($server in $allWindowsServers) {

Write-Output "Resuming $server ... "
Get-Device -Name $server | Resume-Object

}
```

Is there a way to accomplish the same behavior?

**Comment by lordmilko** [comment]
Hi @embusalacchi,

I performed the following test and was unable to replicate this behavior

```powershell
# Pause some ping sensor
Get-Sensor -Id 2056 | Pause-Object -Duration 100

# Pause the ping sensor's parent device
Get-Device -Id 2001 | Pause-Object -Forever

# Resume the device
Get-Device -Id 2001 | Resume-Object
```

Upon doing this the ping sensor was still paused. In addition, another sensor under this device that was already pause forever remained paused.

Are you potentially able to construct and test a specific list of steps that can be used to replicate the behavior?

**Comment by embusalacchi** [comment]
> Hi @embusalacchi,
> 
> I performed the following test and was unable to replicate this behavior
> 
> ```powershell
> # Pause some ping sensor
> Get-Sensor -Id 2056 | Pause-Object -Duration 100
> 
> # Pause the ping sensor's parent device
> Get-Device -Id 2001 | Pause-Object -Forever
> 
> # Resume the device
> Get-Device -Id 2001 | Resume-Object
> ```
> 
> Upon doing this the ping sensor was still paused. In addition, another sensor under this device that was already pause forever remained paused.
> 
> Are you potentially able to construct and test a specific list of steps that can be used to replicate the behavior?

Thank you for your reply - I will construct a test tomorrow and send it along.

**Comment by embusalacchi** [comment]
So I spent the better part of today and I cannot seem to reproduce this now.  There must have been something wrong in my initial testing / deployment.  Thank you for looking into this and I apologize for waisting your time.  Have a good day!
