### ISSUE TITLE
Add-group not a valid cmdlet 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#9]
Hi, add-group (and other add-xx) are not working it appears returning that it is not a valid cmdlet name. 

any guidance appreciated :)  

This api has changed my life by the way thank you so much

**Comment by lordmilko** [comment]
Hi @SamuelmAsh,

Can you please run `Get-Module PrtgAPI` and confirm which version you're running?

**Comment by lordmilko** [comment]
Hi @SamuelmAsh,

Were you able to solve this issue?

**Comment by lordmilko** [comment]
No response. Closing issue. Will reopen if issue resurfaces.
