### ISSUE TITLE
If Valid get-device

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#90]
Hello, good, sorry for the inconvenience, try to create a script with a menu of options. In option 1 is to create dependencies, the function works correctly, but I would like to validate that when a user enters a host and does not exist in the PRTG database, it is told, and asked to enter a host again.
![01](https://user-images.githubusercontent.com/51204835/59886633-05434300-937d-11e9-8de3-f7f9dd222230.PNG)
![02](https://user-images.githubusercontent.com/51204835/59886634-05dbd980-937d-11e9-800c-4f15f9b91d6b.PNG)
![03](https://user-images.githubusercontent.com/51204835/59886636-05dbd980-937d-11e9-8eba-78ea6b114f9d.PNG)
[PRTGAPI PJ Dependencias - copia.txt](https://github.com/lordmilko/PrtgAPI/files/3312351/PRTGAPI.PJ.Dependencias.-.copia.txt)

**Comment by lordmilko** [comment]
Hi @mafer0410,

Devices can be retrieved from PRTG using the `Get-Device` cmdlet. If a device does not exist, `Get-Device` will not return anything

```powershell
$device = Get-Device exch-1

if(!($device))
{
    Write-Host "Could not find device!"
}
```
If you want to retrieve devices by the `Host` property of the device (i.e. its IP Address, HostName or DNS name) you can do this via the `-Host` property

```powershell
$device = Get-Device -Host 192.168.0.1

if(!($device))
{
    Write-Host "Could not find device!"
}
```

Based on this information, you can construct a loop to continuously prompt a user to specify either a device name or a hostname until they enter one that is valid

```powershell
$name = Read-Host "Please specify a device name"

$device = Get-Device $name

while($device -eq $null)
{
    $name = Read-Host "Could not find a device with name '$name'; please specify a valid device name"

    $device = Get-Device $name
}

Write-Host "Using device '$($device.Name)' (Host: $($device.Host))"
```
