### ISSUE TITLE
Can't Deserialize Non-English StandardTriggerChannel Values

### ISSUE THREAD

**Issue by lordmilko** [lordmilko/PrtgAPI#91]
When PrtgAPI attempts to retrieve triggers it currently calls `table.xml` which returns the string representation of the specified channel which is then deserialized to a `StandardTriggerChannel` where applicable. When PRTG is not in English however PrtgAPI does not know what to deserialize the channel to and so throws an `InvalidStateException`, assuming that the channel is corrupt.

Investigate using `triggers.json` in conjunction with `tables.xml` to specify all the properties of the triggers (including their parent IDs)

**Comment by mafer0410** [comment]
204/5000
Hello, sorry for the delay, I was really right, for the change of languages, PrtgAPI does not recognize the word. I changed the language of the PRTG to English and introduced English words, and it worked correctly.
