### ISSUE TITLE
SNMP traffic -- additional channels

### ISSUE THREAD

**Issue by keebluk** [lordmilko/PrtgAPI#92]
Hi, 

I am trying to figure out how to pull object properties for 'additional channels' under SNMP traffic sensors. Basically I want to see what is and isn't enabled.
Is that currently possible at this time? Thank you lordmilko!

**Comment by lordmilko** [comment]
Hi @keebluk,

This information can be retrieved using the `Get-ObjectProperty` cmdlet and inspecting the `trafficmode` property

```powershell
C:\> Get-Sensor -Id 1001 | Get-ObjectProperty -Raw

name        : WAN Traffic
trafficmode : unicast nonunicast
....
```

You can then transform the `trafficmode` property into an array by using the `-split` operator

```powershell
C:\> $properties = Get-Sensor -Id 1001 | Get-ObjectProperty -Raw
C:\> $sensor.trafficmode -split " "

unicast
nonunicast
```

PRTG will not tell you what *isn't* enabled, only what *is*. If you inspect the HTML of the checkboxes for all additional channels you will be able to see the list of valid values, and then based on this determine which ones are missing

Regards,
lordmilko
