### ISSUE TITLE
How to break the inheritance of a trigger?

### ISSUE THREAD

**Issue by douglasgaigher** [lordmilko/PrtgAPI#94]
All devices inherits their notification trigger from a common parent. I would like to customize the properties of a specific device. How to break the inheritance of a trigger in this device?

**Comment by lordmilko** [comment]
Hi @douglasgaigher,

PRTG considers this to be an object property, despite the fact it doesn't actually appear on the object's Settings page.

As such, you can modify this value by modifying the `InheritTriggers` property using the `Set-ObjectProperty` cmdlet

```powershell
Get-Device -Id 1001 | Set-ObjectProperty InheritTriggers $false
```

Regards,
lordmilko
