### ISSUE TITLE
Create notification

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#95]
Hello again, I am creating a command that creates notifications to a specific device, it really works correctly but I have a question. When creating the notification, enter the type of notification, the action to be taken and the latency. As shown in the images, create a speed type notification, and it appears in the PRTG, but where "when condition clears after a notification weas triggered, perform no notification" appears, how can I add an option to this feature?
![01](https://user-images.githubusercontent.com/51204835/60545169-a4e6c680-9cd7-11e9-83b0-ec76dbaabecd.png)
![02](https://user-images.githubusercontent.com/51204835/60545171-a57f5d00-9cd7-11e9-9eb1-022ed95178f3.png)

**Comment by mafer0410** [comment]
similarly I would like to edit when it is a status notification.
![01](https://user-images.githubusercontent.com/51204835/60545833-402c6b80-9cd9-11e9-8d35-30d0a62da911.png)
![02](https://user-images.githubusercontent.com/51204835/60545835-402c6b80-9cd9-11e9-9d46-55e396510aef.png)

**Comment by lordmilko** [comment]
To view all the properties of an object in PowerShell pipe it to the `Formtat-List` cmdlet

```powershell
Get-Probe | Get-Trigger | fl
```

To modify the escalation notification action specify `EscalationNotificationAction`

**Comment by mafer0410** [comment]
a question, can the JOIN structure be used when making queries with the commands get-device, get-sensor etc in the PRTGAPI?

**Comment by lordmilko** [comment]
What is a JOIN structure?

**Comment by mafer0410** [comment]
The JOIN structure is the one used in SQL, for example, when you execute
the following command:
Get-Sensor | select Name, ParentId


The device ID to which the sensor belongs appears but instead of the Id
appearing, I would like the device name to appear with the following
command:
get-device | select Name, Id

but try to join both commands with AND and it did not work, try with the
JOIN structure but it also did not work, in the following way:

$ a = Get-Sensor | select Name, ParentId
$ b = get-device | select Name, Id

$ a Join $ b -on ParentId = Id

**Comment by lordmilko** [comment]
There is no such thing as JOIN in PowerShell
