### ISSUE TITLE
notification - name device

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#97]
Hello, I'm wanting to show notifications of devices by probe, group, etc. When displaying the notifications of the devices of a probe, I would like you in the information of the services by the name of the host of the device, to know on which device it belongs. How could I perform that action?
![01](https://user-images.githubusercontent.com/51204835/60680415-72a8a680-9e48-11e9-8d5f-db43bcd322f7.PNG)

**Comment by lordmilko** [comment]
```powershell
$devices = get-probe "Sonda Local" | get-device

$allTriggers = @()

foreach($device in $devices)
{
    $triggers = $device | get-trigger -SubId $elnot
    $triggers | Add-Member Device $device.Name
    $triggers | Add-Member Group $device.Group
    $triggers | Add-Member Probe $device.Probe

    $allTriggers += $triggers
}

$allTriggers | Export-Csv C:\allTriggers.csv -NoType
```

**Comment by mafer0410** [comment]
but I want the table to show the name of the object to which the notification belongs, if it is a probe, a group, etc.

**Comment by lordmilko** [comment]
Hi @mafer0410,

To show the owning object type you can do the following

```powershell
$devices = get-probe "Sonda Local" | get-device

$allTriggers = @()

foreach($device in $devices)
{
    $triggers = $device | get-trigger -SubId $elnot
    
    foreach($trigger in $triggers)
    {
        $owner = Get-Object -Id $trigger.ParentId
        $trigger | Add-Member OwningObjectType $owner.Type.Value
    }

    $allTriggers += $triggers
}

$allTriggers | Export-Csv C:\allTriggers.csv -NoType
```

**Comment by mafer0410** [comment]
Hello, in the image, I have a separate code and mail perfectly, but if I
put that code in a program that I have, it does not run. why?

**Comment by lordmilko** [comment]
Hi @mafer0410,

I can't see any image attached; however, please refrain from posting screenshots of code - instead simply paste the code into your message and surround it with ``` code tags at the start and end

**Comment by mafer0410** [comment]
Hello, I'm sorry about the images,
I attached 3 screenshots of the code of a program, what it does is modify notifications in groups from a probe or a group. The user enters the characteristics of the notifications that he wants to search first to modify them later, for example, he wants to look for the status notifications and that they are in Down only, but when he shows that list, he does not appear or take the conditions as an or, sample notifications that are state-like or have status in Down.
![01](https://user-images.githubusercontent.com/51204835/60909590-d877a280-a23b-11e9-92b1-681f3567d9d0.png)
![02](https://user-images.githubusercontent.com/51204835/60909591-d9103900-a23b-11e9-9af7-a7d848b33e5f.png)
![03](https://user-images.githubusercontent.com/51204835/60909592-d9103900-a23b-11e9-9fd2-2b63e0d72527.png)

**Comment by mafer0410** [comment]
of the program that I do, it's the only thing I'm missing and I have a problem, because if the user enters two characteristics of a notification, for example Type = State and State = Down, all the notifications that contain one or both characteristics appear, and what I need is to show those in which both are applied.

**Comment by lordmilko** [comment]
I am not going to go through your screenshots - partially written in another language - to debug your issue. As stated above if you want assistance you need to provide the actual code that you are using so I can actually try running it myself to figure out what is wrong with it

**Comment by mafer0410** [comment]
Hello, I'm sorry for the delay, I was making the program changes. I send
you the script of the program that I have made: the user is asked for a
name of either a probe or a group, or the name of a label, then a list of
the devices that belong to the group or label entered must appear. Then
with the present list, the user enters some filters to show specific
notifications, for example, the list has 3 status notifications down and 2
status notifications up, and if the user wants to see only notifications of
state down with only 150's interval, enter it and that list appears.

with the updated list, modify the elements present in a group with the new
properties that he would enter.

Where the error occurs is when the first list appears and when trying to
apply the filter, it does not do it, or takes the values as if they were
"O", that is, if you enter the data: "down" state and interval "150 ",
notifications with status" down "or containing the interval" 150 "appear

**Comment by mafer0410** [comment]
Additionally added some code cap
![01](https://user-images.githubusercontent.com/51204835/61254125-b214a400-a720-11e9-839a-fdbca48a2611.PNG)
![02](https://user-images.githubusercontent.com/51204835/61254126-b2ad3a80-a720-11e9-8a7c-3244d13788e3.PNG)
![03](https://user-images.githubusercontent.com/51204835/61254127-b345d100-a720-11e9-9881-e0b4d6bbe984.PNG)
![04](https://user-images.githubusercontent.com/51204835/61254128-b3de6780-a720-11e9-85cc-53b12eecb755.PNG)
![05](https://user-images.githubusercontent.com/51204835/61254129-b3de6780-a720-11e9-8f10-7530559b3545.PNG)
![06](https://user-images.githubusercontent.com/51204835/61254130-b476fe00-a720-11e9-9b80-2a2a36faef21.PNG)





tures

**Comment by lordmilko** [comment]
Give me the actual text of your script instead of screenshots if you want assistance

**Comment by mafer0410** [comment]
# Cycle to delete several notifications individually
[string]$contador='Y'
while ($contador -eq 'Y') {
$decimo= Read-Host "`r`n1.Device group.`r`n2.Tag.`r`n`r`nEnter an option"
for($k=1; $k -le 2; $k++){
   # If you do not enter a value
   if (!$decimo) {
       $decimo=Read-Host "`r`nEnter a value"
       $k=1

   # If you do not enter a valid value
   } elseif ($decimo -ne 1 -and $decimo -ne 2) {
       $decimo=Read-Host "`r`nEnter a valid option"
       $k=1

   # Use a group or tag to modify the notifications of the devices
contained in it
   } elseif (($decimo -eq 1) -or ($decimo -eq 2)){
       cls
# Use a group or tag to modify the notifications of the devices contained
in it
   } elseif (($decimo -eq 1) -or ($decimo -eq 2)){
       cls
       # If a group name, be it probe or device group
       if (($decimo -eq 1) -and ($decimo -ne 2)) {
             $nomgr = read-Host "`r`nEnter a group name"
             # If the group does not exist, request the name again
             $group = get-object -Name $nomgr
             while (!($group)) {
                 Write-Host "`r`nThe name does not exist."
                 $nomgr = read-host "`r`nEnter a group name"
                 $group = get-object -Name $nomgr
             }
             # show the list of notifications that exist in the devices of
the group previously entered
             if(!(get-group -Name $nomgr) -and ($decimo -eq 1)) {
                 $notson = get-probe | where Name -eq $nomgr| get-device |
 get-Trigger | where Inherited -eq $false | select
SubId,Type,State,Latency,OnNotificationAction,EscalationLatency,EscalationNotificationAction,RepeatInterval,OffNotificationAction
| format-table -AutoSize
                 $notson
             } elseif(!(get-probe -Name $nomgr) -and ($decimo -eq 1)) {
                 $notson = get-group | where Name -eq $nomgr | get-device |
get-Trigger | where Inherited -eq $false | select
SubId,Type,State,Latency,OnNotificationAction,EscalationLatency,EscalationNotificationAction,RepeatInterval,OffNotificationAction
| format-table -AutoSize
                 $notson
             }
       # If it's a tag
       } elseif ($decimo -eq 2)  {
             $tag= read-Host "`r`nEnter the tag of the devices"
             # If the tag exists
             $grta = get-device -tag $eti
             while (!($grta)) {
                  Write-Host "`r`nThe tag does not exist."
                  $tag = read-host "`r`nEnter a tag name"
                  $grta =a get-device -tag $tag
             }
             $notson = get-device -Tag $tag | get-Trigger | where Inherited
-eq $false | select
SubId,Type,State,Latency,OnNotificationAction,EscalationLatency,EscalationNotificationAction,RepeatInterval,OffNotificationAction
| format-table -AutoSize
             $notson
       }
       # Select items from the list to present with the following search
characteristics
       write-host "`r`nSearch for notifications"
       $type = read-host "`r`nEnter the notification type"
       $state = read-host "`r`nEnter the state to search"
       $latency = read-host "`r`nEnter the fallen time to search"
       $onnotifi = read-host "`r`nEnter the action to search"
       $esclat = read-host "`r`nEnter the wait time to search"
       $esclnotifi = read-host "`r`nEnter the action to execute"
       $interval = read-host "`r`nEnter the interval to be evaluated"
       $ofnotifi = read-host "`r`Enter the action to take when you leave
the state $state"
       if (!($type)) {
          $type = $null
       } elseif (!($state)) {
          $state = $null
       } elseif (!($latency)) {
          $latency  = $null
       } elseif (!($onnotifi)) {
          $onnotifi = $null
       } elseif (!($esclat)) {
          $esclat = $null
       } elseif (!($esclnotifi)) {
          $esclnotifi = $null
       } elseif (!($interval)) {
          $interval = $null
       } elseif (!($ofnotifi)) {
          $ofnotifi = $null
       }

       # Make the modifications
       # If a group name
       if ($decimo -eq 1) {
           # If it is a probe
           if(!(get-group -Name $nomgr)) {
                # show a list of notifications with the features or
properties entered by the user previously
                $q = Get-Probe | where Name -eq $nomgr | get-device |
get-Trigger -Inherited $false -Type $type -State $state -Latency $null
-OnNotificationAction $onnotifi -EscalationLatency $esclat
-EscalationNotificationAction $esclnotifi -RepeatInterval $interval
-OffNotificationAction $ofnotifi
                $q
                # New characteristics of the elements to be modified
                write-host "`r`nEnter the new features"
                $ntype = read-host "`r`nEnter the notification type"
                $nstate = read-host "`r`nnter the state to be valuated"
                $nlatency = read-host "`r`nEnter the time fallen to
evaluate"
                $nonnotifi = read-host "`r`nEnter the action to execute"
                $nesclat = read-host "`r`nEnter the waiting time to
evaluate"
                $nesclnotifi = read-host "`r`nEnter the action to execute"
                $ninterval = read-host "`r`nEnter the interval to be
evaluated"
                $nofnotifi = read-host "`r`nEnter the action to take when
you leave the state $state"
                # Execution of the command
                $q = Get-Probe | where Name -eq $nomgr | get-device |
get-Trigger -Inherited $false -Type $type -State $state -Latency $latency
-OnNotificationAction $onnotifi -EscalationLatency $esclat
-EscalationNotificationAction $esclnotifi -RepeatInterval $interval
-OffNotificationAction $ofnotifi | Set-TriggerProperty -State $nstate
-Latency $nlatency -OnNotificationAction $nonnotifi -EscalationLatency
$nesclat -EscalationNotificationAction $nesclnotifi -RepeatInterval
$ninterval -OffNotificationAction $nofnotifi
          # If it is a group
          } elseif(!(get-probe -Name $nomb)) {
                # show a list of notifications with the features or
properties entered by the user previously
                $r = Get-Group | where Name -eq $nomgr | get-device |
get-Trigger -Inherited $false -Type $type -State $state -Latency $latency
-OnNotificationAction $onnotifi -EscalationLatency $esclat
-EscalationNotificationAction $esclnotifi -RepeatInterval $interval
-OffNotificationAction $ofnotifi
                $r
                # New characteristics of the elements to be modified
                write-host "`r`nEnter the new features"
                $ntype = read-host "`r`nEnter the notification type"
                $nstate = read-host "`r`nnter the state to be valuated"
                $nlatency = read-host "`r`nEnter the time fallen to
evaluate"
                $nonnotifi = read-host "`r`nEnter the action to execute"
                $nesclat = read-host "`r`nEnter the waiting time to
evaluate"
                $nesclnotifi = read-host "`r`nEnter the action to execute"
                $ninterval = read-host "`r`nEnter the interval to be
evaluated"
                $nofnotifi = read-host "`r`nEnter the action to take when
you leave the state $state"
                # Execution of the command
                $q = Get-group | where Name -eq $nomgr | get-device |
get-Trigger -Inherited $false -Type $type -State $state -Latency $latency
-OnNotificationAction $onnotifi -EscalationLatency $esclat
-EscalationNotificationAction $esclnotifi -RepeatInterval $interval
-OffNotificationAction $ofnotifi | Set-TriggerProperty -State $nstate
-Latency $nlatency -OnNotificationAction $nonnotifi -EscalationLatency
$nesclat -EscalationNotificationAction $nesclnotifi -RepeatInterval
$ninterval -OffNotificationAction $nofnotifi
          }
       }
       # Ask if you want to modify another group of notifications
       $contador= read-Host "`r`nDo you want to continue [Y or N]"
       # Validate response
       while ($contador -ne 'Y' -and  $contador -ne 'N') {
           $contador= read-Host "`r`nEnter a valid option.`r`n`r`nDo you
want to continue [Y or N]"
       }
       # If you do not want to add more, you leave the function
       if ($contador -eq 'N') {
           get-probe | where Name -eq $sonda | get-device | get-Trigger |
where Inherited -eq $false
           exit
       }
       $k++
   }
}
$j=2

**Comment by lordmilko** [comment]
I have gone through your code and found the following issues
1. Your code is not very well formatted; this makes it difficult to read and understand where control structures begin and end and what's inside them. I had to go through and manually indent things so I was even able to read it. Every time you do a pair of braces `{ }` everything inside them should be indented the same amount by hitting the tab key once

```powershell
if($something)
{
    while($somethingElse)
    {
        if($thirdThing)
        {
            Write-Host "Bye"
        }
    }
}
elseif($otherThing)
{
    Write-Host "Hi"
}
```
2. Inside your `for` loop where you analyze the `decimo` value that was entered you have a duplicate `elseif` block that checks `($decimo -eq 1) -or ($decimo -eq 2)`

```powershell
        elseif (($decimo -eq 1) -or ($decimo -eq 2))
        {
            cls
            # Use a group or tag to modify the notifications of the devices contained in it
        }
        elseif (($decimo -eq 1) -or ($decimo -eq 2))
        {
            cls
            # If a group name, be it probe or device group
            if (($decimo -eq 1) -and ($decimo -ne 2))
...
```
As a result of this, the second block containing all of your actual code will never be reached. You should remove the block which simply contains the call to `cls`

3. Inside the main block you ask the user to enter a group name

```powershell
$nomgr = read-Host "`r`nEnter a group name"
```

however from the code that comes next you *actually* want the user to enter a group *or* probe; this is confusing

4. You have a line that says this

```powershell
elseif(!(get-probe -Name $nomb))
```

However no variable has been defined that has the name `$nomb`, so this is completely illegal. Perhaps this should be `$nomgr`?

5. PrtgAPI currently expects that any parameter specified to the `Get-Trigger` cmdlet will have a value. In your case however you are specifying a whole bunch of different parameters that may or may not have been given a value

```powershell
$q = Get-Probe | where Name -eq $nomgr | get-device | get-Trigger -Inherited $false -Type $type -State $state -Latency $null -OnNotificationAction $onnotifi -EscalationLatency $esclat `
                    -EscalationNotificationAction $esclnotifi -RepeatInterval $interval -OffNotificationAction $ofnotifi
```
Specifying `$null` for certain parameters can result in the cmdlet crashing with an `ArgumentNullException`. I have opened ticket #99 to track the progress of this issue

As a workaround for this, I recommend you use [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6) to construct a hashtable containing only the parameters that have actually been assigned values

```powershell
$triggerParams = @{
    Inherited = $false
}

if($type)
{
    $triggerParams.Type = $type
}
if($onnotifi)
{
    $triggerParams.OnNotificationAction = $onnotifi
}
if($esclat)
{
    $triggerParams.EscalationLatency = $esclat
}
# etc

$q = Get-Probe | where Name -eq $nomgr | get-device | get-Trigger @triggerParams
```

6. After we retrieve the notification triggers defined under our group or probe, you then ask the user to enter some *new* property values to be used by the triggers, and then you do this

```powershell
$q = Get-Probe | where Name -eq $nomgr | get-device | get-Trigger -Inherited $false -Type $type -State $state -Latency $latency -OnNotificationAction $onnotifi -EscalationLatency $esclat `
                    -EscalationNotificationAction $esclnotifi -RepeatInterval $interval -OffNotificationAction $ofnotifi | Set-TriggerProperty -State $nstate -Latency $nlatency -OnNotificationAction $nonnotifi -EscalationLatency $nesclat -EscalationNotificationAction $nesclnotifi -RepeatInterval $ninterval -OffNotificationAction $nofnotifi
```
Firstly, this line is very bad for performance. You already received the triggers you're after above, simply pipe `$q` into the `Set-TriggerProperty` cmdlet directly. Secondly, once again you're specifying values for properties that don't necessarily have values - maybe that's an issue or maybe it's not, but potentially it might be worth utilizing the hashtable technique described above. Thirdly, many of these properties are only available on `State` notification triggers, however what if I entered a `Speed` trigger? PrtgAPI would throw an `InvalidOperationException` explaining that `Speed` triggers do not have an `EscalationNotificationAction` property, among other things.

7. I don't understand what the point of this script is. It seems like you are trying to develop a menu for managing the properties of your notification triggers. Why? Do you really need to be modifying so many properties of your notification triggers every so often? I would present that the entire functionality of this script could be achieved in a couple of one-liners, depending on what you want to do.

In regards to your initial query, I am not exactly sure what the issue is, however if you are really keen on persuing this I would recommend you learn how to use the [PowerShell ISE debugger](https://devblogs.microsoft.com/scripting/use-the-debugger-in-the-windows-powershell-ise/). This will allow you to step through your script one line at a time and check the values of your variables to see what's going on

**Comment by mafer0410** [comment]
I also made a shorter script, which performs the same functions but if the
user enters a group name, the problem is that when you enter the search
values, you do not perform the following command lines.


[string]$contador='Y'
while ($contador -eq 'Y')
{
  $decimo= Read-Host "`r`n1.Device group.`r`n2.Tag.`r`n`r`nEnter an option"
  for($k=1; $k -le 2; $k++)
  {
    # If you do not enter a value
    if (!$decimo)
    {
       $decimo=Read-Host "`r`nEnter a value"
       $k=1

    # If you do not enter a valid value
    }
    elseif ($decimo -ne 1 -and $decimo -ne 2)
    {
       $decimo=Read-Host "`r`nEnter a valid option"
       $k=1

    # Use a group or tag to modify the notifications of the devices
contained in it
    }
    elseif (($decimo -eq 1) -or ($decimo -eq 2))
    {
       cls
       # If a group name, be it probe or device group
       if (($decimo -eq 1))
       {
           $nomgr = read-Host "`r`nEnter a group name"
           # If the group does not exist, request the name again
           $group = get-object -Name $nomgr
             while (!($group))
             {
                Write-Host "`r`nThe name does not exist."
                $nomgr = read-host "`r`nEnter a group name"
                $group = get-object -Name $nomgr
             }
             # show the list of notifications that exist in the devices of
the group previously entered
             if(!(get-group -Name $nomgr) -and ($decimo -eq 1))
             {
             # If a null or empty return is because the name does not
belong to a group, but to a probe.
                 $notson = get-probe | where Name -eq $nomgr| get-device |
 get-Trigger | where Inherited -eq $false | select
SubId,Type,State,Latency,OnNotificationAction,EscalationLatency,EscalationNotificationAction,RepeatInterval,OffNotificationAction
| format-table -AutoSize
                 $notson
             }
             # If a null or empty return is because the name does not
belong to a probe, but to a group.
             elseif(!(get-probe -Name $nomgr) -and ($decimo -eq 1))
             {
                 $notson = get-group | where Name -eq $nomgr | get-device |
get-Trigger | where Inherited -eq $false | select
SubId,Type,State,Latency,OnNotificationAction,EscalationLatency,EscalationNotificationAction,RepeatInterval,OffNotificationAction
| format-table -AutoSize
                 $notson
             }
             # Select items from the list to present with the following
search characteristics
             write-host "`r`nSearch for notifications"
             $type = read-host "`r`nEnter the notification type"
             $state = read-host "`r`nEnter the state to search"
             $latency = read-host "`r`nEnter the fallen time to search"
             $onnotifi = read-host "`r`nEnter the action to search"
             $esclat = read-host "`r`nEnter the wait time to search"
             $esclnotifi = read-host "`r`nEnter the action to execute"
             $interval = read-host "`r`nEnter the interval to be evaluated"
             $ofnotifi = read-host "`r`nEnter the action to take when you
leave the state $state"
             # if the entered values are not null
             $triggerParams = @{
              Inherited = $false
             }
             if($type)
             {
               $triggerParams.Type = $type
             }
             if($state)
             {
               $triggerParams.State = $state
             }
             if($latency)
             {
               $triggerParams.Latency = $latency
             }
             if($onnotifi)
             {
               $triggerParams.OnNotificationAction = $onnotifi
             }
             if($esclat)
             {
               $triggerParams.EscalationLatency = $esclat
             }
             if($esclnotifi)
             {
               $triggerParams.EscalationNotificationAction = $esclnotifi
             }
             if($interva)
             {
               $triggerParams.RepeatInterval = $interva
             }
             if($ofnotifi)
             {
               $triggerParams.OffNotificationAction = $ofnotifi
             }
             # show a list of notifications with the features or properties
entered by the user previously
             $q = Get-Group | where Name -eq $nomgr | get-device |
get-Trigger @triggerParamsbro
             $q
       }
    }
 }
}

**Comment by mafer0410** [comment]
Hello good afternoon, did you receive the new edition of the Powershell
script code?

**Comment by lordmilko** [comment]
Please see my previous comment above. If you are really keen on persuing this I would recommend you learn how to use the [PowerShell ISE debugger](https://devblogs.microsoft.com/scripting/use-the-debugger-in-the-windows-powershell-ise/). This will allow you to step through your script one line at a time and check the values of your variables to see what's going on

**Comment by mafer0410** [comment]
Hello,
Regarding the comment you mention, I read it and applied the references or
advice in the script, and it is shorter. Would you send it again?

**Comment by lordmilko** [comment]
I don't understand what you're asking, however as stated you need to use the PowerShell ISE debugger to diagnose this issue yourself.
